### ISSUE TITLE
Trouble while uploading Images with "colons" in the filename

### ISSUE THREAD

**Issue by offlinehoster** [owncloud/android#1139] opened 2015-09-05 08:49 UTC
Uploading an image with the name "IMG_20150620_171941:nopm:.jpg" is failing.

After renaming the filename to IMG_20150620_171941.jpg it is working fine.

This happens on a Samsung S6 with current official Android 5.1.1 and ownCloud Android app 1.7.2

The photo was original taken on the same Samsung S6 camera app.

**Comment by LukeOwncloud** [comment] 2015-09-07 11:52
Duplicate of https://github.com/owncloud/android/issues/604

**Closed by LukeOwncloud** 2015-09-07 11:52 UTC
