### ISSUE TITLE
make bitrise public

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#2990] opened 2020-10-06 09:29 UTC
Bitrise should be make public in order to ensure external contributors to see the test result of their pull requests. This would be mandatory to ensure external contributions.

Since it would requires us to do more work to get our instrumentation tests running on github actions we decided to stay with bitrise for now. Further reasons can be found here:
https://github.com/owncloud/android/pull/2988

**Comment by abelgardep** [comment] 2020-10-06 09:45
Posible duplicate of https://github.com/owncloud/android/issues/2767 ?

**Closed** 2020-10-06 11:42 UTC
Labels: Feature request
