### ISSUE TITLE
Upload failed: could not be copied to owncloud local directory

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/android#101] opened 2013-03-05 13:11 UTC
I cannot upload files.
It may be because my phone's internal memory does not have so much space left. But 14MB should be enough for a photo. 
My SD card has lots of space.

**Comment by jksinton** [comment] 2015-04-11 11:57
I'm getting this problem on Moto X, Android Version 4.4.  When I try to upload a file from the phone's "Downloads," this error is produced in the notification bar.

In other words, I go to the Downloads app.  Then, I long hold a file I wish to upload to bring up the share icon.  I press the share icon and choose ownCloud, and finally choose a directory on my ownCloud drive.  It won't upload the file.

OC server is OC 8.0.1 on Ubuntu.

I can successfully upload a file from the Google Drive app to ownCloud.  Also, I was able to make a new folder.

**Comment by jksinton** [comment] 2015-04-15 05:44
I've reproduced this issue on an emulated device running android-19.

**Comment by tobiasKaminsky** [comment] 2015-04-16 06:46
You are right.
But the problem seems to be limited only to the download app.

**Comment by jksinton** [comment] 2015-04-16 14:30
For some reason, the download app Intent object is passing the wrong path to the local file:

public int onStartCommand(Intent intent, int flags, int startId) {
...
 } else { // mUploadType == UPLOAD_MULTIPLE_FILES
...
localPaths = new String[] { intent.getStringExtra(KEY_LOCAL_FILE) };
...
I added a Log_OC.d to view the contents of localPath in obtainNewOCFileToUpload(String remotePath, String localPath, String mimeType, FileDataStorageManager storageManager)

At least this is what I have been able to uncover from one night of debugging.

Regards,
James

**Comment by jksinton** [comment] 2015-04-18 21:27
It seems the bug is actually in uploadFiles() from Uploader.java.

For a PDF, Uri.decode(uri.toString()) does not actually provide the localPath to the file.  Also, for an Image file, i.e. mimeType.contains("image"), the columns projection do not match for the URI: content://com.android.providers.downloads.documents/document/. Thus, ownCloud crashes when trying to upload an image from the Downloads app, because localPath ends up being null in obtainNewOCFileToUpload from FileUploader.java.

I added some logging statements while trying to upload a pdf file:
```
Log_OC.d(TAG, "uri scheme is " + uri.getScheme());
String mimeType = getContentResolver().getType(uri);
Log_OC.d(TAG, "mime type is " + mimeType);
```
These printed:
```
uri scheme is content
mime type is application/pdf
```

I added this code to the else statement that catches content that is not an Image, Audio, nor Video:
```
Log_OC.d(TAG, "uri.getPath() is " + uri.getPath());
Log_OC.d(TAG, "uri.toString() is " + uri.toString());
Log_OC.d(TAG, "Uri.decode(uri.toString()) is " + Uri.decode(uri.toString()));

Cursor c = getContentResolver().query(uri, null, null, null, null);
c.moveToFirst();
for(int col=0; col < c.getColumnCount(); col++) {
    String colName = c.getColumnName(col);
    Log_OC.d(TAG,"ColumnName for col " + Integer.toString(col) + " is "  + colName);
    Log_OC.d(TAG,"getString for col " + Integer.toString(col) + " is "  + c.getString(col));
}
```
This was the output:
```
uri.getPath() is /document/7912
uri.toString() is content://com.android.providers.downloads.documents/document/7912
Uri.decode(uri.toString()) is content://com.android.providers.downloads.documents/document/7912

ColumnName for col 0 is document_id
getString for col 0 is 7912
ColumnName for col 1 is mime_type
getString for col 1 is application/pdf
ColumnName for col 2 is _display_name
getString for col 2 is NRG Stadium Houston - NRG Stadium Tickets Available from OnlineCityTickets.com.pdf
ColumnName for col 3 is summary
getString for col 3 is NRG Stadium Houston - NRG Stadium Tickets Available from OnlineCityTickets.com.pdf
ColumnName for col 4 is last_modified
getString for col 4 is 1428751149040
ColumnName for col 5 is flags
getString for col 5 is 6
ColumnName for col 6 is _size
getString for col 6 is 161873
```

**Comment by jksinton** [comment] 2015-04-20 04:08
This works to upload a file from the downloads app by changing the else statement that catches content that is not an Image, Audio, nor Video:
```
String filePath = "";
String id = DocumentsContract.getDocumentId(uri);
Uri contentUri = ContentUris.withAppendedId( Uri.parse("content://downloads/public_downloads"), Long.valueOf(id));

Cursor cursor = null;
String column = "_data";
String[] projection = { column };
cursor = getContentResolver().query(contentUri, projection, null, null, null);
if (cursor != null && cursor.moveToFirst()) {
	final int index = cursor.getColumnIndexOrThrow(column);
	filePath = cursor.getString(index);
}
```
See https://github.com/jksinton/android/commit/1ba1dfe7d02462295be1bbb90ec844e67a45df6b

This uses some of the Storage Access Framework taught by Paul Burke at http://stackoverflow.com/questions/19834842/android-gallery-on-kitkat-returns-different-uri-for-intent-action-get-content

Mr. Burke commented that a more up-to-date version is here:
https://github.com/iPaulPro/aFileChooser/blob/master/aFileChooser/src/com/ipaulpro/afilechooser/utils/FileUtils.java

This works to upload content that is not an image, video, or audio file, e.g. a word doc or a pdf.  We may need to add similar if-else statements that determine if the file is from the downloads app, e.g.:
```
else if (isDownloadsDocument(uri)) {
```
using this:
```
public static boolean isDownloadsDocument(Uri uri) {
    return "com.android.providers.downloads.documents".equals(uri.getAuthority());
}
```

**Comment by davivel** [comment] 2015-04-24 07:30
Thanks for all your work, @jksinton . So. this seems directly related to #296 and #709. Need to check it.

**Comment by enoch85** [comment] 2016-03-17 13:59
Is this still valid?

**Comment by jksinton** [comment] 2016-03-17 14:12
Looks like the if else branch for an image, video, audio is incorporated in Uploader.java. I just tested an image and pdf file. They uploaded. We can probably close this issue.

**Comment by enoch85** [comment] 2016-03-17 14:20
cc @davivel Please close. @all Feel free to reopen if this issue still presists.

**Comment by davivel** [comment] 2016-03-21 10:33
Unfortunately, this is strongly related to #1515, and there is something wrong there. 

@jksinton , what version of the app did you use for your last test? Could you try again with a *.zip or *.apk file instead of PDF?

**Comment by jksinton** [comment] 2016-03-23 01:37
I'm using v. 1.9.1 with server 8.2.2 stable. I was able to upload zip and apk files from the downloads app.

**Comment by tobiasKaminsky** [comment] 2016-05-06 11:55
@jksinton is this still a problem?

**Comment by hodyroff** [comment] 2016-12-09 07:54
No reaction, closing. Please comment/reopen when you have information including newest version feedback. Thanks!

**Closed by hodyroff** 2016-12-09 07:54 UTC
Labels: bug, Needs info, sync::upload
