### ISSUE TITLE
[feature request] Preference to set if notifications should be shown

### ISSUE THREAD

**Issue by agilob** [owncloud/android#1179] opened 2015-09-29 18:52 UTC
New preference checkbox which indicates if 'instant upload' should publish notifications.

**Comment by tobiasKaminsky** [comment] 2015-09-29 19:06
Do you want to completely disable all notifications? 
As far as I know it is planned to remove the success notification as this is the expected behaviour and only show failing messages.
But I think an upload progress bar should always be shown as the user should know what the app is doing.

**Comment by agilob** [comment] 2015-09-29 19:18
I was thinking about a situation when a device was lost or stolen and a thief takes pictures/videos. It should be possible to silently upload them without any notification.

**Comment by AndyScherzinger** [comment] 2015-10-07 10:37
This would mean one would basically need a remote switch, meaning you would have to configure this on the server side, for a certain client. I don't have any idea how this could be implemented concept-wise.

**Comment by agilob** [comment] 2015-10-07 11:30
Very easy:
1. Add Boolean shared preference SilentMode
2.
```
if(silentMode == false) {
showUploadStatusNotification); // upload in progress / successful/failed
}
```

**Comment by AndyScherzinger** [comment] 2015-10-07 11:33
Still doesn't compute for me. This works if you set it _before_ your phone gets stolen.

**Comment by agilob** [comment] 2015-10-07 11:38
>This works if you set it before your phone gets stolen

Yea, that's what I would do. Personally, two notification **per upload** annoy me. One is shown for uploading, second after upload succeeded/failed. Not having any notification would work better for me, and that's what this FR is about.

**Comment by AndyScherzinger** [comment] 2015-10-07 11:53
Got it, that would be something that imho is technically possible to implement :) Fancy doing a PR?

**Comment by agilob** [comment] 2015-10-07 11:54
Possibly. When's the next release?

**Comment by AndyScherzinger** [comment] 2015-10-07 16:22
The next release is 1.8.1 - the release date is somewhere around end of year an excact date might be something @rperezb could tell us :)

**Comment by tobiasKaminsky** [comment] 2015-10-07 16:42
After merging #762 there will only be a notification if an upload fails.
Disabling this function makes no sense to me.
I agree that the current situation produces too much notifications.

**Comment by AndyScherzinger** [comment] 2015-10-07 17:04
would #762 solve your issue with the notifications @agilob ?

**Comment by agilob** [comment] 2015-10-07 20:47
>After merging #762 there will only be a notification if an upload fails.

Still doesn't solve the problem for me (and probably others with unreliable connection), when internet goes down or I'm behind filtered connection I get notification about failed upload every several minutes. I would prefer to disable notification completely.

**Comment by AndyScherzinger** [comment] 2015-10-07 20:58
#1166  will be test driven soon and would fix the connection lost and still trying to upload scenario.

**Comment by davivel** [comment] 2017-03-10 12:11
Sorry for my late response.

Disabling notifications of any app can be done from Android 5.0, without extra options inside the apps. The path is: device 'Settings' / 'Applications' or 'Apps' / 'ownCloud' / 'Notifications'. There you can enable 'Block all'.

@agilob , if this is not enough for your use case, please comment or reopen.

**Comment by agilob** [comment] 2017-03-10 12:34
>@agilob , if this is not enough for your use case, please comment or reopen.

I have android 4.0 and 4.1

**Comment by davivel** [comment] 2017-03-13 11:42
In that case, I'll reopen.

We can't put this in high priority, but shouldn't be too hard for contributors willing to join. Maybe we are lucky if label it as junior job.

**Comment by vikene** [comment] 2017-04-15 09:09
@agilob so, you don't even want upload failed notification ?

**Comment by agilob** [comment] 2017-04-15 20:25
Correct.

**Comment by AigerimBazarbayeva** [comment] 2017-04-18 17:58
Hello, I will tackle this issue.

**Comment by davigonz** [comment] 2017-04-18 21:16
Thanks a lot for your contribution @AigerimBazarbayeva , I've just added a comment in your PR

**Comment by vshivam** [comment] 2017-06-05 07:33
Hi! Is this issue still open ?

**Comment by harshitbansal05** [comment] 2018-02-07 06:01
hi, @davigonz i would like to work on this issue, is it still open?

**Comment by davigonz** [comment] 2018-02-07 11:03
Hi @agilob, are you still interested in this feature? Have you updated your Android version to a newer one so that you can disable the notifications from the device settings? If so, I will close this issue since is a feature already included in Android system from several years ago.

**Comment by agilob** [comment] 2018-02-07 12:12
>Have you updated your Android version to a newer one so that you can disable the notifications from the device settings?

yes

>Hi @agilob, are you still interested in this feature?

yes  :)

You can close it if you think it's not a feature for the app

**Comment by davigonz** [comment] 2018-02-08 09:08
@agilob We have included a new feature in the new ownCloud Android app 2.6.0 to configure separately the notifications for downloads or uploads in Android 8. 

<img src="https://user-images.githubusercontent.com/15261363/35964339-bd8fc972-0cb7-11e8-83b2-5afae396675e.png" width="50%">

**Comment by jesmrec** [comment] 2018-02-15 12:51
Android fixed the problem itself :)

Closing, if any consideration regarding notifications is noticeable, please reopen

thanks for reporting @agilob

**Closed by jesmrec** 2018-02-15 12:51 UTC
Labels: Junior Job, notifications, settings
