### ISSUE TITLE
Beta 20160120: crash - uploading picture to owncloud using "Easy Share Action"

### ISSUE THREAD

**Issue by smico** [owncloud/android#1472] opened 2016-02-11 19:24 UTC
### Expected behaviour
Picture should be uploaded to ownCloud

### Actual behaviour
ownCloud app crashes

### Steps to reproduce
1. open Gallery
2. share picture by using "Easy Share Action" button
3. ownCloud App crashes

### Environment data
Android version: 6.0.1
Device model: Nexus 4
Stock or customized system: Cyanogenmod 13
ownCloud app version: 20160120
ownCloud server version: ownCloud 8.2.2

#### Web server error log
No Web Server error log, because app crashes before connecting to server

#### ownCloud log (data/owncloud.log)
No ownCloud log, because app crashes before connecting to server

### Android Log
************ CAUSE OF ERROR ************
java.lang.RuntimeException: Unable to start service com.owncloud.android.files.services.FileUploader@2fccfd1 with Intent { cmp=com.owncloud.android.beta/com.owncloud.android.files.services.FileUploader (has extras) }: java.lang.IllegalArgumentException: Trying to create a OCFile with a non valid remote path:
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3071)
at android.app.ActivityThread.-wrap17(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5466)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalArgumentException: Trying to create a OCFile with a non valid remote path:
at com.owncloud.android.datamodel.OCFile.(OCFile.java:103)
at com.owncloud.android.files.services.FileUploader.obtainNewOCFileToUpload(FileUploader.java:771)
at com.owncloud.android.files.services.FileUploader.onStartCommand(FileUploader.java:286)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3054)
... 8 more

************ DEVICE INFORMATION ***********
Brand: google
Device: mako
Model: Nexus 4
Id: MMB29U
Product: occam

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 35b26cafd4

**Comment by strugee** [comment] 2016-02-15 12:12
Duplicate of #1465

**Comment by tobiasKaminsky** [comment] 2016-02-15 20:13
Right.
@smico can you test the latest beta and then comment in the linked issue?

**Closed by tobiasKaminsky** 2016-02-15 20:13 UTC
