### ISSUE TITLE
Purpose of stable branch ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2802] opened 2020-01-31 21:28 UTC
I'm just wondering about this stable branch. What's the purpose of it ?
<img width="943" alt="image" src="https://user-images.githubusercontent.com/3314607/73575613-df386200-4478-11ea-88cf-530dc8a07730.png">

**Comment by davigonz** [comment] 2020-02-04 09:10
Our `master` branch is not a stable one, it would be like a `develop` branch in the [Gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) (flow we follow from long time ago). And our `stable` branch would be the `master` branch in that flow.

The purpose of our `stable` branch (or `master` in Gitflow workflow) is to contain the versions we release (official release history) and now is easier to see how it differs from our `master`. `stable` branch contains 2.14.2 and 2.14.1 releases and master contains other features that were merged while we were releasing those versions. 

In other words, our release process is usually:
1. Freeze version code in `master` branch
2. Create `release` branch from HEAD commit of master (or from an already signed tag - hotfix)
3. Update `versionName` , `versionCode` and bug fixing if something was found during regression tests.
4. Once the release code is fine for the reviewer and approved by QA, we tag and sign the version in `release` branch. Why there? Because if we do this in master (as we were doing time ago), we can not keep working on master.
5. Rebase  `release` branch with `master` (solve conflicts if any)
6. Merge `release` branch into `master`
7. Create branch from tagged commit of the version and merge into `stable`

That is our way to do it till now, but I would move to something like, that is not much different:

![Screenshot 2020-02-04 at 09 55 17](https://user-images.githubusercontent.com/15261363/73728936-7e3cb280-4734-11ea-96a9-98307e73dad3.png)

1. Freeze version code in `develop` (our `master`)
2. Create `release` branch from HEAD commit of `develop` (our `master`)
3. Update `versionName` , `versionCode` and bug fixing if something was found during regression tests.
4. Once the release code is fine for the reviewer and approved by QA, we merge the `release branch` into `master` (our `stable`) and tag and sign the version there, so we can keep working on other stuff in `develop` (our `master`)
5. Rebase `release` branch with `develop` (our `master`) 
6. Merge `release` branch into `develop` (our `master`) 

We feel comfortable with this flow but other points of view are always welcome

CC / @jesmrec @abelgardep

**Comment by jesmrec** [comment] 2020-02-04 10:49
> Because if we do this in master (as we were doing time ago), we can not keep working on master.

This is the main reason we took the approach. We schedule a release with a set of features, and we do not want to freeze the work for the next release while QA/release is passing.

**Closed** 2020-02-04 10:59 UTC
