### ISSUE TITLE
File uploads larger than 1MB fail

### ISSUE THREAD

**Issue by sonic331va** [owncloud/android#402] opened 2014-02-16 10:33 UTC
Android Version: 4.4
App Version: 1.5.3
Server Version: 6.0.1 (stable)

All files larger than 1MB fail to upload. Files smaller than 1MB upload successfully.

Apache log - server is returning "400 Bad Request":
"HEAD /remote.php/webdav/Test/ HTTP/1.1" 200 300 "-" "Android-ownCloud"
"HEAD /remote.php/webdav/Test/File1.docx HTTP/1.1" 404 313 "-" "Android-ownCloud"
"PUT /remote.php/webdav/Test/File1.docx-chunking-9385-4-0 HTTP/1.1" 400 629 "-" "Android-ownCloud"

Packet information:
HTTP/1.1 400 Bad request
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre_DAV_Exception_BadRequest</s:exception>
  <s:message>expected filesize 1024000 got 0</s:message>
  <s:sabredav-version>1.7.6</s:sabredav-version>
</d:error>

Chunked file handling is included on the server in filesplugin.php.

I'm breaking this out of the comments of #306 since my issue appears to be different.

**Comment by bislewl** [comment] 2015-02-10 16:00
I'm having the issue with a vanilla version of 7.0.4 uploads > 1MB are failing.

**Comment by davivel** [comment] 2015-02-11 10:26
@markcs , sorry for coming back so late. Could you reproduce it again and copy also the logs in the server side? Specially owncloud.log, in your case. There is an internal error in the last chunk upload.

@bislewl , could you upload some logs from your server too? 

Thanks.

**Comment by koug44** [comment] 2015-06-12 15:21
Got news (almost good one). Still with the same server OC (now on 8.0.4)
Both official clients are failing to upload files (desktop and android)
Upload via web interface is still ok (using Firefox)

But now, I can also upload my pictures from my Android phone using QuickPic app and Owncloud integration. It's working fine for the same files than official client can't upload.
Could it be useful ? I'm guessing they are not using the same HTTP method or syntax

**Comment by childnode** [comment] 2015-07-18 15:08
can reproduce this on my owncloud 8.1.0-2 and 8.1.0-3 from [debian 7.0 repo](http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/) installation with xmarks bookmark sync using webdav. Since I exceeded the 1MiB limit, the error occurs:
```
==> /var/log/apache2/cloud.log <==
77.1.3.223 -> owncloud.childno.de:443(cloud.childno.de) - marcel [18/Jul/2015:16:24:44 +0200] "PUT /remote.php/webdav/xmarks/bookmarks.txt HTTP/1.1" 400 225 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0 Xmarks-Fx/4.3.7.1-signed"

==> /srv/owncloud/data/owncloud.log <==
{"reqId":"UgNIjJEd9ga\/S9xmr2uF","remoteAddr":"77.1.3.223","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 1086517 got 0\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(113): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #259)\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('bookmarks.txt', Resource id #259)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('xmarks\\\/bookmark...', Resource id #259, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":144}","level":4,"time":"2015-07-18T14:24:55+00:00"}
```
deleting bookmarks will make sync work ;/

Running apache2.2.22 with 5.4.41 at debian 7 (wheezy)

at https://github.com/owncloud/core/issues/9832 respectively https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html#apache pointed out some hints that helped for some, but not for me ;/

**Comment by koug44** [comment] 2015-09-01 20:56
The bug is fixed for me, both with Android and new 2.0 client.

I've fixed the PHP cache a few days ago. It may be related

**Comment by childnode** [comment] 2015-09-02 05:52
unfortunatly it isn't for me, not even on android, other related issues: https://github.com/owncloud/core/issues/17712 so it not just seems to be an android / client bug hence it worked fine prior OC 8. as it is pointed out there: it is caused by buggy PHP 5.4, you need to upgrade

**Comment by childnode** [comment] 2016-02-15 22:47
*yay* back ... OC 8.2.2, php 5.6.17 and .18 with any webDav client ;( that's sooo frustrating

**Comment by davivel** [comment] 2016-02-24 21:15
@all, please, could you confirm if this is a problem for you with OC 1.9.1 for Android?

Thanks in advance.

**Comment by childnode** [comment] 2016-02-25 22:48
so, can confirm this doesn't work for me with 1.9.1 (upload a 2,5 MB PDF) but I also can't check back for older version since I have removed it due to the annoying power sucking bug.

But I ran into 2 other bugs ;) and once again: I think it's more a core than an android bug.

**Comment by sprin** [comment] 2016-03-31 16:43
I encountered this problem when attempting to upload any file >  1 MB from my phone via GSM. It happens consistently on GSM, but not on a WiFi connection. I found a way to consistently replicate it regardless of network/hardware.

Server (created for replicating the bug, using a very simple recommended config):
CentOS Linux release 7.2.1511 (Core) 
PHP 5.5.21-4.el7
Owncloud 9.0.0-3.1
MariaDB 1:5.5.44-2.el7.centos
Apache 2.4.6-40.el7.centos

Clients:
App Version 1.9.1
Phone: Android 5.0.2
Desktop Android Runtime: ARChon 1.2

I was able to reproduce from my desktop by simulating the latency, packet loss, and reordering of a non-ideal GSM network with the `netem` kernel module:
```
sudo tc qdisc add dev wlp2s0b1 root netem delay 3000ms loss 25% reorder 50% 50%
```

I used a test file created by `dd`:
```
dd if=/dev/zero of=testfile bs=1100k count=1
```

The exception logged on the server always follows the format:
```
{"reqId":"","remoteAddr":"","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 1024000 got 0\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #313)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/directory.php(134): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #313)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('testfile-chunki...', Resource id #313)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('testfile-chunki...', Resource id #313, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":404,\"User\":\"admin\"}","level":4,"time":"2016-03-31T16:25:41+00:00"}
```

This appears to be the related request logged by Apache:
```
181.132.149.100 - admin [31/Mar/2016:16:25:06 +0000] "PUT /remote.php/webdav/testfile-chunking-4629-2-0 HTTP/1.1" 400 225 "-" "Mozilla/5.0 (Android) ownCloud-android/1.9.1"
```

Additional notes: I have not seen this problem with either the web client or the Linux desktop sync client under the same network conditions. I have only seen the problem under non-ideal network conditions with the Android app. The client reports an error immediately after reaching 1MB while uploading.

**Comment by e-alfred** [comment] 2016-04-25 10:35
The Owncloud Antivirus app causes these problems:

https://github.com/owncloud/files_antivirus/issues/110

**Comment by MorrisJobke** [comment] 2016-05-18 16:41
Most likely fixed with https://github.com/owncloud/core/issues/24653 in all the upcoming server maintenance releases.

**Comment by davivel** [comment] 2016-05-30 12:38
@MorrisJobke , that would be really awesome. Thanks a lot.

**Comment by davivel** [comment] 2016-08-03 08:52
@childnode, @sprin, @e-alfred : is this still a problem for you? Did you upgrade your servers to one of the latest maintenance versions (9.1.0, 9.0.4, 8.2.7, 8.1.9 or 8.0.14) ?

Thanks!

**Comment by childnode** [comment] 2016-08-03 15:41
hi @davivel , yes, I updated to 9.1 in the meantime but was anyway not able to reproduce this in any release since https://github.com/owncloud/android/issues/402#issuecomment-189018141  nor with owncloud client 2.0 ...anyway. I switched to nextCloud and I can confirm nextCloud client 1.2.0 (no idea which owncloud client it is forked of) works in my setup. ... if there is any problem: I can't reproduce it anymore nor can I help to track down which versions / combinations of app and server won't work and which will...

**Comment by davivel** [comment] 2016-08-04 11:00
Thank you so much for your answer, @childnode :)

Will wait a bit more for answers of @sprin  and @e-alfred before closing.

**Comment by davivel** [comment] 2016-08-12 08:24
@sprint, @e-alfred. I'll assume this is not a problem for you anymore.

Add a comment if I'm wrong.

Thanks!

**Closed by davivel** 2016-08-12 08:24 UTC
Labels: bug, Server Involved, sync::upload

**Comment by typorian** [comment] 2016-08-31 07:42
I'm on the second latest stable version of OwnCloud (Serverside) and I'm using the client from F-Droid on Android, and the problem still occurs for me. It was gone with 9.0.2 but it returned with 9.0.4.

**Comment by davivel** [comment] 2016-08-31 14:47
@typorian , could you open a new issue and give us some more details about your environment? Take a look to the issue template.

Thanks!

**Comment by e-alfred** [comment] 2016-09-02 07:43
It works well now with Owncloud 9.1.0, Android client 2.1.1 and Antivirus app 0.9.0.0.

**Comment by typorian** [comment] 2016-09-02 09:10
@e-alfred I'll have my provider upgrade owncloud for me and hope that I get the new client version soon on F-Droid. If that makes it work again, I'd be happy.

**Comment by e-alfred** [comment] 2016-09-29 18:45
It still happens with the antivirus app activated. After disabling it, the uploads work well on 9.1.1.
