### ISSUE TITLE
Enhancement: Use Android 4.4 Document Provider API

### ISSUE THREAD

**Issue by pulser** [owncloud/android#296] opened 2013-11-02 20:58 UTC
The document provider API in Android 4.4 (Kitkat) offers a framework for storage providers, such as OwnCloud, Google Docs, Box etc. 

http://developer.android.com/about/versions/kitkat.html#44-storage-access

This looks like a useful way to permit users to access their OwnCloud files quickly, and make use of OwnCloud as their default storage location, throughout the OS, and permits the provider to be written once, but used by any client application that uses this API.

Implementation documentation is available at http://developer.android.com/reference/android/provider/DocumentsProvider.html

**Comment by strugee** [comment] 2015-03-09 00:13
@davivel did you ever look into this? I share @alerque's concerns.

**Comment by davivel** [comment] 2015-04-30 07:21
@strugee , sure we looked into it. Unfortunately, looking does not produce any result similar to writing code.

This will be done when we can book the time for it. There are several reasons why it's very interesting to have it, but we are a small team an have to address many top priorities.

Code contributions in this and related issues are very welcome.

**Comment by strugee** [comment] 2015-05-04 06:37
@davivel should have been clearer. By 'it', I meant this issue's priority, not the issue itself. Sorry for the confusion (and thanks, as always, for your hard work).

**Comment by haseebeqx** [comment] 2015-10-04 09:58
ok i am working on it.  but when i used the existing content provider it shows permission denied since the `android:exported` is false and `android:grantUriPermissions` is not set. what should i do now. set `android:exported` to true or `granturipermission` or any other options ?.

 currently i managed to implement this feature with exported content provider and it is working fine

**Comment by dschuermann** [comment] 2015-10-04 14:41
Maybe it helps that there is a fully working example for Document Providers here: https://android.googlesource.com/platform/development/+/master/samples/Vault/

**Comment by haseebeqx** [comment] 2015-10-04 15:16
i already have a working model .

but the problem is in kitkat the document provider works from another app called documents inside system. so there are issues with current content provider and localbroadcasts. i can not use the current  file access provider to look at data since it is not exported and android:grantUriPermissions not set.

**Comment by karliwalti** [comment] 2015-11-17 09:48
May I additionally support the integration of this. Microsoft office is now supporting "Other cloud storage" and all major service providers are supported (tested with Drive, Box, Dropbox, and OneDrive ). To work on the go from the cloud it would be essential

**Comment by AndyScherzinger** [comment] 2015-11-17 10:45
Setting exported and android:grantUriPermissions to be able to implement this seems fine to me, what do you think @davitol @masensio @tobiasKaminsky ?

**Comment by davitol** [comment] 2015-11-17 14:48
@davivel :santa:

**Comment by codinguser** [comment] 2015-11-26 07:29
According to http://developer.android.com/about/dashboards/index.html 
devices with Android KitKat (4.4) and above now represent over 63% of the total Android install base. 
Will this warrant a revisiting of the priority of this issue?

**Comment by tobiasKaminsky** [comment] 2015-11-26 17:11
@haseebeqx I think it is not a problem to change these settings.
It would be great if you can provide a pull request which we can merge into our beta app and see how it is working.

**Comment by przybylski** [comment] 2015-12-19 12:30
Since there is no response from previous developer for over a month, I wrote it last night.

**Comment by alerque** [comment] 2016-01-02 10:37
Thanks @przybylski for working on this. I'm looking forward to having it merged and being able to approve the bounty. For reference since it's not cross linked yet, it looks like PR #1368 is related to this.

**Comment by przybylski** [comment] 2016-01-02 11:30
@alerque I encourage you to test it on latests beta version

**Comment by alerque** [comment] 2016-01-02 14:11
Is there a beta channel on the Play store to facilitate the testing process? Or at least pre-built apk's somewhere?

**Comment by przybylski** [comment] 2016-01-02 14:33
Beta is available on f-droid and pre-built apks are available here https://github.com/owncloud/android/tree/beta/apks

**Comment by AndyScherzinger** [comment] 2016-01-08 01:38
@alerque Could you give it a try?

**Comment by alerque** [comment] 2016-01-08 09:20
@AndyScherzinger I've been using the beta since I was pointed to it 6 days ago and it hasn't given me any trouble. On the other hand I've only had a chance to give it pretty light use this week.

**Comment by tobiasKaminsky** [comment] 2016-01-09 07:19
@alerque I think @AndyScherzinger is specifically talking about the document provider?
Is this working for you as expected?

**Comment by AndyScherzinger** [comment] 2016-01-09 10:51
Thanks for the clarification @tobiasKaminsky that is what I was asking about :)

**Comment by ilmaisin** [comment] 2016-01-26 20:48
The beta client seems to support opening via SAF, but not saving.

**Comment by przybylski** [comment] 2016-07-02 21:39
document provider merged, closing

**Closed by przybylski** 2016-07-02 21:39 UTC
Labels: document_provider, enhancement
