### ISSUE TITLE
Upload files: Select all files option

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/android#1015] opened 2015-06-15 12:32 UTC
When uploading files it's tedious to have to select every single file - especially if you have 2-300 files.
It would help if there was a "select all" files option.

PR: #1342

**Comment by LukeOwncloud** [comment] 2015-06-15 13:35
Duplicate of https://github.com/owncloud/android/issues/1005?

**Comment by pascalBokBok** [comment] 2015-06-15 14:11
I had been messy and asked for two things in one issue. Now it is not about uploading directories since it is covered in #1005, but only about being able to select all files in a folder.
That is nice e.g. when wanting to upload your photos from DCIM into a folder in owncloud.

**Comment by masensio** [comment] 2015-06-18 07:41
Hi @pascalBokBok,

Thanks for your ideas. 
I think this is an option into the multiselection of files. https://github.com/owncloud/android/issues/899
Maybe, we'll implement as a part of this feature.

I don't know when we will introduce this feature in the project, but I hope this option will be in our app in a near feature.

**Comment by tobiasKaminsky** [comment] 2016-05-07 07:06
#1342 is the PR for this.

**Comment by tobiasKaminsky** [comment] 2016-05-07 07:08
@LukeOwncloud this is no duplicate as the linked issue (which leads to #645) is about uploading one folder recursively and this one is about only selecting all files from one folder.

**Comment by davigonz** [comment] 2018-12-17 09:59
> I will start work on this.

Great! Thanks

**Comment by sd1998** [comment] 2018-12-17 10:45
@davigonz I the select inverse option also required?

**Comment by davigonz** [comment] 2018-12-17 11:38
> Is the select inverse option also required?

It would be great to have it, yes, similar to we already have in the file list.

**Comment by jesmrec** [comment] 2019-02-12 12:37
Done. Will be available in 2.10

**Closed by jesmrec** 2019-02-12 12:37 UTC
Labels: browse, enhancement, sync::upload
