### ISSUE TITLE
using Feedback option results in receiving a NDR

### ISSUE THREAD

**Issue by woohooyeah** [owncloud/android#1482] opened 2016-02-19 20:06 UTC
### Expected behaviour
The feedback option creates a new e-mail message to incoming2@owncloud.com. We expect this address to exist, delivering our e-mail message containing the feedback content.

### Actual behaviour
The mailbox does not exist, according to ownCloud's mail server, kerio.owncloud.com. It results in a NDR being sent back.

### Steps to reproduce
1. Open the Settings
2. Tap 'Feedback' in the bottom of the Settings screen
3. Produce e-mail message and tap the send button
4. Receive e-mail message, it's a NDR, containing: <incoming2@owncloud.com> (kerio.owncloud.com: Mailbox does not exist)

### Environment data
Android version: 5.1.1

Device model: Sony Xperia Z5 Compact (E5823)

Stock or customized system: Stock

ownCloud app version: 1.9.1

ownCloud server version: 8.2.2

**Comment by AndyScherzinger** [comment] 2016-02-22 08:46
@woohooyeah I can't reproduce this. I hit the Feedback button in the settings and the mail gets sent to apps@owncloud.com which works fine.

**Comment by rperezb** [comment] 2016-02-22 12:47
hehehe @AndyScherzinger confirmed! i have just read the mail

**Comment by rperezb** [comment] 2016-02-22 12:48
@woohooyeah the ownCloud app sends feedback to apps@owncloud.com mail account.
How did you manage to fill in the mail as: incoming2@owncloud.com ?

**Comment by woohooyeah** [comment] 2016-02-22 15:22
When testing it now, it fills in apps@owncloud.com, indeed.
When I tested it 3 days ago, it filled in incoming2@owncloud.com. Quite strange indeed.

**Comment by AndyScherzinger** [comment] 2016-02-22 16:02
I checked the history and https://github.com/owncloud/android/commit/e86d7cd9b4867e30c458bf027ae135251968b122 was the last change which configured apps@... as the mail address (in 2013). 

@woohooyeah Since it is working now I am closing the issue (for now). Please reopen it in case the situation comes up again.

**Comment by AndyScherzinger** [comment] 2016-02-22 16:41
Sorry,
I need to reopen...didn't see it due to my spam filter, but I also get this reply...

This is an informative message sent by kerio.owncloud.com.

The server was not able to deliver your email message

Subject: Feedback - android v1.9.1
Date: Mon, 22 Feb 2016 09:42:38 +0100

to the following addresses:

<incoming2@owncloud.com> (kerio.owncloud.com: Mailbox does not exist)

Maybe there is some kind of mail server config where you have an error with aliases and actual mailboxes @rperezb ? So yes the mail goes to apps@.... but internally within the mail server it seems it is also shipped to incoming2

**Comment by AndyScherzinger** [comment] 2016-02-22 16:51
--> It is not an application error, it is rather an email server missconfiguration as it seems to me.

**Comment by LukasReschke** [comment] 2016-02-22 16:52
@danimo ^

**Comment by danimo** [comment] 2016-02-22 16:53
It's already fixed. Sorry for the inconvenience.

**Closed by danimo** 2016-02-22 16:53 UTC
Labels: Needs info
