### ISSUE TITLE
[QA] misleading sharing icon

### ISSUE THREAD

**Issue by jnweiger** [owncloud/android#3733] opened 2022-08-22 09:12 UTC
Seen in ownCloudReleaseVersion2.21.1

There is are sharing icons at the right hand side of the file listing. Looks very much like the sharing icon in classic web UI.
* click the icon. the file opens locally. BAD

![image](https://user-images.githubusercontent.com/1108546/185884969-3a8752f5-d9c2-4f30-b0ab-41647df103f6.png)

Expected behaviour
* A sharing dialog opens.
* Clearly distinguish status indicator from action button.

Background
* this icon does not allow sharing, it only indicates, that the file is shared.

**Comment by michaelstingl** [comment] 2022-08-22 09:17
@tbsbdr FYI

**Comment by jesmrec** [comment] 2022-08-22 10:03
It was intended only to show that the file is shared. Room for improvement, for sure. In any case, row structure will be re-done (three-dot-button for every row and other improvements, check https://github.com/owncloud/android/issues/2742)

**Comment by xxdc** [comment] 2022-08-29 08:50
https://t.me/+aLC23_hQ895mZDRl

**Comment by jesmrec** [comment] 2023-09-26 08:16
Fixed in 4.1 with the new sharing icon placed on different place

**Closed by jesmrec** 2023-09-26 08:16 UTC
Labels: Design, File list
