### ISSUE TITLE
Date/time issue

### ISSUE THREAD

**Issue by Dreadeath** [owncloud/android#1192] opened 2015-10-09 13:30 UTC
How can I change date and time view in app below folder names? I have only time right now, which is not very useful
![screen](https://cloud.githubusercontent.com/assets/8825774/10394911/a950e29e-6e89-11e5-88bc-da5d019a5542.png)

Version 1.8.0 from f-droid.

**Comment by AndyScherzinger** [comment] 2015-10-09 14:40
At the moment there is no option to change this format. The app shows time being since the latest change which shows hours for the first day and after that shows the date (day/month). So this information will change in your app tomorrow :)

**Comment by Dreadeath** [comment] 2015-10-09 15:13
Some folders updated months ago :-\

**Comment by AndyScherzinger** [comment] 2015-10-09 16:23
hmm, that is strange.

Can you provide some kind of test account for your server to be able to debug this issue? 
What Server version are you using?

**Comment by Dreadeath** [comment] 2015-10-09 16:49
I did some tests, and when I change my smartphone's language to English, dates are displayed as it supposed to. So it is something localization-related I guess.

**Comment by LukeOwncloud** [comment] 2015-10-10 17:55
Confirmed. This is not a server issue. It's all about the system language. Try Russian, for example:
3 hours ago and 2 days ago seem to be correct. However, for older files just a timestamp as shown above is shown (I do not see any relation between that time and the actual change date.)

**Comment by tobiasKaminsky** [comment] 2015-10-11 05:14
FileListListAdapter: 522
private CharSequence showRelativeTimestamp(OCFile file){
        return DisplayUtils.getRelativeDateTimeString(mContext, file.getModificationTimestamp(),
                DateUtils.SECOND_IN_MILLIS, DateUtils.WEEK_IN_MILLIS, 0);
    }

I do not see any language specific or custom implementation from us...
So for now I assume this is a bug by android?

**Comment by AndyScherzinger** [comment] 2015-10-11 07:45
The further methods use the locale and plurals. Might be worth debugging. Not sure it is a Android bug. 
Quite sure there is a work around :) I'll see if I find the time to look into this.

**Comment by AndyScherzinger** [comment] 2015-10-14 08:55
@tobiasKaminsky @davivel @jancborchardt I found the "problem"...
https://github.com/owncloud/android/blob/master/src/com/owncloud/android/utils/DisplayUtils.java#L211
--> return dateString.toString().split(",")[0];

The ownCloud app's code is return the first part of the comma separated dateString. This works fine for English/German/etc. dates but not for e.g. Russian simply due to the fact that the Russian date format is <time>, <date> ... :(

Any creative ideas how to fix this, except for not splitting it at all? Unfortunately the value calculation is done using Google's Android APIs and we cannot influence the locale they are detecting/using. Alternatively we would have to write this function from scratch in order to properly calculate the value ourselfs.

**Comment by LukeOwncloud** [comment] 2015-10-14 09:21
According to http://developer.android.com/reference/android/text/format/DateUtils.html#getRelativeDateTimeString%28android.content.Context,%20long,%20long,%20long,%20int%29 `getRelativeDateTimeString` returns a string `formatted like "[relative time/date], [time]"`.

Quickly looking around for different time formats, did not give me any national formats which contain a , within the time part. So looking for the last , and using everything in front should work.

**Comment by AndyScherzinger** [comment] 2015-10-15 07:41
It's a matter of local dependent formatting. The [time] returns a time String and a time String also includes the date, while a date not necessarily includes hours,minutes and so on.

So the android function returns 
* for English locale : "Jul 15, 4:09 PM"
* for Russian locale: "15 июля, 16:09"  (Android 23)
* for Russian locale: "16:09, 15 июля" (Android 22)

So it is a locale/Andsroid-Version topic which even differs between Android versions :(

Any comment on how to deal with this? @LukeOwncloud @tobiasKaminsky @davivel @masensio 

I don't see any change to fix this but to implement this methods ourselfs basically copying the method and adapting it in the way that it get a fixed format String which prints out a Date without HH:mm directly. :(

**Comment by LukeOwncloud** [comment] 2015-10-15 08:06
@AndyScherzinger I read the documentation differently: I understand [relative time/date] as: relative time (3 seconds ago), a relative date (5 days ago), or an absolute date (4/4/2000). Time is always hours:minutes. That is also what the examples are indicating and this is how it was changed with Android 23 (Russian). Consequently, I'd argue that the Android code did not follow its specification -> Android bug.

What I am trying to say, there is always two parts namely  [relative time/date] and [time], separated by a comma. We always want [relative time/date]. I also claim [time] always contains a colon. So my suggestion:

replace ``return`` line with:

	String[] parts = dateString.toString().split(",");
	if(parts.length() == 2) {
		if(parts[0].contains(":") && !parts[1].contains(":")) {
			return parts[1];
		} else if(parts[1].contains(":") && !parts[0].contains(":")) {
			return parts[0];
		}
	}
	//dateString contains unexpected format. use local absolute date.
	return DisplayUtils.unixTimeToHumanReadable(time);

**Comment by AndyScherzinger** [comment] 2015-10-15 09:16
Ah, Sorry for my confusion, now I got what you mean :) 
You proposed solution is looking good to me, covering the issue quite nicely :)

Would you like to open a branch/PR?
If not I can cover it, no problem.

**Comment by LukeOwncloud** [comment] 2015-10-15 10:01
@AndyScherzinger please go for it! My development environment is not set up currently, as I am quite busy with other projects. I just like to come back occasionally to help a little and to see what I am missing...

**Comment by AndyScherzinger** [comment] 2015-10-15 12:10
PR has been opened (#1200).

**Comment by masensio** [comment] 2015-10-30 09:41
#1200  is in the master branch.
This issue will be release in the next version of the app, so I'll close it. 

Thanks @AndyScherzinger  for solving it.

**Closed by masensio** 2015-10-30 09:41 UTC
Labels: bug, contributions are welcome, enhancement

**Comment by iav** [comment] 2015-10-31 18:25
Please, stop playing with short and reltive formats. Or, at least, please, make a way to set format manualy.
I just want to see year.month.day hour.minute.second.
Always.
Everywhere.

**Comment by AndyScherzinger** [comment] 2015-11-09 18:10
@iav as for that, please open a new issue and have a discussion with @jancborchardt about that.

**Comment by jancborchardt** [comment] 2015-11-10 09:02
@iav well, you’re not the only person using ownCloud. For most people e.g. seconds are completely irrelevant.
