### ISSUE TITLE
Beta: storage path setting too complicated / doesn’t need to be a file picker

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1310] opened 2015-11-26 05:39 UTC
What exactly is the use-case of there being a full-blown file picker for this? We really just need a choice between saving on the local storage or on an external storage like SD card.

We should do that similarly to how [Maps.me](https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro) solves it. Simple choice between the storage mediums. No need to choose the exact path.

cc @AndyScherzinger @tobiasKaminsky @davivel 
(Awesome on tackling this though! Looking forward to be able to use my SD card so I have more space!)

**Comment by tobiasKaminsky** [comment] 2015-11-26 07:45
This belongs to #1293 by @przybylski 
I think the reason for using a file picker is the flexibility for the user to use any desired path and not a predefined one.
Maybe it is an option to choose between "internal" ,"external" , "custom" (which then will open the file picker).

**Comment by przybylski** [comment] 2015-11-26 09:34
I didn't want to force predefined path to the user, and allow them to put owncloud storage in any place they want. Mount points might differ on different phones (especially samsung). User must know whats he's doing.

**Comment by tobiasKaminsky** [comment] 2015-11-26 17:31
A good compromise would be my proposed idea with internal/external/custom?

**Comment by jancborchardt** [comment] 2015-11-27 08:17
Yeah, but honestly the focus here should be on making it super simple. Most other apps don't really ask you for a path but simply if internal or SD card.

A complicated path picker will result in most users _not_ really knowing what they do. It's not about perceived freedom of choice here – cause that doesn't even make sense. It's another option which is not really needed given the use case.

**Comment by tobiasKaminsky** [comment] 2015-11-27 15:31
Ok. This is also fine for me.
So let's try it with internal/external. And if there are several users that want to have custom storage path we can intregrate it?
Are you fine with this @przybyiski?

**Comment by przybylski** [comment] 2015-11-27 19:19
Storage is a general setting for all users and migration is taking care of all files regardless of their owner. Since storage directory also contains logs and temporary files.
I already did introduced internal external option on my computer but I have some concerns about this big. From day 1 oc android was designed to use external storage if it is possible.

**Comment by jancborchardt** [comment] 2015-11-29 12:43
> So let's try it with internal/external. And if there are several users that want to have custom storage path we can intregrate it?

**Comment by jancborchardt** [comment] 2015-11-29 12:45
> So let's try it with internal/external. And if there are several users that want to have custom storage path we can intregrate it?

Exactly. Let’s do small steps, and only add stuff we really need.

@przybylski what do you exactly mean now? Storage is a setting per-user, but for all accounts, yes. And yep, when the storage is changed, the files also need to be moved over.

**Comment by przybylski** [comment] 2015-12-07 16:26
I did push some code regarding this and few other issues.
This code should work for SD cards but it needs a bit more work from UX perspective.
@jancborchardt could you have a look?
@tobiasKaminsky does my commits from externalSD2 needs to be merged into beta somehow?

**Comment by tobiasKaminsky** [comment] 2015-12-13 14:05
I have merged them into beta and replied to your pull request.

**Comment by tobiasKaminsky** [comment] 2015-12-29 14:28
pinging @jancborchardt

**Comment by michaelstingl** [comment] 2019-04-10 11:36
Beta feature never got released.

**Closed by michaelstingl** 2019-04-10 11:36 UTC
Labels: Design, bug, settings
