### ISSUE TITLE
[BUG - 1559]Beta: Cannot select account 

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1657] opened 2016-05-05 06:45 UTC
### Expected behaviour
When selecting account from drop down menu in sidebar, file list view should show files of that account. 

### Actual behaviour
File list view does not change. 

### Steps to reproduce
1. Create multiple accounts. 
2. Try to select second account via sidebar. 

### Environment data
Android version: 4.2.2
ownCloud app version: beta 20160427

**Comment by tobiasKaminsky** [comment] 2016-05-05 08:19
@AndyScherzinger I took a quick look and cannot find any code related to selecting an account on the drawer list?

**Comment by AndyScherzinger** [comment] 2016-05-05 11:40
Will have to further investigate since it works fine on my phone, but that is Android 6.0.1

**Comment by tobiasKaminsky** [comment] 2016-05-06 07:12
I have also an Android 6.0.1 with CyanogenMod.

**Comment by AndyScherzinger** [comment] 2016-05-15 15:46
@LukeOwncloud I tried to reproduce it in an emulator. Ehat happened to me was that the list gets replaced with an empty one. Is that also your seen behavior or does the file list of the formerly active account is getting shown?

@davivel do you know how and where I could enforce a refresh? Because when I switch the user in the drawer the list is empty but gets filled as soon as I do a pull to refresh :(

**Comment by LukeOwncloud** [comment] 2016-05-19 08:39
@AndyScherzinger What happens for me:

I am using account 1. I can browse through directories. Everything okay.

I select account 2. Sidebar disappears, files list stays the same. I tap any directory. A toast tell me: "Directory does not exist". After some seconds of refreshing I see the files from account 2. Now I can browse through directories. Everything okay.

Except: The sidebar still shows account 1 to be active, even though I am browsing account 2.

**Comment by rperezb** [comment] 2016-05-31 07:40
TRACKING info, @AndyScherzinger can't reproduce the error, @MTRichards we may work on this one, so that we may merge #1159 after reviewing, oc

**Comment by AndyScherzinger** [comment] 2016-05-31 08:03
@rperezb It might be that you need an "real" device in order to reproduce this. Sorry for not being of any help with this issue. My suspicion is that is has something to do with the processing of flags when the intent is called to basically restart the app. And it should also work the same way for the actual account switching. From what I understood a forced refresh would fix this issue, but I need @davivel's input on how this could be done. 

Also as already mentioned by @davivel the PR is a rather huge code change so it will need some overall testing since the PR not only introduce 
* a new drawer implementation but in order to do that it also 
* moved from the (legacy) action bar to the toolbar plus 
* it also introduces avatar loading/creation and 
* an account management to remove accounts and relogin in cases of a password change. 

So due to the toolbar change we need to at least open all activities present in the app to check if they can still be opened. If an activity hasn't yet adapted to the new toolbar the app will simply crash. This shouldn't happen since I went through the activities but I might have missed one (you never know).

**Comment by rperezb** [comment] 2016-06-02 07:56
@AndyScherzinger team work! we do have devices here, so it will be easy for us to reproduce the error.
It seems to be very well detailed the bug so easy for us to reproduce 😄 

Thanks for the testing pointers, they will be very helpul for @jesmrec test plan, btw, he is likely to ping you once he has the test plan ready on the [qa repo](github.com/owncloud/qa) as usual (keeping improving the process YAY! )

**Comment by AndyScherzinger** [comment] 2016-06-02 08:30
@rperezb glad to hear that! :smiley: Hopefully we'll find the bug soon since it is the only known issue at the moment. :) So waiting for @jesmrec's ping :+1:

**Comment by davivel** [comment] 2016-07-18 08:57
Is this still a bug? 

By the way, @tobiasKaminsky , are you still maintaining the Beta app in F-Droid?

Thanks.

**Comment by AndyScherzinger** [comment] 2016-07-18 09:26
@davivel I do think so since I haven't made any further changes (also due to the lack of a 4.x device)

**Comment by davivel** [comment] 2016-10-06 09:06
I was checking this one in #1559, so I will remove the beta label.

Right now seems to work fine. I would let @jesmrec confirms it in the validation stage.

**Comment by jesmrec** [comment] 2016-10-07 11:52
Checked in https://github.com/owncloud/android/pull/1559 and works fine. Closing this issue, anything related can be handled in the mentioned issue.

**Closed** 2016-10-07 11:53 UTC
Labels: accounts, bug
