### ISSUE TITLE
Application Not Responding / Crashes after v1.9 updates on S-Galaxy S4

### ISSUE THREAD

**Issue by aslmx** [owncloud/android#1333] opened 2015-12-07 10:57 UTC
Hi, 

updated today to v1.9 from the fdroid market. The version works fine on my S5 and on a colleagues phone (no idea what make and model, but its running cyanogen mod), but on my S4 i repeatedly encounter crashes when changing folders inside the app.

Log:

12-07 11:52:43.864 E/AndroidRuntime(28352): FATAL EXCEPTION: Thread-16681
12-07 11:52:43.864 E/AndroidRuntime(28352): Process: com.owncloud.android, PID: 28352
12-07 11:52:43.864 E/AndroidRuntime(28352): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.owncloud.android.lib.resources.shares.ShareType.getValue()' on a null object reference
12-07 11:52:43.864 E/AndroidRuntime(28352): 	at com.owncloud.android.datamodel.FileDataStorageManager.prepareInsertShares(FileDataStorageManager.java:1501)
12-07 11:52:43.864 E/AndroidRuntime(28352): 	at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder(FileDataStorageManager.java:1462)
12-07 11:52:43.864 E/AndroidRuntime(28352): 	at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder(RefreshFolderOperation.java:496)
12-07 11:52:43.864 E/AndroidRuntime(28352): 	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:216)
12-07 11:52:43.864 E/AndroidRuntime(28352): 	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303)
12-07 11:52:43.864 E/AndroidRuntime(28352): 	at java.lang.Thread.run(Thread.java:818)
12-07 11:52:43.864 V/ApplicationPolicy(  846): isApplicationStateBlocked userId 0 pkgname com.owncloud.android
12-07 11:52:43.864 W/ActivityManager(  846):   Force finishing activity com.owncloud.android/.ui.activity.FileDisplayActivity
12-07 11:52:43.914 V/FileDisplayActivity(28352): onPause() start
12-07 11:52:43.934 I/AudioPolicyManager(  399): getAudioPolicyConfig: audioParam;outDevice
12-07 11:52:43.934 V/AudioPolicyManager(  399): getNewOutputDevice() selected device 0
12-07 11:52:43.934 V/AudioPolicyManager(  399): ### curdevice : 2
12-07 11:52:43.934 I/dumpstate(28419): begin
12-07 11:52:43.954 D/StatusBarManagerService(  846): manageDisableList userId=0 what=0x0 pkg=WindowManager.LayoutParams
12-07 11:52:43.954 D/PointerIcon(  846): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
12-07 11:52:43.954 D/PointerIcon(  846): setMouseCustomIcon IconType is same.101
12-07 11:52:43.954 D/PointerIcon(  846): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0
12-07 11:52:43.954 D/PointerIcon(  846): setHoveringSpenCustomIcon IconType is same.1
12-07 11:52:43.964 D/CrashAnrDetector(  846): processName: com.owncloud.android
12-07 11:52:43.964 D/CrashAnrDetector(  846): broadcastEvent : com.owncloud.android data_app_crash

After the first crashes i downgraded back to v1.8, worked fine, updated to v1.9 again and reproduced the crashes.

Android 5.0.1
Kernel: 3.4.0-4971854
FW: I9506XXUDOE4 (Telekom Germany branded Galaxy S4 Advanced)

Let me know if you need further info.

**Comment by tobiasKaminsky** [comment] 2015-12-07 20:54
This has something to do with sharing, which is only supported in > 1.8, therefore 1.8 will not have these crashes.
@davivel @masensio

**Comment by xenithorb** [comment] 2015-12-09 14:58
Also seeing this on the stable F-Droid build on CM 12.1 (5.1.1)
```
D/OwnCloudClient #2(28754): REQUEST GET /ocs/v1.php/apps/files_sharing/api/v1/shares
D/FileDisplayActivity(28754): Setting progress visibility to true
D/audio_hw_primary(19259): out_standby: enter: stream (0xb58804c0) usecase(1: low-latency-playback)
D/hardware_info(19259): hw_info_append_hw_type : device_name = speaker
E/JsonRpc (21427): d.a@204: Error during request : 404
D/GetRemoteSharesForFileOperation(28754): Got 2 shares
E/AndroidRuntime(28754): FATAL EXCEPTION: Thread-1986
E/AndroidRuntime(28754): Process: com.owncloud.android, PID: 28754
E/AndroidRuntime(28754): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.owncloud.android.lib.resources.shares.ShareType.getValue()' on a null object reference
E/AndroidRuntime(28754):        at com.owncloud.android.datamodel.FileDataStorageManager.prepareInsertShares(FileDataStorageManager.java:1501)
E/AndroidRuntime(28754):        at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder(FileDataStorageManager.java:1462)
E/AndroidRuntime(28754):        at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder(RefreshFolderOperation.java:496)
E/AndroidRuntime(28754):        at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:216)
E/AndroidRuntime(28754):        at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303)
E/AndroidRuntime(28754):        at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(19535):   Force finishing activity 1 com.owncloud.android/.ui.activity.FileDisplayActivity
```

My status.php reports the following:
```
{"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":""}
```

**Comment by xenithorb** [comment] 2015-12-09 15:07
Turning off the Share API from the server admin panel does temporarily prevent the app from crashing.

**Comment by aslmx** [comment] 2015-12-16 15:31
disabling the share api will - according to admin ui - not only disable sharing with 3rd party apps, but also the user to user sharing.

Is there no possibility to fix this in the app?

**Comment by AndyScherzinger** [comment] 2015-12-17 17:14
pinging @davivel @masensio since you are the share api experts :smiley:

**Comment by Messinger** [comment] 2015-12-18 19:39
I have this crashes on any android device since 1.9, and this makes the application real unusable.

**Comment by tobiasKaminsky** [comment] 2015-12-19 07:00
@davivel It seems that somehow the ShareType is not correctly get from the server at 
https://github.com/owncloud/android/blob/master/src/com/owncloud/android/operations/GetSharesForFileOperation.java#L74

**Comment by creolis** [comment] 2016-01-01 22:40
Same problem here using Nexus 5X @ Android 6.0.1. Resetting / flushing cashes / full reinstall did not fix anything. Disabling the Share-API is a valid and tested temporary workaround.

**Comment by tobiasKaminsky** [comment] 2016-01-02 09:24
@creolis do you use federated sharing? In a similar issue federated sharing is the cause of the problem.

**Comment by creolis** [comment] 2016-01-04 15:21
@tobiasKaminsky It's not actually in use, but the feature itself is enabled and there is an actual federation configured.

**Comment by tobiasKaminsky** [comment] 2016-01-04 17:01
@creolis Can you disable and it try the app again?

**Comment by creolis** [comment] 2016-01-04 17:09
@tobiasKaminsky 

**Results:**
Enabling "Allow apps to use the Share API" => Crash
Disabling only "Allow users on this server to send shares to other servers" => Crash
Disabling only "Allow users on this server to receive shares from other servers" => Crash
Disabling both => Crash
Disabling "Allow apps to use the Share API" again => Works fine

**Versions:**
Android: 6.0.1
App: 1.9.0
ownCloud: 8.2.1

**Comment by xenithorb** [comment] 2016-01-14 13:44
leaning off of @tobiasKaminsky I only had one or two federated shares with another person using ownCloud and I removed those shares. App began working again even with the share API enabled. 

Is this not the right issue for that? My comments here on 12/9/15 are based on that as well

**Comment by nobswolf** [comment] 2016-01-15 22:13
I have the same problem on a HTC One m8. Disabling the share API and Federated Cloud Sharing is a workaround. When there will be a solution? I can help debugging on server side, but not on the mobile device.

**Comment by creolis** [comment] 2016-02-24 13:08
Fixed for me, using the following versions:

Android: 6.0.1
App: 1.9.1
ownCloud: 8.2.2

Thanks, guys :)

**Comment by davivel** [comment] 2016-02-24 16:59
@all, could you please test with version 1.9.1 as @creolis did and tell here your result? There was a crash fixed in that version that occurred when any federated share existed in the account. 

Thanks in advance.

**Comment by Messinger** [comment] 2016-02-24 17:04
Looks good here. Doesn't crash anymore.

**Comment by davivel** [comment] 2016-03-01 08:45
Nice!

Please, if anybody disagree, comment it. Thanks!

**Closed by davivel** 2016-03-01 08:45 UTC
Labels: bug, crash, share__through_OC_server
