### ISSUE TITLE
Monitor directories and upload new files like instant camera uploads

### ISSUE THREAD

**Issue by gnotaras** [owncloud/android#1011] opened 2015-06-13 11:15 UTC
I was wondering why the `instant camera uploads` feature is so specific and not a more general feature which could upload new files from any of user-defined directories. This kind of syncing functionality is missing and, since `instant camera uploads` has been implemented, I don't see any reason why not implement multiple directory monitoring and automatic uploading of new files to main server.

Kind Regards,
George

**Comment by tobiasKaminsky** [comment] 2015-06-14 08:57
This is an duplicate of #744

**Closed by tobiasKaminsky** 2015-06-14 08:57 UTC
