### ISSUE TITLE
Can't connect 

### ISSUE THREAD

**Issue by MeiRos** [owncloud/android#1630] opened 2016-04-23 19:25 UTC
### Expected behaviour

Login and instant upload should work. 
### Actual behaviour

I'm a new user and I have a fresh install owncloud app. I tried also Cirrus just before owncloud app. Firstly I couldn't login. I figured out that my ping to server have to be below 200 (about), before I can login. 

Same problem with instant upload. If ping is high, upload won't start. Have to be below 200 or something like that. Then instant upload starts. 
### Steps to reproduce
1. Find a slow connection to your server. 
2. Try to login or instant upload. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No, ping is only around 50 at the moment. 
### Environment data

Android version:
6.0
Device model:
LG G4

Stock or customized system:
Stock
ownCloud app version:
2.0.0
ownCloud server version:
9.0.1
#### Web server error log

```
Insert your webserver log here
```

Apache2 error.log
Nothing at the problem time
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```

Nothing at the problem time. 

I can login with browser while with app I can't.

**Comment by LukeOwncloud** [comment] 2016-04-25 15:02
> I can login with browser while with app I can't. 

This sounds like an IPv6 problem (-> https://github.com/owncloud/android/issues/616). Is it possible that whenever you have a slow connection you obtained an IPv6 address?

Can you provide a logcat log?

**Comment by MeiRos** [comment] 2016-04-26 18:53
That's a good question and I have no idea. Sometimes my owncloud vps is slow anyway so I thought there may be time out or something with the app. Just guessing... 

Unfortunately my phone isn't rooted so I can't get logcat.

**Comment by powerriegel** [comment] 2016-05-09 19:22
Same problem here. 
Owncloud Android App 2.0.0
Owncloud Server 9.0.1 
Running on Nginx 1.3.x (Debian Wheezy))
Router is a FritzBox 7360 with Firmware 6.3x
IPv6 is enabled. Android device is connected to wifi. 

Access via Browser works, CalDAV and CardDAV (via DAVDriod works. **Owncloud app does not work**. Neither up- nor download possible. 

Disconnected from wifi
Owncloud app works as usual. 

There are no log entries at the time of trial. 

This problem is there since OC8 and should immediatelly be fixed as IPv4 is almost obsolete.

**Comment by OCNewbie** [comment] 2016-11-14 12:39
Same Problem with me:
Owncloud Android App 2.1.2
Owncloud Server 8.2.7, PHP Version 7

Access via Browser works, Desktop Software works, Upload via webdav works (e.g. with the App "Scanbot") - but I can not login with the Owncloud Android App!

Owncloud Log shows attached comment:
![administration_-_owncloud_-_2016-11-14_13 30 23](https://cloud.githubusercontent.com/assets/23452918/20264974/91aa6a8a-aa6e-11e6-86a1-cba2d2c64c06.png)

I can change IPv4 to IPv6 and back without success.
Uninstalling and re-installing Owncloud JellyBean Workaround without success.

Any help?

Thank you!

**Comment by jesmrec** [comment] 2018-08-29 15:22
@MeiRos still reproducible?

**Comment by MeiRos** [comment] 2018-08-29 16:29
Hi @jesmrec !
Can't test this anymore and unfortunately I can't remember if this was fixed. Anyway, the server was a disaster. My data got lost some time after I opened this thread, because of the hdd break. :| And after that I forgot the whole thing. I didn't want to build the server again on that vps. :)

**Comment by jesmrec** [comment] 2018-08-29 16:36
ok, we can close this. If you think or remember to discuss about, feel free to reopen. thanks.

**Closed by jesmrec** 2018-08-29 16:36 UTC
Labels: bug, network
