### ISSUE TITLE
1.7.1 can't list any folder

### ISSUE THREAD

**Issue by lin-zhao** [owncloud/android#959] opened 2015-04-23 18:10 UTC
### Expected behaviour
1.7.1 app should be able to show folders.

### Actual behaviour
After I did a factory reset of my phone (LG G2), I installed ownCloud from Play store and can't see any files in the account

### Steps to reproduce
1. Factory reset the phone (may not be needed)
2. Install owncloud app from Play Store
3. Add an account to the app
4. Refresh account. The spinning icon finishes successfully but there's no folder in the account. Files show up alright.

### Environment data
Android version:
5.0.2

Device model: 
LG G2 Verizon

Stock or customized system:
Stock

ownCloud app version:
1.7.1
ownCloud server version:
8.0.2
#### Web server error log
Can't see any

Insert your webserver log here
access.log:
50.240.204.101 - lin [23/Apr/2015:14:09:38 -0400] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1490 "-" "Mozilla/5.0 (Macintosh) mirall/1.7.1"
50.240.204.101 - - [23/Apr/2015:14:09:39 -0400] "PROPFIND /remote.php/webdav HTTP/1.1" 401 7251 "-" "Mozilla/5.0 (Macintosh) csyncoC/0.91.5 neon/0.30.1"
50.240.204.101 - lin [23/Apr/2015:14:09:39 -0400] "GET /status.php HTTP/1.1" 200 6812 "-" "Mozilla/5.0 (Android) ownCloud/1.7.1"
50.240.204.101 - lin [23/Apr/2015:14:09:39 -0400] "PROPFIND /remote.php/webdav HTTP/1.1" 207 3195 "-" "Mozilla/5.0 (Macintosh) csyncoC/0.91.5 neon/0.30.1"
50.240.204.101 - lin [23/Apr/2015:14:09:40 -0400] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1651 "-" "Mozilla/5.0 (Android) ownCloud/1.7.1"
50.240.204.101 - lin [23/Apr/2015:14:09:40 -0400] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 3725 "-" "Mozilla/5.0 (Android) ownCloud/1.7.1"

Nothing in error.log

#### ownCloud log (data/owncloud.log)
Nothing happens during account refresh

**Comment by masensio** [comment] 2015-04-24 08:46
Hi @lin-zhao,

thanks for your feedback.

We've done some changes in the PROPFIND request to ask for PROP by PROP and not ALL_PROPS. 
I don't know if this change cause the problem, since we have tested 1.7.1 with Android 5 and server 8 before we released 1.7.1 version.

Also, we've added the user-agent in the requests. Do you have any firewall on your server?

Related with the rest of operations, how are they working?

On the other hand, we've received other bug related with this #940. I don't know if they are the same problem, but sure that they are related.
We'll take a look.

Please, if you have more information about this problem say us.

**Comment by rperezb** [comment] 2015-04-24 11:48
Hey,

Can you please tell us whether you have enable google drive as external storage?
thx

**Comment by lin-zhao** [comment] 2015-04-29 21:12
Hi @masensio ,

Thanks for the reply. https://github.com/owncloud/android/issues/940 doesn't seem related. My account is set to unlimited storage. The behavior seems to be:

1. A file/dir created on the web UI cannot be synced to the android app.
2. A file/dir created on the android app can be synced to the web UI, desktop UI and android app.

@rperezb , I don't have an external google drive storage. But I have local external storage that points to a directory mounted via s3fs. However, if I remove these external storages the issue persists.

![screen shot 2015-04-29 at 2 11 00 pm](https://cloud.githubusercontent.com/assets/5116965/7401520/bb18ed9a-ee79-11e4-8390-fee20cc28490.png)

**Comment by tobiasKaminsky** [comment] 2015-04-30 05:34
@lin-zhao It is exactly the other way.
Currently the android app seems to have a problem with unlimited user quota.
So you have to set it to a limit like 50 Gb.
Please try this.

**Comment by MrFly** [comment] 2015-05-12 14:24
I didn't notice any of this behaviour with my Nexus 6 and OC 8.0.3. I'm working with two accounts, one as admin, one as user. Both have unlimited quota set. I also have no external storage activated, but activated the app to be able to add external storages in the future. App version should be 1.7.1, too. Maybe this helps, if not, please ignore :-)

**Comment by andreicristianpetcu** [comment] 2015-05-13 13:41
Same thing here :(

Samsung Galaxy S5 (SM-G901F), ownCloud Android v 1.7.1, ownCloud server v8, Android 4.4.4 (stock android, no factory reset).
I just got a brand new smartphone and I did not fool around with the ROM and I did not factory reset it.
Strange thing is that the upload works fine. I enabled auto upload of pictures and it uploads it. It also sees the list of uploaded file.
I have ownCloud hosted and owncube so I have no access to the logs but I can check out various things with Wireshark if you are interested.

Thank you for building this app :P

**Comment by andreicristianpetcu** [comment] 2015-05-13 13:43
@lin-zhao Can yours auto-upload photos? Can you see them in the folder view inside the Android app?

**Comment by MrFly** [comment] 2015-05-13 15:37
Just for the files: I tried this with my hardware. I made a picture while having no WIFI. If I got back home and WIFI connected, the new photo uploaded immediately. The picture was shown inside the right folder. But if I scrolled down the photos inside the OwnCloud app again, the app crashed. But this is an other topic....

**Comment by lin-zhao** [comment] 2015-05-13 16:47
@andreicristianpetcu , yes I can auto-upload, but the behavior is weird:

I already have an InstantUpload/ folder, with hundreds of photos. Before I turn on auto upload, this folder is invisible form the android app.

After I turn on auto-upload and take a photo, the new photo gets uploaded, and InstantUpload/ appears in the app. But this folder only contains the new photo uploaded from the app.

On the web UI, the InstantUpload/ folder has all photos, included old ones and the newly taken.

**Comment by lin-zhao** [comment] 2015-05-13 16:48
@tobiasKaminsky , I changed the limit to ```100G```, or ```10G``` but the issue still happens.

**Comment by lin-zhao** [comment] 2015-05-13 17:14
@masensio @rperezb , can you guys provide a link to previous builds? Want to revert to earlier version until this is fixed. I tried to build from the earlier tags but it's not walk in the park for non-android developers.

**Comment by masensio** [comment] 2015-05-14 07:04
@lin-zhao, we are working in solving this issue. 
We are testing the solution to be released in the next version of the app. I hope our changes fix the problem.

For ensuring that your problem is fixed with our solution, could you please provide us a test account on your server to test our fix? Please, send us the credentials to apps@owncloud.com. In this way, we can check the solution and provide you a previous version, if it is necessary.

Thanks in advance.

**Comment by rperezb** [comment] 2015-05-14 09:19
This is duplicated of https://github.com/owncloud/android/issues/940 lets follow there its state, thx

**Closed by rperezb** 2015-05-14 09:19 UTC
Labels: bug, sync

**Comment by lin-zhao** [comment] 2015-05-14 17:03
@masensio , I found that the existence of a  local External Storage that points to a s3fs directory may be the trigger of the issue.

Steps:
1.  sudo s3fs -o allow_other s3-bucket-name:/ /var/s3mounts/mountpoint
2. Add a local external storage that points to /var/s3mounts/mountpoint

The added storage shows up on Web, desktop but not on the android app. 

I have sent the credentials to apps@owncloud.com to help you replicate.

**Comment by masensio** [comment] 2015-05-15 06:53
@lin-zhao, thanks for sending more details to reproduce this issue. That is useful for us to know if we fix the problem. 
Thanks for the credentials too. We will use them in our test.

**Comment by rperezb** [comment] 2015-05-15 07:23
Thanks @lin-zhao we have been able to reproduce the error as well as check that the fix works.
It will be published within the next version,.
