### ISSUE TITLE
Show ownCloud in native Android file manager

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#709] opened 2014-11-06 12:55 UTC
(Screenshot from issue #596 courtesy of @tobiasKaminsky)
![](https://cloud.githubusercontent.com/assets/5836855/4689604/ea542930-56c1-11e4-84f3-07fcd4e80f24.png)

In that list to the left, how can we make ownCloud show up there so it’s browsable? Seems we should be in there.

@davivel @tobiasKaminsky any idea?

**Comment by strugee** [comment] 2015-05-16 09:29
Duplicate of #296

**Comment by jancborchardt** [comment] 2015-05-18 10:09
Is it? @davivel – also when can we fix this? ;)

**Comment by davivel** [comment] 2016-02-11 16:52
True: duplicate of #296.

**Closed by davivel** 2016-02-11 16:52 UTC
Labels: browse, enhancement, share__send_files_to_apps
