### ISSUE TITLE
OwnCloud app shows incomplete list of folders

### ISSUE THREAD

**Issue by fungs** [owncloud/android#864] opened 2015-01-25 13:25 UTC
Having a folder with many subfolders, recent folders show up in the web interface for the respective user but the Android app fails to list recent subfolders even after hitting manual sync button.

I'm using the latest version of the Android app and OC7.

**Comment by LukeOwncloud** [comment] 2015-02-03 11:52
Please check if you are correctly connected when pressing refresh button. There is currently to feedback which would tell the user that something when wrong while refreshing (e.g., no server connection). I made pull request on this issue: https://github.com/owncloud/android/pull/796

**Comment by LukeOwncloud** [comment] 2015-05-22 08:09
Most probably a duplicate of https://github.com/owncloud/android/issues/688

**Closed by LukeOwncloud** 2015-05-22 08:09 UTC
