### ISSUE TITLE
Enhancement: Force instant upload via button press

### ISSUE THREAD

**Issue by Fmstrat** [owncloud/android#980] opened 2015-05-15 13:42 UTC
Like many, I use the Instant Upload feature to backup pictures so I can remove the images from my device when it starts to fill up. However, often times I've noticed a failed instant upload is never retried and I've lost images because they weren't in sync with ownCloud.

I would love a feature added to the app via a button press that checks for any files in DCIM that are not in the InstantUpload folder and uploads them. Or, if the app works by keeping track of successful uploads, forcing a sync on anything not marked as successful.

Thanks.

**Comment by strugee** [comment] 2015-05-16 08:48
This isn't great UX. Instant Upload should Just Work™. The solution to this isn't to add something else for the user to deal with, the solution is to get #919 merged.

**Comment by LukeOwncloud** [comment] 2015-05-18 10:41
Duplicate of https://github.com/owncloud/android/issues/340

**Closed by LukeOwncloud** 2015-05-18 10:41 UTC
