### ISSUE TITLE
update folder list before uploading via share with owncloud

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/android#198] opened 2013-06-26 11:37 UTC
I just made a folder via the web interface. When I want to share a photo on my phone and I get to select the upload folder I cant choose the new folder since the folderlist is not up to date.
Please add a "refresh folder list" in the select upload folder dialog.

**Comment by pascalBokBok** [comment] 2015-04-12 10:26
There is still no refresh option in the Share/"send to owncloud" dialog. Was it not supposed to have been fixed?

**Comment by tobiasKaminsky** [comment] 2015-04-12 12:40
Right. The list should be updated when entering the directory.
So there is no need to have a refresh button.
Can you verify if this works?

**Comment by pascalBokBok** [comment] 2015-04-12 15:29
it does not work.

**Comment by tobiasKaminsky** [comment] 2015-04-12 19:20
Have you tried the PR #821 by yourself?
Otherwise you cannot test it as it is not merged into develop tree and therefore not yet in the public available app, as statet in Edit in my previous post.

**Comment by pascalBokBok** [comment] 2015-04-13 06:36
No. Didn't see edit.

**Comment by orzel** [comment] 2015-04-28 12:04
I'm still having this problem with uptodate owncloud (server and android client). This is especially frustrating as it is a very common pattern to create a directory before uploading ('sharing' here).

**Comment by tobiasKaminsky** [comment] 2015-04-30 05:43
@orzel Please read more carefully. 
The code is not yet merged...

**Comment by michaelstingl** [comment] 2015-05-27 19:22
@rperezb will this be fixed with next release? (there is a PR) /cc @MorrisJobke

00003239

**Comment by tobiasKaminsky** [comment] 2015-06-27 19:28
@davivel 
There is already a PR, but it is again outdated...
It would be great if such PR could get merged sooner as it is sometimes quite much work to update the branch and resolve all conflicts...

**Comment by michaelstingl** [comment] 2015-07-02 09:48
@rperezb Any news on this?

**Comment by davivel** [comment] 2015-07-22 15:46
Will be fixed in the next release, 1.8

**Comment by michaelstingl** [comment] 2015-07-22 16:48
@davivel This is good news! Thanks!

**Comment by davivel** [comment] 2015-09-15 07:40
Sorry @michaelstingl , needs to wait for 1.8.1.

**Comment by davivel** [comment] 2015-11-12 12:19
With the current schedule there is no way we can have this done for https://github.com/owncloud/android/milestones/1.9-current .

Moving to next release.

cc @rperezb , @MTRichards , @cmonteroluque

**Comment by pascalBokBok** [comment] 2015-11-16 07:34
If it could auto update like the main window does now ( with "status bar" in top ) then you could skip having a button

**Comment by davivel** [comment] 2016-01-29 09:27
Sorry, but this needs to be delayed once again.

**Comment by AndyScherzinger** [comment] 2016-01-29 09:38
Hi @bboule It is label-wise in "3 - in review" imho, since @tobiasKaminsky already opened a pull request, see #1399 :)

**Comment by MTRichards** [comment] 2016-01-29 12:55
For transparency, the delay is as @davivel said in another issue, because we need to regression test and release a fix quickly for #1442 , then we will get right back to this for the next release.

**Comment by davivel** [comment] 2016-03-22 13:01
This was solved via #1399

**Closed** 2016-03-22 13:02 UTC
Labels: 3 - To review, blue-ticket, in progress, share__receive_files_from_apps

**Comment by pascalBokBok** [comment] 2016-03-22 14:07
@davivel 
When will it roll out? 
It doesn't work in the version I have on my phone.

**Comment by AndyScherzinger** [comment] 2016-03-22 14:35
This will be part of the upcoming release 1.9.2 which is expected to be sometime around end of March.
