### ISSUE TITLE
Photos/Videos auto-sync stopped working

### ISSUE THREAD

**Issue by miodzicho** [owncloud/android#1795] opened 2016-09-03 18:51 UTC
### Actual behaviour
Photos/Videos auto-sync doesn't work anymore, last succesfull sync was 2 days ago.
Uploads list is empty, no files to sync. They are new photos/videos to sync.

### Expected behaviour
Photos/Videos should be auto synced to SofortUpload directory on Owncloud server.
 
### Steps to reproduce
1. take photo/video
2. photo/video should appear on Uploads list
3. photo/video should be synced to directory on the server

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 6.0.1

Device model: HTC M10

Stock or customized system: stock

ownCloud app version: 2.1.1

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by RealRancor** [comment] 2016-09-04 14:09
Also reported at IRC as well as at central: https://central.owncloud.org/t/adroid-6-0-1-client-intant-uploads-not-working/2152?u=realrancor

The user in IRC reported that using the "ocloud" client works again. That one seems to be a themed but quite outdated version 1.7.2 of the official app.

**Comment by rkarlsba** [comment] 2016-09-04 14:52
For the record, I (that IRC user) just tried to uninstall and reinstall the client after removing the ocloud client and same results. Guess I'll stick to the ocloud client until this is fixed.

**Comment by admered1** [comment] 2016-09-04 21:05
I'm seeing the same here.

owncloud android 2.1.1

HTC One M8 - Droid 6.0

It's not even getting as far as trying to upload, so server version not relevant.

This has been working fine for years.

**Comment by andykvakk** [comment] 2016-09-05 05:43
I'm seeing the same. Galaxy S7 - Android 6.0.1. Have tried reinstalling client and also tride to switch from internal to sd and back without luck.

**Comment by davivel** [comment] 2016-09-05 06:54
Hi, everybody.

The underlying implementation of instant uploads has changed to try to support more devices and camera apps, including Android 7.

As an undesired side effect, you need to access the app settings and select the location where your camera app stores the pictures and videos in a new option called "Camera folder". The default value corresponds to the default location for Google Camera app (and others), but might not be yours.

Please, try to set this folder and tell us if the pictures are still not captured.

**Comment by andykvakk** [comment] 2016-09-05 07:07
Hello again. I have tried different settings, and also changing from SD to internal storage with no luck.

This screenshot shows the settings in owncloud:
![screenshot_20160905-085936](https://cloud.githubusercontent.com/assets/21997405/18239824/243c1370-7348-11e6-8c37-fe93d254b91d.png)

This image was taken as a test:
![20160905_073018](https://cloud.githubusercontent.com/assets/21997405/18239742/93e039b4-7347-11e6-9112-20c626019772.jpg)
This screeshots shows the filepath:
![screenshot_20160905-090040](https://cloud.githubusercontent.com/assets/21997405/18239765/ab490afe-7347-11e6-85c5-794282a274f6.png)
This shows the folder in TC:
![screenshot_20160905-090113](https://cloud.githubusercontent.com/assets/21997405/18239788/d7e65dc8-7347-11e6-83af-9afb26710645.png)

The images is not being uploaded instantly.

**Comment by davivel** [comment] 2016-09-05 07:10
Thank you, @andykvakk . These pictures correspond to a configuration saving is SD card? What is your camera app?

**Comment by andykvakk** [comment] 2016-09-05 07:13
I use the standard Samsung APP v. 5.0.88. I will also do at test on my wifes Nexus 5 as soon as possible.

**Comment by davivel** [comment] 2016-09-05 07:16
Thanks a lot. I would expect no problem with Nexus 5, we tested with several of them, but any feedback is welcome.

Please, could you try also with some other camera app in your device? I could suggest Open Camera - it's free, open source, and you can find it both in Google Play Store, F-Droid and maybe other stores.

**Comment by andykvakk** [comment] 2016-09-05 07:22
Testet open camera, changed the storage folder to same setting, but still no luck. Nothing happens in Owncloud client.

**Comment by davivel** [comment] 2016-09-05 07:58
In 'Open Camera', 'Settings' icon, 'More camera controls...', is the option 'Use Storage Access Framework' enabled? In that case, could you test with it disabled?

**Comment by andykvakk** [comment] 2016-09-05 08:09
Yes, it was enabled. Disabled it, but was not able to change to /storage/3338-6339/DCIM/Camera so i used /storage/emulated/0/DCIM/Camera, then it works from OpenCamera but still not from Samsungs app (which i also changed to same folder). This is strange.

Now both camera apps store the images to same folder, but only images from OpenCamera gets uploaded.

**Comment by davivel** [comment] 2016-09-05 08:27
OK, thanks. This is the second time we watch this effect, and I also could confirm it on a Nexus 5. Samsung camera probably is using Storage Access Framework all the time.

For some reason, files created with ```DocumentsContract.createDocument``` are not noticed by inotify and our new implementation doesn't detect them.

Definitely, we need to deal with this ASAP.

**Comment by andykvakk** [comment] 2016-09-05 08:37
Ok. Do feel free to contact me if you want me to test more.

**Comment by johfeu** [comment] 2016-09-05 09:09
likewise. I have the same thing on Xperia 6.0.1

**Comment by admered1** [comment] 2016-09-05 09:18
David A. Velasco said: "As an undesired side effect, you need to access the app settings and select the location where your camera app stores the pictures and videos in a new option called "Camera folder". The default value corresponds to the default location for Google Camera app (and others), but might not be yours."

I have tried the various paths to get to the Camera folder, but none of them make any difference I'm afraid.

**Comment by rkarlsba** [comment] 2016-09-05 10:35
I've also chosen to store images on the SD card (Sony Z3+ phone)

**Comment by rkarlsba** [comment] 2016-09-05 10:59
I hope this is fixed soon (as in fixed, not asking users to do a bunch of workarounds). Older versions just worked without fiddling around with stuff. This is important owncloud to be easy to use for non-geeks.

**Comment by gnul** [comment] 2016-09-05 22:38
I'm having the same exact issues as andykvakk. No instant upload  from my camera folder '/storage/FA8F-27EF/DCIM/Camera'. I'm using LG G5, Android 6.0.1, LG's "Camera" app 5.0.83.

**Comment by jesmrec** [comment] 2016-09-06 16:47
Could you check the fix in branch `instant_upload_combined_solution` and give us feedback about? Thanks in advance.

cc @miodzicho @gnul @rkarlsba @johfeu

**Comment by andykvakk** [comment] 2016-09-06 17:08
I will gladly test, but i'm not sure how to get the fix on my phone. I have found the branch, but should there be an . apk file?

**Comment by davivel** [comment] 2016-09-06 17:58
No, @andykvakk , sorry. At the moment you need to know how to build the app from source code to test it.

**Comment by johfeu** [comment] 2016-09-07 06:00
I was able to build android_2.1.1-debug.apk successfully, but it would not install :( any clue where to find install logs or how to figure out what went wrong?

**Comment by davivel** [comment] 2016-09-07 06:31
@johfeu, if the official Android app is installed in the same device, you will not be able to install a client build by yourself due to security rules.

But don't uninstall your official app, please.

Given the interest in this feature, let me prepare an APK that you all can test.

**Comment by davivel** [comment] 2016-09-07 07:20
Find a test APK in https://github.com/owncloud/android/blob/instant_upload_combined_solution/android_2.1.2-beta-debug.apk .

It can be installed in your device without uninstalling your current ownCloud app, will appear as another app, ownCloudTest. You will need to allow APKs from "Unknown sources" in your device settings to install it. Then, disable instant uploads in your regular ownCloud app and start ownCloudTest as usually to enter your account details, enable instant uploads and give it a try.

If instant uploads were working for you in version 2.1.0 you can ignore the "camera folder" option.

**Comment by gnul** [comment] 2016-09-07 08:01
Thank you.
This fixed the issue on my device.

**Comment by johfeu** [comment] 2016-09-07 08:10
Same here, thanks.
Its uploading standard images and videos. Panorama images as well, but time-shift video and other effect images (from Sony default camera app) would not upload.
That is probably expected behaviour?

**Comment by perhof** [comment] 2016-09-07 08:10
Solved the problems for me too and it didn't cause and other problems as far as I can see.

**Comment by andykvakk** [comment] 2016-09-07 08:10
This fixed the issue on my device aswell. I have tested Samsungs camera app with saving to both internal and external sd card.

**Comment by davivel** [comment] 2016-09-07 08:13
@johfeu , the expected behaviour is that it works for you exactly as it worked in 2.1.0. Were time-shift video and effect images working before?

We know there are much more improvements to do in this feature; at the moment, we just pretend to push a hot-fix to get Android 6 users working as they were before 2.1.1

**Comment by Fukurokudzu** [comment] 2016-09-07 11:45
Looks like it works on huawei stock cam.

**Comment by jesmrec** [comment] 2016-09-07 12:21
With Nexus5 +  Android 6 + Default Camera

If you turn the device network connections off, and the instant uploads are enabled in "only wifi"  mode, the files are duplicated in que uploads queue and after the connection is recovered, are upload twice.

cc @davivel

**Comment by davivel** [comment] 2016-09-07 15:48
@jesmrec, working on a fix.

**Comment by davivel** [comment] 2016-09-07 17:04
@jesmrec , added extra check to filter duplicated detections; ready to test.

**Comment by cschwarz007** [comment] 2016-09-07 19:19
It works on Sony stock camera perfectly. Thanks a lot!

**Comment by OlivierS1** [comment] 2016-09-07 21:15
When running 2.1.1, transfer seemed sketchy at first but then was able to do instantupload.
However, as I was checking the different settings, I came to edit the "Camera folder" setting location which should point to "/storage/emulated/0/DCIM/Camera" on my LG3 phone.
However, what I found is that I cannot see the folders present below "/storage/emulated".
Then I found this post and decided to try the APK.
By default, the "Camera folder" setting was loaded with "/storage/emulated/0/DCIM/Camera" and instantupload would work, but it somewhat work with 2.1.1 at some point.
Anyway, I decided to edit "Camera folder" setting and I get the same issue. I cannot see any folders under "/storage/emulated".
I am also experiencing slow response on the default file manager. It now takes a considerable amount of time to display anything. I suspect it is caused by the Google update.
I suspect the APK is not quite the fix as it doesn't allow me to list all the folders preventing me from accessing the camera folder.

**Comment by davivel** [comment] 2016-09-07 21:24
@OlivierS1, were instant uploads working with version 2.1.0 in your device and with your favorite camera app? If that was the case, then you don't really need to select the camera folder to get the instant uploads working. You would only get a benefit with the camera folder option if you try to use a camera app that was not working with ownCloud Android app 2.1.0.

In any case, the behavior you talk about is quite strange. What model is your device? What Android version does it contain? Did you upgrade it recently?

**Comment by OlivierS1** [comment] 2016-09-07 22:27
@davivel , It used to work under 2.1.0 but I got some Google notification about app compatibility and I thought it was a possible cause. I had to power of my phone to take out the SD card and after I put it back in, I tried to take some picture witht he camera app and was getting a message such as "Cannot save" or similar.
I noticed then the SD card logo on the top of the camera App and when i pressed the icon, it showed another type which might look like a folfer, but not quite certain. Anyway, it seemed to work and this was with version 2.1.1 as of last night.
As I said, I cannot go deeper into the emulated folder.
Phone model number: LG-D852
Android 6.0
Android security patch level 2016-07-01
The Google update appeared a couple of days ago and I think I started experiencing some issues around that time, but still remain uncertain.

**Comment by davivel** [comment] 2016-09-08 09:24
Seems a quite specific problem. Could you open a separate issue in Github and copy your previous messages there, please?

**Comment by jester-ro** [comment] 2016-09-08 12:30
Unfortunately i can't pinpoint what exactly triggered this either, i have the same issue with the stock camera folder on a Samsung S7. The .apk provided earlier seems to work tough.

**Comment by NickyHeuperman** [comment] 2016-09-08 13:39
The proposed fix works for me (Samsung Galaxy S6 EDGE, android 6, samsung camera)

**Comment by wobblywob** [comment] 2016-09-08 15:56
The provided APK fixed the issue for me. My problem was the same as most commentators':
- default camera's photos were not detected neither on local storage nor on SD Card
- Open Camera photos weren't detected with Storage Access Framework (local or SD)
- Open Camera photos were detected with SAF disabled.

**Comment by ctrlbru** [comment] 2016-09-08 20:08
I confirm the test apk fixes the issue on LG G3 with stock camera app on external sd folder. Photos and videos not synchronized in the meantime seem to remain not synchronized, I guess I'll have to upload them manually.

**Comment by kaffeeringe** [comment] 2016-09-09 07:58
Same Problem on my OnePlus 2 with their version of Android 6.0.1

When I try to choose the camera folder, the app tells me, the folder is empty - like any other folder I choose. 

The App seems not to see the pictures.

**Comment by davivel** [comment] 2016-09-09 08:27
@ctrlbru , sorry, you are right, you will need to upload those pictures manually from the list of files.

@kaffeeringe , files are not listed in the 'Camera folder' option, only folders (we should improve that showing files as disabled elements). You should both files and folders from the uploader. Go to the list of files in the app, tap on the (+) button, then the top ```upload``` icon; that file browser shows files and folders.

**Comment by e-alfred** [comment] 2016-09-09 17:29
Same problem here, running 2.1.1 of the client on a BQ M5 running Android 6.0.1. Nothing gets uploaded despite the right folder is set.

**Comment by amjiphone** [comment] 2016-09-09 17:36
I have a Galaxy Note 5 that was experiencing this issue and the test .apk is working on my phone now with the default camera app. Android 6.0.1

**Comment by marchaase** [comment] 2016-09-10 00:50
I have a Galazy Note 5 - Android 6.0.1.  I use the default Samsung Camera app.  My photos are not syncing with the Google Play app nor the Test apk linked in this thread.

In both apps, if I try to manually upload a file from the location: /storage/emulated/0/DCIM/Camera it works fine, I can see pics and upload them.

When setting the InstaUpload settings, if I navigate back from the default directory, once I get down to /storage/ and click on emulated - it then lists there are no folders available in /storage/emulated.  Also in the same dialog, when in the /storage directory, it lists the emualted directory's date as 12/31/2014 - which seems odd.

**Comment by janarzz** [comment] 2016-09-11 09:51
Hey, 
I have problem with owncloud app version 2.1.1
When i take a photo, then owncloud not upload my photo automaticly...
I marked owncloud settings upload my photo automaticly.
Photos location /storage/0123-4567/DCIM/Camera.
I use Samsung Galaxy S7 and android version 6.0.1

**Comment by hiliev** [comment] 2016-09-11 12:27
The test APK restored automatic sync of photos stored to the internal memory on Xperia Z3 Compact with Android 6.0.1.

**Comment by janarzz** [comment] 2016-09-12 09:24
Hey, when goming this fix in Google Play Store ?

**Comment by davivel** [comment] 2016-09-12 09:39
Very soon. We'll release a hot-fix version ASAP. Stay tuned.

**Comment by davivel** [comment] 2016-09-12 09:39
By the way, @janarzz , did you try the test APK? Did it work for you?

**Comment by jesmrec** [comment] 2016-09-12 14:09
The validation is in this status:

- [] Pics/videos that are duplicated in the queue (https://github.com/owncloud/android/issues/1795#issuecomment-245263247) [in progress]
- [X] Pics stored in SD card
- [X] Different camera apps
- [X] Different target folders (Android 7 feature, and optional for Android 6 and previous versions)
- [] Check folders that are not browsable to be selected (https://github.com/owncloud/android/issues/1795#issuecomment-245845867) @davivel [in progress]

**Comment by davivel** [comment] 2016-09-12 14:45
@OlivierS1, @kaffeeringe, @marchaase, could you please try to get to the camera folder through the paths ```/sdcard/DCIM/``` or ```/mnt/sdcard/DCIM```, please? Android is making some black magic with paths, symbolic links and the good-old ```Environment.getExteralStoragePath()``` method.

**Comment by delumerlino** [comment] 2016-09-12 14:59
The test app works fine with Huawei P8 Lite and Android 6.0 :)

**Comment by marchaase** [comment] 2016-09-12 15:33
I am back on the playstore version.

If I use the + button to try to upload a file, I can see pictures in all 3
folders: /storage/emulated/0/DCIM/Camera, /sdcard/DCIM/Camera, and
/mnt/sdcard/DCIM. Using this add file navigator it starts in the emulated
directory, and when I go up a directory to /storage/emulated all file
listings and folders disappear even though I was just in 0 and seeing files
and folders.

When I use the instant upload directory chooser and the 2 new folders
requested. I can get to the folders fine, but in the folders I don't see
any pictures (not sure if existence of pictures is expected or not here).
When any of the 3 folders are selected, no pictures upload.

Let me know if you need any more info.

**Comment by amjiphone** [comment] 2016-09-12 17:03
@marchaase With the test .APK file, set your folder path to /storage/emulated/0/DCIM/Camera then take a new picture after setting that folder path. We have the same phone and android version and it works just fine for me.

I am experiencing the folders not displaying properly in the app navigator when trying to choose a new camera folder as well. It seems once I hit /storage/emulated/ the folders in there do not display properly,even on the test .apk file. All other folders seem to display just fine.

**Comment by OlivierS1** [comment] 2016-09-12 17:30
I suspect Google update have changed folder permissions and ownerships causing this series of issues.

**Comment by janarzz** [comment] 2016-09-12 18:16
Hey,
What is the right camera folder location Samsung Galaxy S7 ?

**Comment by davivel** [comment] 2016-09-13 09:07
> I suspect Google update have changed folder permissions and ownerships causing this series of issues.

Well, I'm not sure if was the Google update or was there before in Android 6, but the permissions of the folders are the key.

In any case, please, take this into account:

** If instant uploads were working in your device with ownCloud Android app version 2.1.0, then you don't really need to care about the value of the 'Camera folder' option. That option is only required if you are using Android 7 or if instant uploads never worked for you before **

I'll add an ugly clarification to the option. Since we'd like to get the uploads fixed really fast, we'll make a fast release just that way. We can care about a better UI in settings in subsequent releases.

**Comment by davivel** [comment] 2016-09-13 14:42
That should do it. Updated the test APK in https://github.com/owncloud/android/blob/instant_upload_combined_solution/android_2.1.2-beta-debug.apk just in case anybody is curious. Added better filtering to prevent duplicated uploads.

ETA for release: tomorrow.

**Comment by jesmrec** [comment] 2016-09-13 15:38
The feature with the last APK seems to be OK. Anyway, all the feedback you can give us will be helpful. Thanks everybody for your contributions.

**Comment by ljephson** [comment] 2016-09-14 02:24
Thanks! I was having issues with Note 4 android 6.0.1 running oc 2.1.1 with the instant upload and the latest .apk worked. 

https://github.com/owncloud/android/blob/instant_upload_combined_solution/android_2.1.2-beta-debug.apk

**Comment by davivel** [comment] 2016-09-14 10:34
This is a now merged and pushed to the Play Store, will be available as soon as Google processes the update, what usually takes not too much time.

Thank you everybody for you help testing this, has been fundamental.

**Closed** 2016-09-14 10:35 UTC
Labels: bug, sync::instant_upload
