### ISSUE TITLE
Storage access ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#3777] opened 2022-10-17 20:26 UTC
I use version `v2.21.2` and I can select a file from ownCloud by selecting a file from an other app 👍 -fine-
![image](https://user-images.githubusercontent.com/3314607/196275985-e8cfcbcd-c448-44a1-a620-f190fff1f6e8.png)

Does someone know how to select a complete directory from ownCloud from an other app ?
I do this 
```
val intent = Intent(Intent.ACTION_OPEN_DOCUMENT_TREE)
startActivityForResult(intent, OPEN_DIRECTORY_REQUEST_CODE)
```
![image](https://user-images.githubusercontent.com/3314607/196276206-281d2e2b-1fa2-4bdb-9f00-ec6d8b1209b2.png)

But I can't access ownCloud

**Comment by hannesa2** [comment] 2022-10-18 04:41
> I use version `v2.21.2` and I can select a file from ownCloud by selecting a file from an other app 👍 -fine- ![image](https://user-images.githubusercontent.com/3314607/196275985-e8cfcbcd-c448-44a1-a620-f190fff1f6e8.png)
> 

Maybe you can give me a buzzword how you added this `ownCloud` entry in "Open from" file list ?

**Comment by hannesa2** [comment] 2022-10-18 09:08
I asked in [strackoverflow](https://stackoverflow.com/questions/74108371/android-list-all-files-in-drectory-from-scheme-content-uri ) as well.

Maybe someone knows

**Comment by abelgardep** [comment] 2022-10-18 09:59
Hi @hannesa2 , this is kind of duplicate of https://github.com/owncloud/android/issues/3339.

Here I posted my thoughts about it https://github.com/owncloud/android/issues/3339#issuecomment-902645936

If you want more info:
- This is our DocumentsProvider implementation: https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
- Here you have a little guide: https://developer.android.com/guide/topics/providers/create-document-provider
- Here you will see the options for each file/root https://github.com/owncloud/android/tree/master/owncloudApp/src/main/java/com/owncloud/android/providers/cursors

**Comment by hannesa2** [comment] 2022-10-18 11:03
Yes, this is exactly my problem ! I'll keep it open for some days to be able to discuss

**Comment by abelgardep** [comment] 2022-10-31 07:24
I'll close this issue, we can discuss on the other issue -> #3339

**Closed by abelgardep** 2022-10-31 07:24 UTC
