### ISSUE TITLE
Hi @sd1998 , I am facing same issue and instant run option is not available on latest version kindly help me that how can i resolve this issue.

### ISSUE THREAD

**Issue by zaibidev** [owncloud/android#2916] opened 2020-07-05 21:21 UTC
Hi @sd1998 , I've just noticed the same problem while using a different computer and I have fixed by **disabling the Instant Run feature**. To do that, go into File > Settings > Build, Execution, Deployment > Instant Run and disable it.

_Originally posted by @davigonz in https://github.com/owncloud/android/issues/2060#issuecomment-347826895_

**Comment by hannesa2** [comment] 2020-07-06 04:10
Run `git clean -xdf`

and invalid caches

<img width="260" alt="image" src="https://user-images.githubusercontent.com/3314607/86554914-32926d00-bf4f-11ea-8ef2-f49d18d7f0e2.png">

Btw, this is a **local** problem, I vote to close it

**Comment by jesmrec** [comment] 2020-07-06 07:04
If the problem is related with another issue, please post the problem there, reopen it, or open a new issue with a significative title and description.

Check the fix that @hannesa2 suggested you.

Closing...

**Closed by jesmrec** 2020-07-06 07:04 UTC
