### ISSUE TITLE
Create account page shows "unknown error" when adding URL with trailing slash

### ISSUE THREAD

**Issue by mrumpf** [owncloud/android#603] opened 2014-09-01 20:43 UTC
When I enter the owncloud URL with a trailing slash:
https://192.168.0.3/owncloud/
I get an "unknown error" message when hitting the enter button.

The Apache2 access log was showing the following entries:
192.168.0.246 - - [01/Sep/2014:20:35:21 +0000] "GET /owncloud//status.php HTTP/1.1" 200 773 "-" "Android-ownCloud"
192.168.0.246 - - [01/Sep/2014:20:35:21 +0000] "HEAD /owncloud//remote.php/webdav/ HTTP/1.1" 403 681 "-" "Android-ownCloud"

You could see that the HEAD request gets a 403 Forbidden response and the context path was showing a double slash "owncloud//status.php".

After removing the trailing slash the error message went away. The Android App should strip the trailing slash so that the user does not get confused by this kind of error.

**Comment by davivel** [comment] 2015-01-21 16:29
Sorry, but seems this was already fixed in some of the 1.6.x releases. 

@mrumpf , could you confirm wether this is still a problem for you with current version 1.6.2? Thanks

**Comment by tobiasKaminsky** [comment] 2015-01-21 17:01
@davivel Are you sure? I have reproduced the double // with the scenario described above. Although this does not lead to any problem for me.

**Comment by davivel** [comment] 2015-02-02 14:28
I tested again, I cannot reproduce the double slash. I used oc-android-1.6.2 with oc-android-library-0.9.4.

What branch did you use for your test, @tobiasKaminsky ?

@mrumpf , any comment?

**Comment by tobiasKaminsky** [comment] 2015-02-03 12:12
@davivel It was develop.
But as stated above: It did work for me, but I saw // in the log files.

**Comment by rperezb** [comment] 2015-04-15 12:27
Closed for inactivity, from our end it is working, if this were a problem, please reopen

**Closed by rperezb** 2015-04-15 12:27 UTC
Labels: bug, login
