### ISSUE TITLE
Feature Request: shortcut home-screen

### ISSUE THREAD

**Issue by EtienneBruines** [owncloud/android#842] opened 2015-01-19 08:24 UTC
It would be nice to be able to add a shortcut to the Android homescreen, to start ownCloud in a specific folder. 
# Current behavior
- I start ownCloud, traverse to "public/Images/TestDirectory1".
- I press "HOME" (button). This takes me to the home screen. 
- I start ownCloud again. I am now already in "public/Images/TestDirectory1".
# Desired behavior
- I start ownCloud, traverse to "public/Images/TestDirectory1".
- I press "HOME" (button). This takes me to the home screen. 
- I click the shortcut I created. I am now in "public/JW/Books", because that's where I pointed the shortcut. 
# Why?

This way, you can quickly access folders you'd want to access often, without having to traverse to that folder from your previous location.

**Comment by jabarros** [comment] 2015-01-20 07:33
Sure, this would be an interesting enhancement.
Contributions are welcome! :)

**Comment by purigarcia** [comment] 2015-08-21 08:15
@tobiasKaminsky , @AndyScherzinger , @LukeOwncloud and whoever feels like, contributions are wellcome here :)

**Comment by tobiasKaminsky** [comment] 2015-08-23 19:22
duplicate of #383?

**Comment by purigarcia** [comment] 2015-08-24 08:45
@tobiasKaminsky, you are right. Although I am not sure if they are asking the exactly the same, but for sure they are similar. So maybe it is not a good idea to start to do things here, however there is a pr pending in the other issue.

**Comment by harshitbansal05** [comment] 2018-02-07 07:04
@tobiasKaminsky i want to work on this issue, I think we should come to a common solution for issues #383 and #842.

**Comment by jesmrec** [comment] 2022-03-31 10:20
No plans to implement ftm.

**Closed by jesmrec** 2022-03-31 10:20 UTC
Labels: Enhancement, Contributions are welcome
