### ISSUE TITLE
Actions in long-press menu

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1144] opened 2015-09-08 10:49 UTC
![](https://cloud.githubusercontent.com/assets/1315170/9714873/8ccde6cc-555b-11e5-9440-878aa98b2567.png)

* Share link
* Open with
* Update file
* Rename
* Move
* Copy
* Delete
* Send
* Favorite
* Details

3 things we can do here: Correct the order, add icons and combine actions

The order should be this instead, and 
* Share link (with icon)
* Favorite (with icon)
* Open with | Send
* Move | Copy
* Rename
* Details
* Delete (always needs to be the last action, and with icon)

Update file should be removed – a file will be updated when opened.

edited by @jabarros

- [x] Create 'reorder_menu_items' branch from master in android repository @jabarros
- [ ] Merge 'reorder_menu_items' branch into master
- [x] Change the order of menu items @jabarros
- [x] Check if all menu items has associated icon @jabarros 
- [x] Create test plan @jesmrec
- [ ] Validate test plan @jesmrec
- [x] Text in toolbar for "SEND" and "DETAILS" https://github.com/owncloud/android/issues/1144#issuecomment-248579686 @jabarros

**Comment by AndyScherzinger** [comment] 2015-09-08 11:19
Hi @jancborchardt 

two questions for further details/clarification
* should all items get an icon (I would recommend that)
* How can the actions be combined, since move and copy as well as open with and send trigger different actions?

**Comment by jancborchardt** [comment] 2015-09-08 11:21
Not all items need an icon. I would actually say since it’s soo many actions, only the important actions (Share, Favorite, Delete) should get an icon.

Regarding combining: Can actions not be put on the same row, by splitting the row somehow? The Chrome and Firefox settings menu achieve that.

**Comment by AndyScherzinger** [comment] 2015-09-08 11:32
That would be a bit complicated but possible.

The actual implementation uses the menu definitions and renders a simple list. If we want to have a layout in the way you described it we would need to create a new layout (move from a list to a grid I guess).  At a future point in time I would recommend to move favorite into the item layout to be able to set/unset it there.

**Comment by jancborchardt** [comment] 2015-11-08 22:07
An example of a file manager which includes icons in the action menu is [Cabinet](https://play.google.com/store/apps/details?id=com.afollestad.cabinet&hl=en):
![](https://lh3.googleusercontent.com/R7f2vCwYFbP9yDWsrmZBhDvtcIB1S9ewaHpzCpzDptG-hvvqj9MLbXLTTiqqA6g2SDQ=h900-rw)
Icons should be there only for Share, Favorite and Delete – as said above to keep the focus on them.

**Comment by AndyScherzinger** [comment] 2015-11-09 09:35
I guess that should be an easy (while effort taking) one :) 
* add the respective icons
* create a new layout for the line items (icon + text)
* create an adapter to file the list view

So it is some work but if one knows its way around Android UI code it is an easy one (thus also labeling it junior job).

Should we then split the issue?
* icons for Share, Favorite and Delete (should these then be the top three, since it might look weird if the icons are popping up every now and then within the list)?
* custom layout as discussed in this issue

I'm unsure about the second issue with the custom layout since it  moves away from the standard Android menu layouting and thus might be tricky to implement especially when we move on to the three-dotted menu icon within the list items (which of course would be the right thing to do for UX and performance reasons) :smile:

**Comment by jancborchardt** [comment] 2015-11-09 10:55
> * icons for Share, Favorite and Delete (should these then be the top three, since it might look weird if the icons are popping up every now and then within the list)?

No, Delete should _always_ be the very last action. Share and Favorite need to be the first 2.

> * custom layout as discussed in this issue

Yeah, that’s probably the biggest thing. I’d say we start by simple reordering, bringing Delete to be the last item, and sort the rest correctly as well.

**Comment by AndyScherzinger** [comment] 2015-11-09 11:45
Ah, then it is three issues... ;)

* reordering
* layout with icons
* completely custom layout as suggested with the two column layout (in case we really want to do this, which might be quite painful to implement talking alignment and positioning which it then dynamically and custom)

**Comment by jancborchardt** [comment] 2015-11-09 12:18
Favoriting could actually even just be the star symbol as a toggle left of the file name. Boom – another row saved! :)

**Comment by jancborchardt** [comment] 2015-11-09 12:19
And Share could be directly on the row to the right, as an element with very low opacity. See the mobile view of the web interface for reference (just make your browser smaller). Then we also don’t need to duplicate the Share function in the long-press menu and it’s way quicker to access.

**Comment by AndyScherzinger** [comment] 2015-11-09 13:19
No 8.2 for me yet (since I *still* have to wait for the web updater to be updated :cry:) Do you have a screenshot for reference? :) (problem with the share is that we already kind of show it twice for the folders 8on the folder and on the right hand side...)

**Comment by AndyScherzinger** [comment] 2015-11-09 13:20
Favorite could be on the right hand side as well (like in the gmail app) also with an action, like you said.

**Comment by supportreq** [comment] 2015-11-09 13:37
can we not have something like dropbox a downward arrow which tells the user that there is a menu..

https://lh3.googleusercontent.com/F-ehG8Y7CnLPFa3-RWAUa9zGrCMDrTvPcA4nQ30ayC46zDUPt7JnyWY08kxNcBbECRs=h900

**Comment by AndyScherzinger** [comment] 2015-11-09 14:14
@supportreq That is what @jancborchardt wants to do with the three dotted icon (which is Androids standrad icon for such things to indicate). Unfortunately you would than still end up with the huge amount of menu items we have right now, which is the sesconds issue Jan wants to change :)

**Comment by jancborchardt** [comment] 2015-11-09 14:39
@AndyScherzinger if we add favorites directly in the list, we should put it left of the file thumbnail like it’s done in the mobile web interface. However I would not add that on top since it just is too much stuff. Share icon and 3-dot-menu is enough.

**Comment by jancborchardt** [comment] 2015-11-09 14:39
(For the first pass at least, we can revisit stuff after that.)

**Comment by jancborchardt** [comment] 2015-11-09 14:39
Initially the 3-dot-icon could just trigger the same menu. Then long-press is free for multiselect.

**Comment by AndyScherzinger** [comment] 2015-11-09 16:57
So where would the 3-dot icon be positioned then? Naturally I would expect it to be on the bottom right. And Yes, as soon as we have this the long press would be free for multi select which would be in line with the actual user's expected behavior :+1:

**Comment by jancborchardt** [comment] 2015-11-09 17:44
The three-dot menu would be on the right, in each row. Just like the 3-dot menu in the mobile version of the web interface.

**Comment by jancborchardt** [comment] 2015-11-09 17:44
Of course a bit grey as to not distract too much.

**Comment by AndyScherzinger** [comment] 2015-11-09 18:01
Gery it is ;) - I would go for the standard grey of Android's icons if that would be fine with you.

**Comment by tobiasKaminsky** [comment] 2015-11-09 20:23
I am unsure if this works fine with the beta version.
I thought that we have talked about adding "three dots" to each line @jancborchardt and decided to not do that as we have multiselect, which works the same way as the gallery3d:
selecting one item: show all possible entries
selecting > 1: show only bulk operating menu entries

**Comment by DougJod** [comment] 2015-11-27 02:11
@AndyScherzinger @jancborchardt 
Are you sure that we don't want icons for all items? It looks incomplete with missing icons:
(the icons are from https://www.google.com/design/icons/)
![screenshot_2015-11-26-18-03-26](https://cloud.githubusercontent.com/assets/15933358/11432722/0901fe3a-9469-11e5-854e-e62716f532e7.png)
![screenshot_2015-11-26-18-02-21](https://cloud.githubusercontent.com/assets/15933358/11432721/08f8281a-9469-11e5-99bf-89840fbb7a7c.png)

**Comment by AndyScherzinger** [comment] 2015-11-27 09:43
In general I leave this decision to the UI expert @jancborchardt 
Taking into account that we want to move to the three dotted menu I wouldn't add icons now and when we move to the three dotted menu we can either go for a standard popo up menu which would be Android standard behavior or create a custom one a suggested by @jancborchardt where icons do make sense but the layout is more advanced in comparison to  "simple" list layout where it is rather it grid like one

**Comment by tobiasKaminsky** [comment] 2015-11-27 16:04
@AndyScherzinger this does not answer the "question" of @DougJod: It looks kind of weird when there are only several icons...
(even with the three dotted menu we can have icons...)

**Comment by tobiasKaminsky** [comment] 2015-11-27 16:16
@AndyScherzinger this does not answer the "question" of @DougJod: It looks kind of weird when there are only several icons...
(even with the three dotted menu we can have icons...)

**Comment by AndyScherzinger** [comment] 2015-11-27 16:56
You are right @tobiasKaminsky my comment was rather a summary of @jancborchardt's original comments where he pointed out that he would like to revamp the popup to a firefox like one with a multi column layout and icons only for some actions. 
For the icons you are absolutely right and depending on the remaining actions we could probably have icons for all of them and rather use for icons as the main visualization of the action instead of text :)

**Comment by DougJod** [comment] 2015-11-27 22:25
I do like the FireFox menu. It uses a combination of a multi-colum layout (for icons without text) and a simple list (for text). Maybe we can combine the 3 icons; Share, Favorite and Delete into a single row without text, then put the rest of the text options in a simple list? I'll post a mock-up screenshot in a few minutes...

**Comment by AndyScherzinger** [comment] 2015-11-27 22:59
@DougJod I think @jancborchardt described how he would prefer this to be implemented here: https://github.com/owncloud/android/issues/1144#issue-105352328

**Comment by DougJod** [comment] 2015-11-27 23:29
With the FireFox menu (below) it looks like they have all the 'multi-column' icon rows at the top, then just a simple list of text items, some of which are grouped (Page & Tools) and one with the checkbox option.

I'm not sure how to combine text items midway through the list (Move|Copy) & (Open With|Send), especially since 'Open With' is only visible with downloaded files, but I'll work on it.

@jancborchardt : do you think it's ok to have the 3 icons (including Delete) across the top? I know you mentioned that Delete should be last. There is a confirmation dialog before a file is deleted, which should prevent accidental deletions.

![screenshot_20151127-150445](https://cloud.githubusercontent.com/assets/15933358/11448905/c1924b6c-9518-11e5-8b5a-d6462cd35b14.png)

**Comment by DougJod** [comment] 2015-12-07 17:43
Sorry, I've been working on another project and haven't had time to follow up on this yet.
I don't know a way to mimic this FireFox menu without building a custom dialog with fixed (non menu driven) fields. The FireFox menu is a global options menu, which has built in behavior for showing items as icons (via the showAsAction attribute) and also dynamically handling the menu item grouping and overflow onto the action bar. Since we are using a context menu, the showAsAction attribute doesn't make sense.

If we build a custom dialog, then we can design it exactly as @jancborchardt described, but that means not using menu items. I can work on this, but I'd like to have a consensus decision to proceed this way before I spend time on it. My thoughts are that we should stick with a standard context menu and show icons for all items, as this is simple to implement and easy to maintain. 

@jancborchardt @AndyScherzinger @tobiasKaminsky : Your thoughts?

**Comment by AndyScherzinger** [comment] 2015-12-08 08:51
I would also stick with the standard menu for now especially since we might have to rethink it again when we move to a three dotted menu icon per entry which usually triggers a popup menu.

**Comment by supportreq** [comment] 2016-05-18 14:14
@AndyScherzinger are we looking at implementing a small three dots button next to each file/folder like dropbox to display the context menu..

**Comment by AndyScherzinger** [comment] 2016-05-18 14:29
@supportreq yes, but at the moment it is still in discussion - see  #1396 and it is also to some extend related to the not yet released multi select functionality @jancborchardt and @tobiasKaminsky are also part of this discussion.

**Comment by jancborchardt** [comment] 2016-06-08 09:38
Oh, I thought I commented here. I actually like the last mockup by @DougJod – sure we would have to adjust the exact color and sizing, but it’s good that the 3 most important functions (Favorite, Share, Delete) are emphasized and easily findable. @DougJod as additional input, of course these functions should not be duplicated in the list. :)

Whether we do it like that, or by adding icons in the list to only the important actions – it’s important we somehow highlight the most-used ones. Currently it’s a mess of a list.

**Comment by AndyScherzinger** [comment] 2016-06-08 10:20
Yes, the last mockup would work with the additional comments by @jancborchardt while it would have to be defined what "most-used ones" means. Is it a static defined list of actions like the three seen in the mockup or a dynamic list of three actions based on the usage hit count for each action. For starters I would go for a fix set of three defined actions.

**Comment by jancborchardt** [comment] 2016-06-08 10:42
@AndyScherzinger yeah, for a start we should go for a fixed set. In the future we can make it a learnable UI. Like Android actually does with the sharing function in Gallery, and Firefox, where the most used share function (Signal, Bluetooth, Skype etc) is actually directly shown next to the share icon for quick access.

**Comment by AndyScherzinger** [comment] 2016-06-08 11:55
Yeah, sounds good to me :)

**Comment by jabarros** [comment] 2016-09-20 07:56
Menu items have been reordered as we can see in the following image. 

On the other hand, since we have the multiple selection, to have a menu (on the right) per file, I think it makes no sense.

![device-2016-09-20-095443](https://cloud.githubusercontent.com/assets/1561821/18661922/47b48734-7f18-11e6-8ac8-ac8a379a17d6.png)

**Comment by jabarros** [comment] 2016-09-20 10:36
@jesmrec, available on #1812

**Comment by jesmrec** [comment] 2016-09-21 11:05
@jabarros 

In tablets (5,5  inches or higher), the option "SEND" is displayed as text in the toolbar. I suggest not to set text for options that do not have icon with ifRoom.

The same case happens when a file is sync with the option "DETAILS"

**Comment by jabarros** [comment] 2016-09-21 14:35
@jesmrec, as you say, it is not cool to display the text instead of an icon, so, as we talked, icons for both ("send" and "details") items have been added. You can test it :)

**Comment by jesmrec** [comment] 2016-09-21 16:13
Approved. New order in the actions menu, and items added to `Send` and `Details`options correctly.

Thanks everybody involved.

**Comment by davivel** [comment] 2016-09-26 09:23
Merged.

**Closed by davivel** 2016-09-26 09:23 UTC
Labels: approved by qa, Design, enhancement, Junior Job
