### ISSUE TITLE
[BUG] Mobile app struggling showing files when there are too many

### ISSUE THREAD

**Issue by azukaar** [owncloud/android#3546] opened 2022-02-03 16:05 UTC
### Actual behaviour
Mobile apps is showing a wrong file structure on bigger folders 
This is what the mobile shows in the Owncloud folder :

![image](https://user-images.githubusercontent.com/7872597/152380049-0b0a928f-edc8-4a9a-bf3b-b735b9485bf1.png)

This is what I actually have (taken from web app):

![image](https://user-images.githubusercontent.com/7872597/152380153-db23d352-be30-4f51-8611-3cc339b2d2a0.png)

### Environment data
Android version: 11

Device model: Fold 3

Stock or customized system: No

ownCloud app version: 11368

ownCloud server version: 10.9.1.2

**Comment by jesmrec** [comment] 2022-02-04 07:58
The screenshot is taken from the document provider, right? not from the app itself.

file structure, you mean the order?

**Comment by azukaar** [comment] 2022-02-04 14:09
> The screenshot is taken from the document provider, right? not from the app itself.

Yes correct, this is when trying to access the folder from an app using the document provider

> file structure, you mean the order?

if you look at the files in the document providers, some of them are duplicated, and some of them are missing (or may be just the missing ones are named wrongly like other files)

**Comment by abelgardep** [comment] 2022-02-07 07:52
Hi @azukaar, could you post a video to check the exact steps you are following?

Do you have this issue with the latest version in GPlay? https://play.google.com/store/apps/details?id=com.owncloud.android

Thanks in advance 👍

**Comment by azukaar** [comment] 2022-02-08 11:25
Hello !

> Hi @azukaar, could you post a video to check the exact steps you are following?

Not sure what you mean by that, I am just using any app, "Open File"'s function, and going into the OwnCloud folder

> Do you have this issue with the latest version in GPlay

Yes with 2.19

**Comment by jesmrec** [comment] 2022-02-09 09:42
is this effect also visible in the app? (not only in the document provider)

**Comment by azukaar** [comment] 2022-02-09 19:25
Good point actually yes in the app it is broken too:

![Screenshot_20220209-192502_ownCloud](https://user-images.githubusercontent.com/7872597/153275316-722e0604-1eb0-4543-9944-513834d77308.jpg)

**Comment by jesmrec** [comment] 2022-02-11 09:35
The incoming 2.20 version will include some protection against duplication. We'll ping you when it is out to do another check.

**Comment by azukaar** [comment] 2022-02-11 15:07
I think this is not just duplication, because here the "duplicated" files' metadata are *overwritting* actual files that become unaccessible

**Comment by abelgardep** [comment] 2022-10-06 09:07
@azukaar We have released a new beta: 3.0 beta 1. Let us know if you still reproduce this issue. We have changed its functionality internally 👍

**Comment by abelgardep** [comment] 2023-01-25 12:21
I'll close this issue, feel free to reopen it if the problem is still reproducible with v3.0.1 👍

**Closed by abelgardep** 2023-01-25 12:21 UTC
Labels: Needs info, New architecture
