### ISSUE TITLE
Sync of offline made pictures does not work

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2460] opened 2019-02-24 12:00 UTC
When you made pictures offline, the sync waits for ever to sync. 

> Waiting for WiFi connectivity

I expected an auto start with Wifi or with 15 minutes periodical sync job

![image](https://user-images.githubusercontent.com/3314607/53298896-2ca55b80-3834-11e9-86a2-30b9368d3da0.png)

### PRs: 
- App: https://github.com/owncloud/android/pull/2679

**Comment by davigonz** [comment] 2019-02-28 07:57
So the steps to reproduce here are: 

1. Disable wifi connection.
2. Enable camera uploads.
3. Take a picture.
4. Wait 15 minutes so the new picture is detected and enqueued 
5. Enable wifi

Is this correct? Thanks

**Comment by hannesa2** [comment] 2019-03-04 21:29
This is the right order :
1. Enable camera uploads.
2. Disable wifi connection.
3. Take a picture.
4. Wait 15 minutes so the new picture is detected and enqueued
5. Enable WiFi
And pictures are still in wait-for-WiFi-mode

**Comment by rotational467** [comment] 2019-05-01 17:53
Hello,
I can reproduce this problem.  Copying a post I made to the user forums earlier regarding this.

**Actual behaviour**
With Photo auto-upload on WiFi only enabled, photos taken while not on WiFi coverage do not automatically upload after returning to WiFi coverage.

**Expected behaviour**
The app should detect the presence of/switch to WiFi, and trigger the upload queue automatically.

**Steps to reproduce**
1 . Install OC client and enable Auto-Upload photos on Wifi only. Test and validate this works on WiFi.

2. Leave/Disable WiFi coverage and take a new photo. Within 15 minutes it will appear in the upload queue as expected, with the “Waiting for WiFi” status.

3. Return to WiFi coverage. Items in the upload queue will remain in “Waiting for WiFi status” for at least 24 hours. The “Retry failed” option will trigger the uploads, which complete successfully. The app will then usually crash (note - the app seems to be extremely crash-prone when there are items queued in the Waiting for WiFi status while WiFi is enabled).

**Can this problem be reproduced with the official owncloud server?**
**(url: https://demo.owncloud.org, user: test, password: test)**

Yes. Validated auto-upload on wifi. No auto-upload to demo server 20+ minutes after returning to WiFi. App crashed while browsing upload queue.

Auto-upload to demo server triggered after app auto-restart from crash.

**Environment data**
Android version:
8.1.0 Dec 5 2018

**Device model:**
Nexus 6P

**Stock or customized system:**
Stock

**ownCloud app version:**
2.10.0 release 6d34130f8

**ownCloud server version:**
10.1.1

**Comment by sid3windr** [comment] 2019-07-21 11:27
Same problem here - this is not being fixed? It's pretty basic functionality. And indeed while it's uploading if you're looking at the queue, the app just crashes and restarts.

**Comment by hannesa2** [comment] 2019-07-23 05:37
@sid3windr 
I total agree to you about basic functionality.
But see it positive, a half a year ago, even sync on Android P was not working at all. 
But now, they are on __a good way__ and modernize the app. 👍 

In my point of view any bug fixing makes no sense now, till they merge this "new architecture" stuff

Btw, please can you post the crashes log ?

**Comment by hannesa2** [comment] 2019-10-04 14:50
Here is a attempt to fix it https://github.com/owncloud/android/pull/2679

**Comment by jesmrec** [comment] 2019-11-25 09:23
Merged. Ready to 2.14.

**Closed by jesmrec** 2019-11-25 09:23 UTC
