### ISSUE TITLE
[Feature Request] Folder uploading 

### ISSUE THREAD

**Issue by tapir** [owncloud/android#1597] opened 2016-04-08 08:45 UTC
### Expected behaviour
We should be able to upload complete directories.

### Actual behaviour
You can only upload files.

### Steps to reproduce
1. Press upload button.
2. See that there is no "Folder" option

### Environment data
Android version: 5.1.1
Device model: LG G2
Stock or customized system: CyanogenMod 12.1
ownCloud app version: Latest
ownCloud server version: 8.2.3

**Comment by tobiasKaminsky** [comment] 2016-04-09 14:57
This should be done recursive.
If there are more than 30 files to upload the app should show a warning?
@jancborchardt

**Comment by tapir** [comment] 2016-04-09 19:41
I don't think it should show a warning. Uploading a folder is an explicit action done by the user. User is already aware of the consequences.

**Comment by tobiasKaminsky** [comment] 2016-04-09 19:44
I am not sure if all users are aware that the upload is recursive and not expect to only upload the chosen folder and its content without subfolders.

**Comment by tapir** [comment] 2016-04-09 20:02
Frankly, I'm against assuming that the user is stupid. That method only ends up with overly dumbed down apps.

**Comment by tobiasKaminsky** [comment] 2016-04-09 20:07
Ok :)
It was just an idea, but hopefully you are right and I underestimate the users ;)

**Comment by jancborchardt** [comment] 2016-04-10 11:59
In this case we could assume that people know it’s recursive.

**Comment by wranger** [comment] 2016-05-04 06:44
And what is with folder downloading?

I created a nice folder with a lot of mp3 on my PC, now I have to select every single mp3 to download it, and after that it begins to play.  That sucks

**Comment by jancborchardt** [comment] 2016-05-04 12:38
@wranger long-click a folder and choose download/sync.

**Comment by tobiasKaminsky** [comment] 2016-05-07 07:10
Duplicate of #645

**Closed by tobiasKaminsky** 2016-05-07 07:10 UTC
Labels: enhancement, uploads
