### ISSUE TITLE
Unable to log on from Android client

### ISSUE THREAD

**Issue by ldesousa** [owncloud/android#1291] opened 2015-11-18 11:01 UTC
I have an OwnDrive account to which I sync with the ownCloud client from various Linux systems. About one year I installed the client on an Android device to sync with this same account but I was unable to log in, always receiving the error message "Please enter valid details". I tried changing my OwnDrive password but the problem remained. Back then, various other users reported the same issue in  the Forum:
https://forum.owncloud.org/viewtopic.php?f=24&t=24242

Since then I have accessed my OwnDrive account with the Android device web browser. But now I would like to sync my calendar across all my devices. I installed the client again but it is still impossible to log on.

### Expected behaviour
The client should log on to the OwnDrive service since the credentials provided are correct.

### Actual behaviour
The client yields the message: "Please enter valid details" and does not log on. 

### Steps to reproduce
1. Install the ownCloud client
2. Request log on to the OwnDrive account

### Environment data
Android version: 4.4.2

Device model: Samsung Note 10

Stock or customized system: customised (Samsung)

ownCloud app version: 1.0

#### ownCloud log (data/owncloud.log)
How do I get this in Android? With a desktop Linux it is just a matter of using the -l option, but what about Android?

**Comment by AndyScherzinger** [comment] 2015-11-18 14:45
Looking through the comments in the forum you all get the same error (message) but it is unclear from a technical point of view if the source of the problem is the same or what the problem might be.

Please use the template https://raw.github.com/owncloud/android/master/issue_template.md
Otherwise there is a lot of important information missing.

Things I can think of that might be important here besides the ones mentioned in the template:
* http or https
* ip v4 or ip v6 (might be difficult to answer)
* wifi or cellular connection
* any special characters in the username or password? (e.g. german umlaut)

As to the other question, the owncloud android app doesn't offer any calendar sync, just a general file sync.

**Comment by ldesousa** [comment] 2015-11-18 15:14
My apologies for forgetting about the template, I edited the first comment accordingly. My answers to your questions go below:

    http or https
The error occurs with both protocols.

    ip v4 or ip v6 (might be difficult to answer)
How can I check this? I am not that savy on Android.

    wifi or cellular connection
WiFi

    any special characters in the username or password? (e.g. german umlaut)
There is just an exclamation mark

I am not looking for any application specific sync, file sync is enough for me.

**Comment by AndyScherzinger** [comment] 2015-11-18 15:25
Pinging @davivel @masensio @tobiasKaminsky 

* can the exclamation mark be a problem for Android?

@ldesousa 
* can you retry with the actual Android app version 1.8.0 (play store or f-droid)
* not sure how you can check ip4/ipv6 but I think some users reportedly have problems with the different versions there
* does it work on any other Android device (which would point to the Android version being a possible source)

Thanks for the further information this hopefully helps closing in on the source of the problem! :+1:

**Comment by tobiasKaminsky** [comment] 2015-11-18 16:16
Tested it with password "test'123" and it worked...

**Comment by ldesousa** [comment] 2015-11-19 09:42
It seems this was all an issue with F-Droid, the full story goes below.

Since the client I had install was so old I requested an upgrade from F-Driod, but it did not found any. I then removed the ownCloud client manually and went back to F-Droid to get it re-installed. When I selected install F-Droid would simply answer back with "not installed".

I then went to the Play Store to install ownCloud from there. But the Play Store actually asked money for it :s This looks mighty suspicious....

Over at the F-Droid web site I confirmed that indeed ownCloud 1.8 is available; why was F-Droid not picking it up? It turns out F-Droid itself was reporting a very old version (0.73), for some reason it had been failing to update itself...

I then removed F-Droid manually and re-installed it from the web site (now I have version 0.96). With this new version I was able to install ownCloud 1.8 and with it log on to my OwnDrive account.

I let you decide if this issue should be closed or not. And thank you for the guidance,

**Comment by AndyScherzinger** [comment] 2015-11-19 10:02
@ldesousa thank you for the feedback. Since the issue is resolved I would close this issue. As for the Play store pricing, that is the decision of ownCloud Inc. to ask for some money on the Play Store to help finance the further development of the Android a and all other parts of the platform since ownCloud has some developers on its pay roll to work on the products. So the decision is to ask for some money on the Play store and offer is via f-droid for free as an alternative.
Even though it is open source it is nevertheless legit to put a price tag on it ;)

**Closed by AndyScherzinger** 2015-11-19 10:02 UTC
Labels: Needs info
