### ISSUE TITLE
Upload Folders incl. subfolders all at once

### ISSUE THREAD

**Issue by hitam4450** [owncloud/android#1005] opened 2015-06-08 18:36 UTC
Hi,

it would be very smart & helpful to be able to upload folders incl. subfolders all at once incl. options : 
overwrite to all or single, 
only upload changes

regards, hitam4450

**Comment by masensio** [comment] 2015-06-18 07:28
Duplicate of https://github.com/owncloud/android/issues/735

**Closed by masensio** 2015-06-18 07:28 UTC
Labels: duplicate, enhancement, uploads
