### ISSUE TITLE
Instant upload doesn't check wifi on every upload file start

### ISSUE THREAD

**Issue by Siggi0904** [owncloud/android#1305] opened 2015-11-23 10:21 UTC
I've activated instand photo upload only on wifi. If I connect back to wifi, the app starts with upload.

But if the wifi connection where lost and some pictures have to be uploaded, the app uses the mobile connection to upload.

Looks like, that the app doesn't check the wifi connection on every picture or video on start upload.

**Comment by AndyScherzinger** [comment] 2015-11-23 13:51
Hi @Siggi0904 - thanks for reporting this, imho it seems to be a duplicate of #1166 so I would close it if that is fine with you and the other issue is covering this in your opinion.

**Comment by Siggi0904** [comment] 2015-11-23 14:47
Hi @https://github.com/AndyScherzinger - yes it's ok.
Do you know when this bug is fixed? Next stable version?

**Comment by AndyScherzinger** [comment] 2015-11-23 16:34
It is part of this change: #1191

Unfortunately I don't know when this will be release. This would be a question for @davivel or @rperezb but as far as I know it will most likely not be in the next release since the core team is working hard on a new share feature and the strategy is to release new versions basically around every three month and right now they are close to the new release.

**Comment by LukeOwncloud** [comment] 2015-11-23 17:27
Closing due to duplicate of https://github.com/owncloud/android/issues/1166.

@Siggi0904 Milestone 1.9.1 https://github.com/owncloud/android/milestones/1.9.1-next is all about uploads. Maybe it'll be included already then...

**Closed by LukeOwncloud** 2015-11-23 17:27 UTC
