### ISSUE TITLE
[FEATURE REQUEST] Screenshots prevented

### ISSUE THREAD

**Issue by jnweiger** [owncloud/android#3772] opened 2022-10-05 12:24 UTC
ownCloud android 2.21.2 does not allow me to do screenshots.
I get this message:

Screenshot konnte ncht gespeichert werden
Die App der deine Organisation lässt das Erstellen
von Screenshots nicht zu

Usecase:
- QA needs to do screenshots when discussing GUI elements.

**Comment by abelgardep** [comment] 2022-10-05 17:38
Hello @jnweiger, could you give us some more info? Is it a branded version or you can reproduce it with the Google Play version?

Disallowing screenshots is a branded option. 

So if you are using a branded app that disallowed the screenshots, it's a feature.
If you are using the Google Play version, it's a bug.

Let us know 👍

**Comment by michaelstingl** [comment] 2022-10-06 06:40
@jnweiger what exact screen? Only the login screen? I think that's a security feature. Isn't there an entry in the settings to disable it?

Blocking all other screens too is a branding option.

**Comment by abelgardep** [comment] 2022-10-06 07:38
> Only the login screen? I think that's a security feature.

As @michaelstingl said, login is protected against screenshots. So it's working as expected

**Comment by abelgardep** [comment] 2022-10-13 06:19
Let's close this issue since it's the expected behavior. Login, passcode, pattern screens are protected against Screenshots for security 👍

**Closed by abelgardep** 2022-10-13 06:19 UTC
Labels: Feature request
