### ISSUE TITLE
Android client crashed when scrolling

### ISSUE THREAD

**Issue by bremenpl** [owncloud/android#905] opened 2015-03-02 08:07 UTC
Hello there,
I am using the Android Owncloud client in lastest available on the google play version (1.7.0). I am using Samsung s3 with Cyanogen 11. I have a folder it owncloud where I have over 700 pictures. When I enter that folder in the android client and start to scroll through the pictures fast, the app crashes.

**Comment by tobiasKaminsky** [comment] 2015-03-02 09:37
Could you please append a logcat log, as with this description there is unfortunately no way to figure out the real reason...

**Comment by bremenpl** [comment] 2015-03-02 09:38
I can append anything, but I dont know where to find this log.

**Comment by tobiasKaminsky** [comment] 2015-03-02 09:44
http://wiki.cyanogenmod.org/w/Doc:_debugging_with_logcat
https://play.google.com/store/apps/details?id=org.jtb.alogcat&hl=de
Logcat provides nearly all debug messages we need to determinate the root of the crash.

**Comment by bremenpl** [comment] 2015-03-02 20:54
I have downloaded this tool and tried to record the crash. But there was no 
ibfo about it in the log. I tried switching log levels.

**Comment by shoeper** [comment] 2015-03-02 22:21
Is it in a folder containeding images?
I've the same in folders containing many images I get outofmemoryerror

**Comment by tobiasKaminsky** [comment] 2015-03-03 07:41
> Have also sent multiple reports to gplay - maybe the devs get them and could put the erros on github.

@davivel Is there a  way to get those reports intergrated here in github?

**Comment by skymania** [comment] 2015-03-13 09:31
Same issue here. Log cat when it crashes: 

03-13 10:30:03.406    2480-2480/com.owncloud.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.owncloud.android, PID: 2480
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:620)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:634)
            at com.owncloud.android.ui.adapter.DiskLruImageCache.getBitmap(DiskLruImageCache.java:123)
            at com.owncloud.android.datamodel.ThumbnailsCacheManager.getBitmapFromDiskCache(ThumbnailsCacheManager.java:134)
            at com.owncloud.android.ui.adapter.FileListListAdapter.getView(FileListListAdapter.java:286)
            at third_parties.in.srain.cube.GridViewWithHeaderAndFooter$HeaderViewGridAdapter.getView(GridViewWithHeaderAndFooter.java:657)
            at android.widget.AbsListView.obtainView(AbsListView.java:2255)
            at android.widget.GridView.makeAndAddView(GridView.java:1345)
            at android.widget.GridView.makeRow(GridView.java:345)
            at android.widget.GridView.fillUp(GridView.java:386)
            at android.widget.GridView.fillGap(GridView.java:262)
            at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5143)
            at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4254)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:543)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by masensio** [comment] 2015-03-24 08:43
Hi all,

thanks for your feedback.
I think the problem is cause by the caching up thumbnails process, when the folder contains a lot of files the problem is greater. We need to improve this process. I hope to take time for solving this problem soon.

Sorry for the inconvenience.

**Comment by skymania** [comment] 2015-03-24 08:48
Use of ViewHolder and not inflating each View when it is shown, pervents the app from crashing. But there still is IO lag when loading images from disk cache and the scrolling is not a great user expirance. 
Im currently working on reducing this lag with background imageview image swap, but have encountered image flickering as described above.

**Comment by Joriks** [comment] 2015-04-29 22:17
Hello, i have the same issue on v 1.7.0 (with nexus 5 and android 5.1.0) and a similar logcat than @skymania but a bit larger ^^.
https://gist.github.com/Joriks/345b7806d561c5c957a4

**Comment by tobiasKaminsky** [comment] 2015-04-30 05:36
This should be resolved by #955

**Comment by masensio** [comment] 2015-05-07 07:36
Hi @bremenpl, @shoeper, @skymania, @Joriks,

We are working to fix the thumbnails problems
To know if our changes solves this problem, we need a description of this bug, to reproduce it in our tests.
Could you please describe your problem specifying: device, Android version, app version, server version and the steps to reproduce it? Please indicate also the number of files (aprox) that you have in the folder.
You can use the template https://github.com/owncloud/android/blob/master/issue_template.md

**Comment by masensio** [comment] 2015-05-22 06:48
Hi everybody,

we've included some fixes in our develop branch to avoid this crash. 
That update will be available on the next release of the app (1.7.2).

So I close the issue.

**Closed by masensio** 2015-05-22 06:48 UTC
Labels: browse, bug, image
