### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by vsessink** [owncloud/android#2001] opened 2017-07-02 12:35 UTC
### Actual behaviour
Trying to start the app wil result in a message saying: owncloud crashed. Instantupload and file sharing cease functioning as well.

### Expected behaviour
App starts without crashing.
 
### Steps to reproduce
1. Start the app.

Owncloud seems to function again after restarting the phone. However, once the app starts crashing again, it becomes dysfunctional again - I.e. I need to restart the phone for it to function again, there is no workaround.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

(Not sure)

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S6 / SM-G920F

Stock or customized system: stock. May 2017 Samsung update installed.

ownCloud app version: 2.4.0

ownCloud server version: [will check later]

I 'm not sure how to obtain crash logs from android - if there are any.

**Comment by davigonz** [comment] 2017-07-03 12:13
Hi @vsessink , thank you for reporting this problem. Does the crash occur in a specific moment or when you make a concrete action? Are you able to login with no problem?

**Comment by vsessink** [comment] 2017-07-03 12:43
I'm not sure. It could be a race condition and I also wondered if it has something to do with instantupload. After a restart, the app functions as it should, but once it's broken, it stays broken. 

It looks a bit like bug #1950 - but it's different.

I tried to reproduce the problem. Just moving around in the app and / or losing, then regaining network connectivity seems to activate the bug, but I'm unsure why or when exactly it happens. It just happened again: moved around in the app a bit, then decided to do something else - starting ownCloud again made the app crash. And then it keeps crashing.

I'm sending crash information regularly, does that help?

**Comment by davigonz** [comment] 2017-07-04 15:48
Hello @vsessink , thank you for the feedback, can you try to uninstall, install the app again and check if the crash is still there?

**Comment by vsessink** [comment] 2017-07-05 11:05
@davigonz I think I'm a step closer to reproducing the issue.

I've got some 3500 files in InstantUpload, and it takes quite a while for the Owncloud app to refresh the directory. Now as far as I can see, if something changes inside this directory while the app is still refreshing it's content, it will crash. So:
1) have an InstantUpload directory with 3500 photos. Make sure you have the InstantUpload functionality turned on.
2) open your owncloud app and open (i.e. view) the InstantUpload directory.
3) while the app is still refreshing (as can be seen by the moving dots in the upper bar), change to your Camera app and take a picture. I have also experienced that just *removing* a picture on the server will also induce this behaviour. 
4) change back to ownCloud. The app will crash.

Afterwards, the app will keep crashing, i.e. trying to choose "restart app" will result in another dialog box saying that owncloud keeps crashing.

And rather weird: when owncloud is in it's "crashing" state, de-installing it and re-installing it will *still* make it crash. It will do so even before I had the chance to answer the question about allowing owncloud to access local storage and photos. The only thing that helps is restarting the phone. And only *after* I restart my phone, I'm able to enter my owncloud credentials.

So:
1) InstantUpload directory with 3500 photos, have InstantUpload functionality turned on.
2) open your owncloud app and open (i.e. view) the InstantUpload directory.
3) while the app is still refreshing (as can be seen by the moving dots in the upper bar), change to your Camera app and take a picture. I have also experienced that just *removing* a picture on the server will also induce this behaviour. 
4) change back to ownCloud. The app will crash.
5) try to restart ownCloud. It will crash again.
6) try to restart - it will still crash.
7) go to Google Play app. De-install owncloud. Go to home screen.
8) go to Play app, re-install owncloud
9) try to start newly installed owncloud. It will crash. A message about "do you want owncloud to acces local storage" will be visible behind the crash dialog.
10) try to restart owncloud - to no avail.
11) restart phone
12) start ownCloud. It will ask for a server/username/password combination.

**Comment by vsessink** [comment] 2017-07-05 11:14
Oh, btw: I'm not 100% sure if it is necessary to remove/add files while InstantUpload is refreshing. This is how I got the app to crash.

Unfortunately, afterwards, I have to restart my phone so it takes quite some time to try crash the app - a crashing sequence takes about 2 minutes machine time.

I've also got the app to crash while just refreshing InstantUpload without anything uploading. So I'm still unsure about the exact reasons for crashing.

**Comment by jesmrec** [comment] 2017-07-07 08:32
unable to reproduce the problem. Maybe a good idea to try to reproduce the problem with the owncloud beta version, so you can ship us logs about what is happening. The beta is available in F-droid

**Comment by vsessink** [comment] 2017-07-07 15:32
Hi. Unable to reproduce with 2.5.0-beta.1 :-/
I'm not sure what to do - mark the bug "fixed in 2.5"?

**Comment by jesmrec** [comment] 2017-07-07 21:42
your feedback is enough :)

**Comment by davigonz** [comment] 2017-07-12 10:58
I'm glad the beta app has solved the problem @vsessink. I will close this, please reopen it if the crash appears again, thanks.

**Closed by davigonz** 2017-07-12 10:58 UTC
Labels: Needs info
