### ISSUE TITLE
 release-1.8 

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1153] opened 2015-09-14 08:33 UTC
AC:
- Freeze the code and regression test
- Release on the different markets: Google Play, Amazon and Blackberry

NOTE:
- Code will be fronzen on the branch https://github.com/owncloud/android/tree/release-1.8

**Comment by davivel** [comment] 2015-09-15 07:50
I reviewed the contents of the milestones, and updated them according to our last talk. I moved the things that won't get into https://github.com/owncloud/android/milestones/1.8-current to https://github.com/owncloud/android/milestones/1.8.1-next .

cc @MTRichards @cmonteroluque @rperezb @masensio

**Comment by davivel** [comment] 2015-09-16 15:22
The code is finally frozen in the branch https://github.com/owncloud/android/tree/release-1.8 . 

If anybody wants to help in testing, just build the app from that branch and go for it :+1:

Two simple rules for testing in the search for regressions:
  - bugs that didn't exist in version 1.7.2 and exist in the frozen branch are welcome;
  - bugs already existing in version 1.7.2 (known or not) are not the target in this test stage

If you find any bug relevant, create an issue for it in the repository and mention its number in a comment in this thread; @masensio , @rperezb or @davivel will confirm that it corresponds to this testing stage (or doesn't).

If you can fix it - still better! Just make a PR with the fix to the branch https://github.com/owncloud/android/tree/release-1.8 . 

cc @AndyScherzinger due to recent interest, but any help is welcome.

**Comment by AndyScherzinger** [comment] 2015-09-16 16:07
First one found on the login screen (actually rather 3 bugs): #1160

**Comment by AndyScherzinger** [comment] 2015-09-17 09:59
Little update, I added a PR for 1.8 which fixed the two bugs that have been present on the 1.8 branch: #1163 (this also fixes #192 which I didn't see before I already fixed the issue). This is a UI glitch fix now since the crash bug wasn't present on 1.8 but my open PRs for post 1.8.

Thus this doesn't need to be fixed but since it is a simple xml fix you might consider merging it, since it fixes a 2,5 years old UI glitch :grinning:

**Comment by masensio** [comment] 2015-09-28 16:56
Hi @all,

this release is available in the market. Enjoy it!

So I'll close the issue :)

**Closed by masensio** 2015-09-28 16:56 UTC
Labels: 3 - Done

**Comment by AndyScherzinger** [comment] 2015-09-29 08:18
Woohoo! Nice work everybody and a big thank you for having me! It is great to be a part of this release!

**Comment by rperezb** [comment] 2015-09-29 12:12
such a great team work!

**Comment by tobiasKaminsky** [comment] 2015-09-29 18:09
Great :)
Looking forward to all the positive comments ;)
