### ISSUE TITLE
Feature Request: Fingerprint Access

### ISSUE THREAD

**Issue by cdamken** [owncloud/android#1462] opened 2016-02-05 11:02 UTC
Instead to use the `passcode lock`, I would like to have the fingerprint access function.

The interest here is that anybody can hack the key, but the fingerprint is unique. 

@MTRichards 

00004644

___

TASKS

- [x] [GIT] Create fingerprint_lock branch. 
- [X] [RESEARCH] 
- [X] [DEV] Include new Fingerprint lock in Details section of Settings view. 
- [X] [DEV] Add Fingerprint Permission to the manifest File.
- [X] [DEV] Design Fingerprint dialog. 
- [X] [DEV] Implement Fingerprint lock behaviour. 
- [X] [DEV] Handle Passcode lock along with Fingerprint.
- [X] [DEV] Ensure Passcode lock is enabled before allowing the user to enable Fingerprint lock.
- [X] [DEV] Disable option for Android < 23 and devices which do not support fingerprint.
- [x] [DEV] Grant permissions.
- [x] [DEV] Integrate with just recently included pattern lock feature.
- [x] [QA] Design test plan @jesmrec
- [ ] [QA] Execute test plan @jesmrec [WIP]
- [ ] [GIT] Merge branch fingerprint_lock into master.

**Comment by AndyScherzinger** [comment] 2016-02-05 12:14
cross referencing to earlier issue ##1323

**Comment by MTRichards** [comment] 2016-02-05 16:28
Please add a SF ticket reference and any STORY info you have  and can show so we can discuss.

**Comment by cdamken** [comment] 2016-02-06 14:06
The SFDC ticket is mention above

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.91&pv=5.1.1&source=email_footer_2] On Fri, Feb 05, 2016 at 5:30 PM, MTRichards < notifications@github.com [notifications@github.com] > wrote:
Please add a SF ticket reference and any STORY info you have and can show so we
can discuss.

—
Reply to this email directly or view it on GitHub
[https://github.com/owncloud/android/issues/1462#issuecomment-180429293] .[https://github.com/notifications/beacon/AG7Y702ZJydvPUNMQVniah3XOqtU9UyQks5phMVCgaJpZM4HUL8H.gif]

**Comment by davivel** [comment] 2016-02-24 18:05
Very important the reference in #1323 from @Querschlag . Thanks, @AndyScherzinger , for the link.

**Comment by AndyScherzinger** [comment] 2016-02-25 09:50
@davivel would you rather head for the high level library or our own implementation based on the slightly lower level Google API? :)

**Comment by davivel** [comment] 2016-02-25 17:32
I'd prefer the high level library, but maybe it's not feasible; in our case the password fallback should be the current passcode Activity, just took a fast look to the lib, but if it's handling itself the password dialog I wouldn't expect a soft integration.

**Comment by codedsun** [comment] 2018-02-05 12:57
@davigonz I want to work on this issue.

**Comment by davigonz** [comment] 2018-02-05 13:28
> I want to work on this issue.

Great, ping me if you have any question or need any pointer to our code.

**Comment by codedsun** [comment] 2018-02-05 13:47
@davigonz I want to ask, that how the following will go.

1.Like the user clicks on the android fingerprint choice and then he will navigate to which choice?

2.(i) he has to confirm the choice by confirming his finger and then the choice will be made.
2.(ii).or the choice will be confirmed and the next time the app is opened, the fingerprint activity is shown.

Next, can two locks be chosen simultaneously?

**Comment by cdamken** [comment] 2018-02-05 13:59
It would be nice if the application can be locked with the fingerprint.

**Comment by codedsun** [comment] 2018-02-05 14:10
@cdamken That means that it will follow step2(i) or step2(ii)?

**Comment by davigonz** [comment] 2018-02-05 14:32
@codedsun Once the user presses the **Fingerprint lock** option, he will be asked for configuring the fingerprint and after that, the fingerprint will be required by the ownCloud app when it is resumed after closing or killing it.

In this case, we could follow the same approach as Android system itself, I mean, a different lock (passcode or pattern) is necessary before configuring Fingerprint, just in case fingerprint access is not successful.

**Comment by davigonz** [comment] 2018-02-05 14:32
Sorry, wrong button

**Comment by codedsun** [comment] 2018-02-06 18:59
@davigonz To implement this further I want to ask that when the user presses the Fingerprint Lock option, then what screen(UI) has to be shown? For eg: 
<img src= "https://www.androidhive.info/wp-content/uploads/2016/11/android-fingerprint-authentication-sign-in.png" />

Do we need such UI and can u guide me more as the above point is not clear to me enough.
Like, the user clicks fingerprint option then he validates the option/choice by placing his fingerprint and then the choice is confirmed.

Next, I asked that we have pinlock availaible in owncloud app, hence can we make 2 locks availaible at the same time in the app that means the user chooses both the option of pinlock and fingerprint lock.

**Comment by davigonz** [comment] 2018-02-07 09:54
@codedsun The fingerprint is stored in the Android system so **you wouldn't need to ask for confirming the choice or configuring the fingerprint**, I've just updated my previous comment. 
If the user doesn't have the fingerprint in his device yet, a error message would appear saying something like "To enable the fingerprint lock you should configure your fingerprint in your device". 

Besides, you have to take into account that **the Passcode lock needs to be enabled before the user enables the Fingerprint lock**, it's up to you the way to show the the Fingerprint lock option when Passcode lock is still disabled, e.g. a message could appear when the user tries to enable the Fingerprint lock and the Passcode lock is still disabled, saying something like "To enable Fingerprint lock you will need to enable Passcode lock first".

When **Fingerprint lock is enabled, you will have to show the Passcode lock view behind the dialog asking the user for introducing the fingerprint**. That dialog will contain a cancel button so that the user is able to use the passcode as well. 

Hope with this you have the enough information to start, if not, please ask me again.

**Comment by davigonz** [comment] 2018-02-07 09:56
@codedsun Instead of the dialog I suggested above, you could also use your "One touch sign-in" view, with a small option that says "use passcode".

**Comment by codedsun** [comment] 2018-02-07 17:34
@davigonz I am not able to figure "One touch sign-in" view? Can you tell me about that and tell me your location/gmt so that I can sync.Can u drop ur email/ any chat channel suitable for conversation.?

I am setting up the server still :( because the demo ones expire and widout it I am not able to make a walkthrough and debugging every time.
Thanks for the help.

**Comment by davigonz** [comment] 2018-02-09 09:36
> I am not able to figure "One touch sign-in" view? 

@codedsun "One touch sign-in" view is the one you attached in https://github.com/owncloud/android/issues/1462#issuecomment-363528048. What I meant is that you can use the dialog I explained in https://github.com/owncloud/android/issues/1462#issuecomment-363715728 or just use that view, with an option that says "use passcode".

> Can you tell me about that and tell me your location/gmt so that I can sync 

GMT +1, Spain 🇪🇸 

> Can u drop ur email/ any chat channel suitable for conversation? 

I would prefer discuss about the topic here, so anyone can keep up with the issue. If we see that we need talk about it privately, I will give you my email, no problem.

**Comment by codedsun** [comment] 2018-02-09 17:58
@davigonz  I couldn't move forward until I get the server ready :( hence trying to set up server asap!

**Comment by davigonz** [comment] 2018-02-21 09:32
@codedsun have you finally got the server ready? I would like to start with this but if your server is ready and want to contribute here, let us know.

**Comment by cdamken** [comment] 2018-02-21 11:26
> @davigonz I couldn't move forward until I get the server ready :( hence trying to set up server asap!

I can provide you an account in my server if you want to test.

**Closed** 2018-03-14 16:37 UTC
Labels: blue-ticket, contributions are welcome, enhancement, passcode

**Comment by jesmrec** [comment] 2018-03-14 16:38
Ready to be released in 2.7.0

**Comment by michaelstingl** [comment] 2018-03-14 16:50
Awesome – can't wait to test the beta!
