### ISSUE TITLE
[1.9.0] Can't copy to clipboard while renaming files

### ISSUE THREAD

**Issue by cdamken** [owncloud/android#1401] opened 2016-01-04 16:41 UTC
When we try to rename files with branded 1.9.0 the clipboard functions don't work as expected.

1.- Try to Double tap on the entry in the renaming dialogue (instead of touching a longer time) the function menu is darkened and the symbols doesn't work anymore.
2.- Trying to mark the text add selecting the scissors closes the dialogue.

Problem win Sony Xperia Z3 (Andriod 5.1.1)

1.9.0 Branded client.

I tried to reproduce it with onePlus 2 (5.1.1) 

The 1. was unabled to reproduce (I will ask for more detailed information)

The 2. was reproduced in 1.9.0 Branded and Unbranded client.

@MorrisJobke 
00004488

**Comment by tobiasKaminsky** [comment] 2016-01-04 17:05
I cannot reproduce any of it on Moto X Play with Android 6.
But this is maybe due to the fact that the copy&paste function is fresh implemented.

**Comment by cdamken** [comment] 2016-01-05 10:07
Now I can reproduce the first point (1.-) ;

The app is opened and I am long tapping an file-entry, so I'm getting the menu:
"Share, Open with, Synchronize, Rename....".
A short tap on /Rename/ opens
a bright dialogue box to enter a new filename. The background is getting darker.
Then I'm double tapping on a part of the filename. This part is marked and I'm getting a second menu between the dialogue box and the status bar. But this menu is also darkened and contains symbols for cut, copy and paste. When I'm tapping there to select a function like paste or cut, the dialogue box
closes.

@tobiasKaminsky Do you have a device with 5.1.1? I can repoduce with branden and unbraded versions on my phone.

**Comment by tobiasKaminsky** [comment] 2016-01-05 19:42
No, unfortunately I only have 6.x devices :/

**Comment by MorrisJobke** [comment] 2016-01-08 14:49
cc @rperezb @davivel

**Comment by rperezb** [comment] 2016-01-12 16:42
Just reproduced it, on Android 4.1.2 and 4.3 devices. 
The thing is that the edit menu appears below the rename view so when you select any edit action (copy/cut..) it's detected as cancel action (cancel the rename) so that the view is closed.
Android 6 works fine since the edit menu is above the rename view

**Comment by AndyScherzinger** [comment] 2016-01-12 17:15
@rperezb can you provide 1 or 2 screenshots? Also also only have Android 6 at the moment. Thanks! :)

**Comment by rperezb** [comment] 2016-01-15 10:14
Does this help?

![edit menu](https://cloud.githubusercontent.com/assets/1846927/12350696/f0ed91ba-bb78-11e5-8883-45f2bde7bc4c.png)

**Comment by AndyScherzinger** [comment] 2016-01-17 19:25
Here is the problem... 
https://code.google.com/p/android/issues/detail?id=170105

This means upgrading to AppCompat v23 which means targeting Android v23 which we startet on a branch but it needs a complete reimplementation of the permission Api.   I started with this but it still needs a lot of work.

**Comment by AndyScherzinger** [comment] 2016-01-17 19:26
It'll take some time, unfortunately :(

**Comment by rperezb** [comment] 2016-01-20 10:51
Good catch, @AndyScherzinger !

**Comment by AndyScherzinger** [comment] 2016-01-20 14:57
Thanks @rperezb but like I said this is a very time consuming matter now, since it means moving to v23 with all the consequences described above :disappointed:

**Comment by davivel** [comment] 2016-01-29 09:14
Sorry, but this needs to be moved to next release.

**Comment by davivel** [comment] 2016-02-15 18:52
@AndyScherzinger 's PR was 'relocated' to #1473; almost there.

**Comment by rperezb** [comment] 2016-02-19 10:36
This will be included within the next Android version

**Closed by rperezb** 2016-02-19 10:36 UTC
Labels: blue-ticket, in progress

**Comment by cdamken** [comment] 2016-02-19 19:36
Thanks  @rperezb
