### ISSUE TITLE
Sharing text with ownCloud

### ISSUE THREAD

**Issue by untitaker** [owncloud/android#104] opened 2013-03-06 13:09 UTC
It would be neat if i could share text from my twitter app (or from the sms app) and pipe the text into a new text file on ownCloud.

**Comment by 3dluvr** [comment] 2015-07-22 02:17
Is there an update on this (been over a year), and the functionality is still not working?

What needs to be done to get it to work?

**Comment by strugee** [comment] 2015-07-23 02:04
@3dluvr someone needs to sit down and write the code.

**Comment by davivel** [comment] 2015-07-23 08:19
Right that

**Comment by tobiasKaminsky** [comment] 2015-08-16 13:08
So the workflow would be:
- accepting text as input
- write it to a temporary file
- prompt for a file name
- let user choose storage path

**Comment by torwag** [comment] 2015-08-16 13:49
IMHO, it should be as easy as possible for 90% of all usage scenarios. That is, the settings should allow to set a default path and a file name structure. E.g. \notes\income\  $date-$time-$sending-app-name.
The workflow would go straight to ask the user to save the text by the default settings (single click) and prompt for a file name and path otherwise.

**Comment by tobiasKaminsky** [comment] 2015-08-16 19:09
I do not like the idea of a setting, here.
Maybe just remember the last storage path of txt files (just like it is currently for upload files)

@jancborchardt your opinion here, please!

**Comment by tobiasKaminsky** [comment] 2015-08-16 19:12
ref: https://github.com/owncloud/android/issues/1098#issuecomment-131542181

**Comment by purigarcia** [comment] 2015-08-21 08:14
@tobiasKaminsky , @AndyScherzinger , @LukeOwncloud and whoever feels like, contributions are wellcome here :)

**Comment by AndyScherzinger** [comment] 2015-08-21 10:26
I agree with @tobiasKaminsky I also wouldn't like to see this realized using a setting, an expected behavior like Tobias described with "currently for upload files" seems to be a consistent way imho

**Comment by tobiasKaminsky** [comment] 2015-08-21 11:47
@jancborchardt 
@davivel 
We need your opinion here first :)

**Comment by jancborchardt** [comment] 2015-08-24 12:27
Honestly this seems like a very specific usecase. Doing this properly would be to implement the ability to view & edit text files: #88 – then you can paste stuff and edit it afterwards too.

**Comment by tobiasKaminsky** [comment] 2016-04-16 07:42
@jancborchardt @davivel 
It seems that now some more people would like to have this feature.
So, in order to have someone that can implement this, we should discuss the proper way?

In a first step I would just do this like files: 
An user shares text with owncloud app, selects the folder and then a dialog appears where the filename is entered with automatically extension ".txt" and save.

**Comment by jancborchardt** [comment] 2016-04-17 14:07
Ok, functionality-wise that seems good. :)

**Comment by davivel** [comment] 2016-04-18 12:24
@tobiasKaminsky , :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by tobiasKaminsky** [comment] 2016-05-01 08:18
#1647

**Comment by davivel** [comment] 2017-04-04 07:41
This was resolved with #1926 and will be available in the next release.

Thanks, @cinnamonsalt

**Closed by davivel** 2017-04-04 07:41 UTC
Labels: enhancement, share_Android::receive_files_from_apps, text
