### ISSUE TITLE
Multiselect header glitch

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1434] opened 2016-01-12 13:08 UTC
The multiselect header has a strange horizontal blue line in there.

Also, when multiselecting one file and then going to »Details«, the header is still in multiselect mode. Should be normal though, since in that view there is no multiselection.

**Comment by AndyScherzinger** [comment] 2016-01-12 13:11
the details part is a duplicate of #1412 which shouldn't be a bug in case #1275 gets merged sometime.

**Comment by tobiasKaminsky** [comment] 2016-01-19 21:17
@AndyScherzinger can you help me with the blue horizontal line?
I suspect this comes from the "account update progress bar"?

**Comment by AndyScherzinger** [comment] 2016-01-19 22:39
I can have a look, sure. The glitch should be in part because of the progress bar, but for some reason there is also a part visible from the action bar... Which is weird.

**Comment by AndyScherzinger** [comment] 2016-01-19 23:25
I fixed the coloring bug regarding the light blue line, but of course the dark blue one is still there since that is the progress bar as Tobias mentioned already. In order to properly fix this we would need to move to the toolbar implementation since that one can be customized with additional UI elements been added, but never got it to work properly for drawer/back/home navigation since the fragments seemed to fire two events which irritated the navigation bar's state. So to move to the toolbar which I would love we would need a collaboration with @davivel / @masensio and I am unaware of the time they could spent on tracking toolbar issues regarding fragments.

For review changes on the multi select branch can be found here: https://github.com/owncloud/android/commit/2396355b85a48a5a0394ae2bec68fcdf14887529

So is this fine for now @jancborchardt ? - Please also let me know if the grey color is fine with you :)
![actionmode](https://cloud.githubusercontent.com/assets/1315170/12435152/f7e1e8ea-bf0b-11e5-8e9e-2d63802dea5a.png)

**Comment by AndyScherzinger** [comment] 2016-01-19 23:27
@jancborchardt please ignore the checkboxes, they will be in the new design whenever the branch gets updated to latest master.

**Comment by AndyScherzinger** [comment] 2016-01-19 23:31
I moved from the dark grey to a lighter grey since the dark grey for the action bar coloring since the dark grey would be rather Holo style (Android 4.x) while the light grey is more common in material styleed app, like Gmail.

**Comment by AndyScherzinger** [comment] 2016-01-19 23:49
Screenshot with change merged to the beta branch, running on Android 4.0.x
![device-2016-01-20-004758](https://cloud.githubusercontent.com/assets/1315170/12435732/b25edd06-bf0f-11e5-9229-9cf0bff02227.png)

**Comment by AndyScherzinger** [comment] 2016-01-19 23:52
So for explanation: The action mode hasn't been themed (before my last commit) and the style was Holo based and is now Material style based. So it should be fine, that dark blue line (as in progress bar) should be postponed as mentioned before.

**Comment by jancborchardt** [comment] 2016-01-20 12:51
@AndyScherzinger it seems to be a different grey color than before though, a lighter one?

**Comment by AndyScherzinger** [comment] 2016-01-20 14:21
@jancborchardt exactly! Like I said I have chosen a light one, which seems typical for material design apps (see e.g. Gmail). I will change the coloring a bit and post a new screenshot but would suggest to stay with a light grey instead of a dark one to have a contrasting color for the standard, dark blue.

**Comment by jancborchardt** [comment] 2016-01-20 14:42
I’m not sure, for several reasons:

- seems too much of a contrast to the default dark color
- too much of a contrast to the system bar above it
- too little contrast to the text

Also, there is still this dark line (loading bar?) below the bar which still makes it look strange. Can we get rid of that?

**Comment by AndyScherzinger** [comment] 2016-01-20 14:51
@jancborchardt small optimization I just added for Lollipop and up, also greying out the system bar :smile: 
![device-2016-01-20-154127](https://cloud.githubusercontent.com/assets/1315170/12452175/5ce9aa58-bf8d-11e5-9f31-41a99657615f.png)

Unfortunately getting rid of the progress bar like I said would only be possible when we integrate it into the bar itself and in order to do that we would need to migrate to the toolbar implementation, which I yet failed to get to work properly :(

**Comment by AndyScherzinger** [comment] 2016-01-20 14:54
So, simply said, we cannot get rid of the dark blue line except for one solution I can think of right now which would be to use the dark blue color (system bar and progress bar) when the multi select mode gets activated, so the progress bar then has the same color :wink:

**Comment by AndyScherzinger** [comment] 2016-01-20 14:55
One more thing, the progress bar actually gets animated in some situations (!), when y sync is running and you trigger the mulstiselect at that moment... So still showing the progress (bar) makes sense to me.

**Comment by jancborchardt** [comment] 2016-01-20 15:27
Looks much better now! :) :+1:

**Comment by AndyScherzinger** [comment] 2016-01-20 15:46
W00t!  So can I commit and close the ticket then :smiley: Beware though that the grey system bar is Lollipop and up, since 4.x doesn't support coloring the system bar...

So 4.x would look like this:
![device-2016-01-20-164547](https://cloud.githubusercontent.com/assets/1315170/12453844/55542b9e-bf95-11e5-85b5-18ab53e297a3.png)

**Comment by AndyScherzinger** [comment] 2016-01-20 15:59
commit for the grey system bar coloring: https://github.com/owncloud/android/commit/8b22a06850e42a20ff3c6cb39e9341a480a3a2b1

**Comment by jancborchardt** [comment] 2016-01-20 16:55
Yup, that’s fine. Good work!

**Comment by AndyScherzinger** [comment] 2016-01-20 17:14
Fixed in #1176
related commits:
* https://github.com/owncloud/android/commit/2396355b85a48a5a0394ae2bec68fcdf14887529
* https://github.com/owncloud/android/commit/8b22a06850e42a20ff3c6cb39e9341a480a3a2b1

**Closed by AndyScherzinger** 2016-01-20 17:14 UTC
Labels: Design
