### ISSUE TITLE
auto upload of pictures is broken

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2394] opened 2018-12-08 15:19 UTC
With the current version, it seems the auto sync of pictures is broken. On my device there was nothing synced since months

**Comment by hannesa2** [comment] 2018-12-08 18:10
I did a test on a real device from 15:05 till 18:55

### Problem A:
It seems `CameraUploadsSyncJobService` does not start

```
adb pull /storage/emulated/0/owncloud/log/currentLog.txt .
cat currentLog.txt |grep CameraUploadsSyncJobService

2018/12/08 15:03:20 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService
2018/12/08 15:03:38 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService
2018/12/08 15:03:45 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService
2018/12/08 15:03:50 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService
2018/12/08 15:05:40 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService

```
Looks like L53 is never reached
![image](https://user-images.githubusercontent.com/3314607/49689026-1c29f280-fb1b-11e8-85fb-c9eac1bb62e1.png)

### Problem B:
Last entry at 15:47:47. After this time app seems to stop doing anything in background. No Job started, nothing

### Problem C:
I see a lot of actions in background, but server directory `Kamera-Upload` has still only **one** file instead if > 800 files 
```
status:UPLOAD_FAILED and result:NETWORK_CONNECTION
Socket timeout exception Exception
UPLOAD_IN_PROGRESS and result:UNKNOWN
updateCameraUploadSync returns with: 1
Unrecovered transport exception Exception
```

Does someone understand what's going on. Here is the complete log
[currentLog.txt](https://github.com/owncloud/android/files/2659927/currentLog.txt)

**Comment by jesmrec** [comment] 2018-12-10 07:51
Thanks a lot for reporting. We have had some issues of people who automatic uploads do not work for them. I guess you selected the correct source folder. We will have a look.

**Comment by davigonz** [comment] 2018-12-12 11:33
Thanks for reporting this @hannesa2, in the `currentLog.txt` you attach I see several logs saying `Scheduling a CameraUploadsSyncJobService` in different hours but there's no 15 minutes wait.

`2018/12/08 15:03:20 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService
2018/12/08 15:03:38 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService
2018/12/08 15:03:45 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService
2018/12/08 15:03:50 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService
2018/12/08 15:05:40 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService`

If the `CameraUploadsSyncJobService` is scheduled at 15:03, the job execution should start approximately at 15:18, do you have more logs to see what's going on at that time? Thanks

**Comment by hannesa2** [comment] 2018-12-12 18:12
Sorry, that was the only detected log file. If there are more, please tell me.
Or should we add more places to log, or add additional info ?

Btw, such lines `2018/12/08 15:03:20 CameraUploadsHandler : Scheduling a CameraUploadsSyncJobService` I modified manually, because timestamp is in separate line. What's the purpose of it ? I recommend to have it in one line, maybe with method name and line number. 
I could make a PR to do so, at least for time and log in one line

**Comment by hannesa2** [comment] 2018-12-18 07:40
In my point of view, this issue has very high (or highest) priority. 
But I can't fix, because my real device has loose connection and on Emulator I do no picture make.
@davigonz I guess you are the right person, at least the code lines have your name

**Comment by hannesa2** [comment] 2018-12-19 07:54
It would be nice to have this https://github.com/owncloud/android-library/pull/225 to have a more easy investigation

**Comment by hannesa2** [comment] 2018-12-29 11:45
"Before fixing something, first we need to reproduce it and this is not the case." ... I can do it on my wife's and my device. Pixel and Pixel 2 both with Android P.

It looks like this `created before period to check, ignoring` prevents the upload.
https://github.com/owncloud/android/blob/415f88f79051aeb9d36f1fc4217ae65a8d2527f5/owncloudApp/src/main/java/com/owncloud/android/files/services/CameraUploadsSyncJobService.java#L188

I didn't invented it, so I didn't know exactly the purpose of `OCCameraUploadSync`. 
**Please** have a look ! @davigonz 
This male function causes all my PRs and has for me the highest prio !
And because of the merge velocity, I made my private release which is ahead of upstream master https://github.com/hannesa2/owncloud-android/releases

Here are the logs
[olderLog.txt](https://github.com/owncloud/android/files/2716338/olderLog.txt)
[currentLog.txt](https://github.com/owncloud/android/files/2716339/currentLog.txt)

**Comment by davigonz** [comment] 2019-01-02 09:14
>  I can do it on my wife's and my device. Pixel and Pixel 2 both with Android P.
> I didn't invented it, so I didn't know exactly the purpose of OCCameraUploadSync.

@hannesa2 we have to reproduce it in our side so we can fix and properly test it, I'm not saying you invented it, I trust you.

> It looks like this created before period to check, ignoring prevents the upload.
> I didn't know exactly the purpose of OCCameraUploadSync.

Camera uploads feature, as `...whatever.jpg created before period to check` said in your _currentLog.txt_, **does not upload pictures taken or videos recorded before enabling the feature**, there's a warning message about that when you enable the feature as well.

For example, if you take some pictures at 11:30 and you enable Camera uploads at 12:00, those pictures won't be uploaded, just those taken after 12:00.

That's the main aim of using `OCCameraUploadSync`, apart from preventing to upload duplicated files when `CameraUploadsSyncJobService` is executed every 15 minutes. In other words, is a timestamp from which the pictures/videos taken should be uploaded.

> And because of the merge velocity, I made my private release which is ahead of upstream master

If you want to contribute with some of the features of that private release, we will review them.

**Comment by hannesa2** [comment] 2019-01-02 16:48
> For example, if you take some pictures at 11:30 and you enable Camera uploads at 12:00, those pictures won't be uploaded, just those taken after 12:00.

And how to enable to sync my older, not synced files ?

**Comment by hannesa2** [comment] 2019-01-02 16:59
### Android camera view, these are just the last ...
![image](https://user-images.githubusercontent.com/3314607/50602474-a74a9e00-0eb7-11e9-8105-b70568708408.png)
here I can scroll down and see tons of other picture


### In Owncloud:
This is ALL 
![image](https://user-images.githubusercontent.com/3314607/50602498-b7fb1400-0eb7-11e9-99c6-94868c94c2d3.png)

You see just four !

**Comment by davigonz** [comment] 2019-01-03 08:38
@hannesa2 what I see in the logs and taking into account the photos you have, if **Camera uploads** feature detects `/storage/emulated/0/DCIM/Camera/IMG_20181228_144728_1.jpg` as created before period to check is because it should have uploaded a picture created after that moment, have a look at https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/files/services/CameraUploadsSyncJobService.java#L207, is executed after requesting a new upload and there's no photo in your Kamera-Upload folder after 28/12/2018 at at 14:47:28. This is a bit weird.

There's more ways to update that timestamp:
- When disabling and enabling again the **Camera uploads** feature, e.g. uncheck + check again in Settings menu => https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java#L517
- When changing the source path in which to check the pictures/videos to upload => https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java#L651

Have you performed any of those actions? Thanks

**Comment by davigonz** [comment] 2019-01-03 08:47
> And how to enable to sync my older, not synced files ?

Uploading them, syncing older files is not the aim of Camera uploads feature.

**Comment by davigonz** [comment] 2019-01-18 09:00
> To avoid duplicates with a stored timestamp is potential error rich and I would never do this. Btw, better is to compare two lists and push missing ones

We fully tested the feature with timestamp solution and is working pretty fine. Which potential errors should we consider in your opinion?

> but better to have it twice instead of never synced !

Hmm, think that's not a good approach IMHO.

> But how to fix a wrong working app and let's sync all my picture again ?

The app is not working wrong in this scenario, your expectations were wrong about the feature. What we could do to avoid this misunderstanding and future ones is including a message saying that the camera uploads feature doesn't upload old pictures.

So I will close this issue since auto upload pictures is not broken as you describe in here, if you have any idea to improve camera uploads feature, please a new issue or PR, thanks!

**Comment by hannesa2** [comment] 2019-01-19 22:43
pretty fine ? I'm not sure 
![image](https://user-images.githubusercontent.com/3314607/51433084-393a0100-1c43-11e9-8796-4c6ce6f439fa.png)
I use the app for a long time and since this timestamp solution is invented, the app synced only four (4 !) files for the whole year 2018. 

At least there is a huge room for missunderstanding. But this word is IMHO a diplomatic word for something other

**Comment by davigonz** [comment] 2019-01-21 07:49
> pretty fine ? I'm not sure

Having reports from people who say that camera uploads do not work for them doesn't mean that the feature is not working fine, this issue is an example of it. Most of the users didn't properly configure the uploads path, that's why we included a [new warning dialog](https://github.com/owncloud/android/issues/2303).

> I use the app for a long time and since this timestamp solution is invented, the app synced only four (4 !) files for the whole year 2018.

I have analyzed your logs and suggested possible causes in [this comment](https://github.com/owncloud/android/issues/2394#issuecomment-451081692) and by reading what you said above - "Uploading them, syncing older files is not the aim of Camera uploads feature." ... ok, my expectation are wrong." - , it seems there's no wrong behaviour of the feature itself.

**Comment by jesmrec** [comment] 2019-01-21 07:57
how many pics did you take in such year? about my comment, we planned the solution to warn users about the correct behaviour (already merged). I can also assure you that the number of reports decreased strongly from the latest @davigonz implementation.

**Comment by hannesa2** [comment] 2019-01-21 17:43
@jesmrec I took ~100 pictures. I'm on latest master  (including https://github.com/owncloud/android/issues/2303) and got no warning

**Comment by davigonz** [comment] 2019-01-22 07:50
> I took ~100 pictures. I'm on latest master (including #2303) and got no warning

The warning appears when enabling the camera uploads feature, maybe you've not enabled it since then because is already enabled in your app.

**Comment by hannesa2** [comment] 2019-02-10 13:36
Now I made a picture and I'm able to [filter for that now](https://github.com/owncloud/android/pull/2440) so it's easier to investigate (unfortunately the line is long and needs 3 screens)

![image](https://user-images.githubusercontent.com/3314607/52534250-98b99700-2d3f-11e9-8486-96ddccba6806.png)
![image](https://user-images.githubusercontent.com/3314607/52534252-9f480e80-2d3f-11e9-9dce-480a56a26b49.png)
![image](https://user-images.githubusercontent.com/3314607/52534258-a7a04980-2d3f-11e9-8c56-18373a6866b8.png)

What's wrong here ? I see this two lines
`with status:UPLOAD_IN_PROGRESS and result:UNKNOWN `
`status:UPLOAD_IN_PROGRESS result:-1`

@jesmrec @davigonz do you see here a reason why nothing appears in app and on server ?

**Comment by hannesa2** [comment] 2019-02-10 13:41
Going deeper in log and observe the near time range I see L6484

It looks like it crashes and app is starting again ! 
But Owncloud logger don't share any information ! 

![image](https://user-images.githubusercontent.com/3314607/52534432-9c4e1d80-2d41-11e9-908f-c75826b6fcf6.png)

**Comment by hannesa2** [comment] 2019-02-10 17:42
Now I'm able to see, what's wrong https://github.com/owncloud/android/pull/2440

**Comment by hannesa2** [comment] 2019-02-10 21:22
Because `AndoridX https://github.com/owncloud/android/pull/2402 solves it for me, its for me done, but I would not surprised when other user run into same too.

#### Either this branch 4afb54fb0e2a3 causes it:
pro: you do not see a crash or a log entry, it's just not working
con: There must be more then a few of people out there, having this issue and I assume it was tested

#### Or installation of Android P at August 2018 on my device causes it
pro : only less people have this, so you get less feedback
con : Why I've just 4 pictures synced in year 2018 ?

Anyway, I'm done with this. For me `AndoridX` https://github.com/owncloud/android/pull/2402 solves it and I spent too much time with this.

When you close this issue is your decision

@michaelstingl 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/3314607/52539776-3d5cc880-2d82-11e9-86a2-cf85d97ae953.png">
This happen, because a global error catcher is missing

**Closed** 2019-02-13 18:38 UTC
Labels: sync::camera_uploads

**Comment by revoltown** [comment] 2023-03-26 11:12
hello i have a problem, im uploading pictures and some of them are not acessible...

**Comment by jesmrec** [comment] 2023-03-27 06:14
@revoltown could you open new issue with all details?
