### ISSUE TITLE
File loading bar old style

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1032] opened 2015-06-26 15:01 UTC
Currently when you open a file you are greeted with this beauty:
![screenshot_2015-06-26-16-59-40](https://cloud.githubusercontent.com/assets/925062/8380222/ea46eb2a-1c24-11e5-9877-02836d896d35.png)

@davivel @tobiasKaminsky @masensio you know what I mean. ;) We need a nice material design spinner here, and a proper Material design icon for aborting it.

**Comment by tobiasKaminsky** [comment] 2015-06-28 07:34
A spinner is imho not enough as the user wants to know how big the file is and how many percentage are downloaded already, or?
So there should be a spinner and "12 kb of 5mb (0,3%)".

**Comment by jancborchardt** [comment] 2015-06-28 16:09
Sorry, meant to say Material design loading bar of course.

**Comment by tobiasKaminsky** [comment] 2015-06-29 19:14
http://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

The first one "determinate"?

**Comment by jancborchardt** [comment] 2015-06-29 20:35
Yup!

**Comment by masensio** [comment] 2015-06-30 07:07
@jancborchardt,

Yes, we need to migrate this view to the Material Design appearance.
I just added this issue to the remaining tasks to adapt the app to Material Design.

NOTE: this issue must be developed after https://github.com/owncloud/android/issues/692.

**Comment by jancborchardt** [comment] 2015-06-30 17:34
It was already not fitting for Holo, just for the record. ;)

**Comment by tobiasKaminsky** [comment] 2015-07-01 19:52
BTW: this is a duplicate of #710 
But in #710 are some more suggestions from you @jancborchardt 
Please review them and integrate them in this issue and close the old one.

**Comment by sudhirkhanger** [comment] 2015-07-23 08:58
Why do we need a dedicated Activity for downloading file. Something as follows should suffice. This is just a sample. Final implementation should be determinate and material theme based.

![image](https://cloud.githubusercontent.com/assets/841656/8846729/e968d290-3146-11e5-81f1-7e0a2f202bc4.png)

**Comment by jancborchardt** [comment] 2015-07-23 10:23
Huh, closing this as duplicate of my own almost-one-year old issue https://github.com/owncloud/android/issues/710 – thanks @tobiasKaminsky for letting me know.

@davivel @masensio @tobiasKaminsky @Stoyicker @LukeOwncloud @AndyScherzinger let’s get to it then – who wants to take a stab at this? :)

**Closed** 2015-07-23 10:26 UTC
Labels: browse, Design, download, Junior Job

**Comment by AndyScherzinger** [comment] 2015-07-23 11:02
@jancborchardt I could, but I didn't quite get what needs to be done. Is this one closed and can be ignored completely and any info necessary for fixing/enhancing this is described in #710 ?

**Comment by jancborchardt** [comment] 2015-07-23 11:16
Yep, all info is now in the original issue – the important thing was Tobias' comment about which loading bar to use.

**Comment by AndyScherzinger** [comment] 2015-07-26 22:43
fix for #710 and thus for this one is on PR #1076
