### ISSUE TITLE
ownCloud app don't open the last revision of a modified file

### ISSUE THREAD

**Issue by Paviluf** [owncloud/android#1519] opened 2016-03-16 14:52 UTC
### Expected behaviour
When you open a file in the ownCloud app, it should show you the last version of the file (the one on the server).

### Actual behaviour
When you open the ownCloud app it check if there is updated files and see them. Then when you open a file that you have previously updated on your computer (that is synced to the server) the ownCloud app show you a previous version of the file.

### Steps to reproduce
1. Modify a file from your ownCloud folder on your computer
2. Sync it to the server
3. Open it in the ownCloud app on your Android phone

### Environment data
Android version: 4.4 

Device model: Razr i

Stock or customized system: CM11

ownCloud app version: 1.9.1

ownCloud server version: 8.0.2

### Logs
I don't have logs since it's my ownCloud provider that handle them.

Thanks

**Comment by LukeOwncloud** [comment] 2016-03-16 18:22
Duplicate of https://github.com/owncloud/android/issues/333

**Closed by LukeOwncloud** 2016-03-16 18:22 UTC

**Comment by Paviluf** [comment] 2016-03-16 18:44
Sorry I didn't saw it.
Thanks !

**Comment by LukeOwncloud** [comment] 2016-03-16 20:16
No problem. Happens all the time. Good that you reported it again. Must be fixed some time soon!
