### ISSUE TITLE
Display folder sizes in list view

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#712] opened 2014-11-07 09:39 UTC
In order to be aware how much space the local owncloud storage uses it would be nice to see folder sizes: both remote and local sizes (that is, how much of the remote content is stored locally)

It could be place next to the last modified date in the form "local size / remote size". @jancborchardt Where is the right spot to place that information?

___

BUGS & IMPROVEMENTS

- [X] Folder size in "share with ownCloud" view https://github.com/owncloud/android/issues/712#issuecomment-240676223 [FIXED]
- [X] 0B shown when no connectivity https://github.com/owncloud/android/issues/712#issuecomment-240997508 @davivel [FIXED]

**Comment by tobiasKaminsky** [comment] 2016-05-06 12:30
remote folder size is implemented in #1655 .
Local folder size is not shown: @janc

**Comment by jancborchardt** [comment] 2016-06-08 09:33
Local folder size is not interesting anyway, and it will be confusing to people because it doesn’t match the size which is shown on the server or other devices. If there is a folder size shown, only ever show the remote size (the »true« size ;)

**Comment by tobiasKaminsky** [comment] 2016-06-14 20:14
Recently I wanted to delete big owncloud local folders on the device. 
As this is not in the app I had to use ES File Explorer.
But I agree it is hard to show both...

**Comment by jesmrec** [comment] 2016-08-18 09:48
Improvement: When an external app shares content with ownCloud, the folders size is not displayed.

**Comment by davivel** [comment] 2016-08-19 07:35
Seen, I'll have a look. Should be easy.

**Comment by davivel** [comment] 2016-08-19 09:31
Added folder size to selector of target folder, @jesmrec

**Comment by jesmrec** [comment] 2016-08-19 11:46
### Feature

Steps:

1. Browse into a folder that has already content (size > 0)
2. Upload some content into the folder
3. Switch the device connection off
4. Browse back to the parent folder

Actual behaviour

Size: 0B

Expected behaviour

The folder size can not be updated because the lack of connectivity, so the previous size is displayed

tested with nexus9 v6, htc one v4.3

**Comment by davivel** [comment] 2016-08-19 13:10
Dammit. That's unexpected.

Good catch. I'll take care.

**Comment by davivel** [comment] 2016-08-22 07:10
@jesmrec , fixed now.

**Comment by jesmrec** [comment] 2016-08-22 08:12
@davivel, after checking the fix i keep on reproducing the problem in https://github.com/owncloud/android/issues/712#issuecomment-240997508

**Comment by jesmrec** [comment] 2016-08-22 12:04
now is already fixed

**Comment by jesmrec** [comment] 2016-08-22 12:22
And the whole feature is correct. Approved.

**Comment by davivel** [comment] 2016-08-22 13:55
Done, will be released in versin 2.2.0

**Closed by davivel** 2016-08-22 13:55 UTC
Labels: approved by qa, browse, Design, enhancement
