### ISSUE TITLE
[BUG] Duplication of Files and Folders

### ISSUE THREAD

**Issue by dpapac** [owncloud/android#3921] opened 2023-02-17 12:15 UTC
### Actual behaviour

> After the Upgrade to the latest Android App Version 3.0.3 and oC-Server Version 10.11.x it was noticed that after I tried to access files via my phone that some files/folders were duplicated
> The contents of the folder were ignored and were duplicated without any of the original folder content
>The File Note.txt was copied with the contents of the file
>The Duplication of the Files/Folder is only visible in the Android App

Can this problem be reproduced with the official ownCloud server?
> I have tested it by connecting my Android App to our demo.owncloud.com but could not replicate the issue.

>Duplicated Files in the Android App 

![Screenshot_20230215_005501_com owncloud android](https://user-images.githubusercontent.com/101094874/219629477-5a6ef6c2-d19a-4e86-8b3c-0cf53a091fd8.jpg)

### Expected behaviour
>No duplication of files and folders in the View of Files of the Android App

>As seen in this screenshot: 
![non_duplicated](https://user-images.githubusercontent.com/101094874/219629303-aeaa9645-35bf-4098-8de4-c62ed1f9bdf2.PNG)

### Steps to reproduce

1. Upgrade the Android App from Version 2.21
2. Open the app and try to access files or folders
3. Files/Folders are duplicated when trying to access them
4. Logging was disabled before this but I activated it right after I noticed the issue.

> It only occurred right after the upgrade of the Android App I could not reproduce this behaviour since then. 

### Environment data
EMUI version: 12.0.0 
Device model: Huawei P20 Pro
Stock or customized system: Stock
ownCloud app version: Upgrade from 2.21.x to 3.0.3
ownCloud server version: 10.11.6

### Logs
I added the server log file and two Android App log files:
https://cloud.owncloud.com/index.php/f/5967125

**Comment by JuancaG05** [comment] 2023-03-03 09:36
Hi @dpapac! Thanks for opening a issue!

In this case logs are not useful since they were taken after the problem happened. As we were talking, you were not able to reproduce it again upgrading from 2.21.2 to 3.0.3, so closing this.

Feel free to reopen it if the problem happens again 🍻

**Closed by JuancaG05** 2023-03-03 09:36 UTC
Labels: Bug
