### ISSUE TITLE
[BUG] Weird cookie handling

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/android#2604] opened 2019-07-11 12:24 UTC
### Actual behaviour
New cookies sent by the server are ignored by the client. The client keeps sending the same cookie.
In addition, the cookies sent by the client seem to include some cookie flags that shouldn't be present

Below what is sent by the server

![Screen Shot 2019-07-11 at 14 19 03](https://user-images.githubusercontent.com/1477829/61050291-f9c8c200-a3e6-11e9-8878-809a2a77642c.png)

And below the client

![Screen Shot 2019-07-11 at 14 18 24](https://user-images.githubusercontent.com/1477829/61050332-1533cd00-a3e7-11e9-9b65-b2995a37ed64.png)

_____

Task checklist:

- [x] Check why is happening this
- [X] First refactor of cookie stuff to use in login requests the cookie retrieved from the server https://github.com/owncloud/android/pull/2970 @theScrabi 
- [X] Remove cookie persistence https://github.com/owncloud/android/pull/3002 @theScrabi 
- [x] Refactor library to avoid cookies leaking to other accounts  @theScrabi

**Comment by davigonz** [comment] 2019-07-12 06:45
Thanks @jvillafanez for reporting this, we'll have a look

**Comment by michaelstingl** [comment] 2020-09-30 09:12
We should have closer look after the 2.16 or earlier…

**Comment by jesmrec** [comment] 2020-10-14 10:40
Checked this problem in the content of the fix: https://github.com/owncloud/android/pull/2970.

I think the problem is not gone. These are the steps i performed:

1. Add a new account, everything goes OK. App receives some cookies and start to send them:

`oc794f4ep19m=o6adkiaict0gm5nqk17e7eskjd; cookie_test=test; oc_sessionPassphrase=WUf8q8glaFgv0HAjIziVDOyNVZ%2Foqw9UNRBXY3aooizWn9iiMDX75c1KJftAIBZqKl4koLWJvF7YJt8%2BlmVXkOsSWVm6%2BYv4SNYalv0jOtYdnjLlhJz8aCOFI2rKpRQ0
`

no new cookies are sent from the server during the request/response flow (doing some operations: copy, move, share etc etc...). So, the cookies above are repeatedly send in every request with no changes

2. Add another account and repeat same process, same result.

3. Switch again to the account added in 1. Cookies start to accumulate:

`oc794f4ep19m=4ifrsdasga4fr1h2jeulaij4cr; path=/; cookie_test=test; expires=Wed,14Oct202010:54:31GMT; path=/ocs/v2.php/cloud;                                                                                                   oc_sessionPassphrase=34Y1NQRAAIAKRnq6q2h9cfH6sA21Vsr9cMXGsx0BzSqBStY5f3%2FsJqruMRtVpw%2FfDYi5htw4cJbneKvri%2ByK8L%2FAIk5fjsulNI7ocPo1QNm3l%2F5hjous2%2FzXvF5KMfk9; path=/; ocfyjsccrdck=29mt69g0djvsag6mmq8f51k8qo`

we have new cookies but i did not see any server request that sent them.

4. Switch to account in 2, same process same result.

5. Switch back to first account (steps 1 and 3), this is the cookie sent:

`oc794f4ep19m=4ifrsdasga4fr1h2jeulaij4cr; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; cookie_test=test; domain=192.168.1.66; path=/; expires=Wed,14Oct202010:54:31GMT; domain=192.168.1.66; path=/;       
                  path=/ocs/v2.php/cloud; domain=192.168.1.66; path=/; oc_sessionPassphrase=34Y1NQRAAIAKRnq6q2h9cfH6sA21Vsr9cMXGsx0BzSqBStY5f3%2FsJqruMRtVpw%2FfDYi5htw4cJbneKvri%2ByK8L%2FAIk5fjsulNI7ocPo1QNm3l%2F5hjous2%2FzXvF5KMfk9;        
                  domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; ocfyjsccrdck=29mt69g0djvsag6mmq8f51k8qo; path=/; oc_username=deleted; oc_token=deleted; oc_remember_login=deleted`

more stuff included.

By repeating several times, this is how cookies header looks like:

```
Cookie:           oc794f4ep19m=4ifrsdasga4fr1h2jeulaij4cr; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/;                 
                  domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; path=/;     
                  domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/;
                  domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; cookie_test=test; domain=192.168.1.66; path=/; domain=192.168.1.66;   
                  domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; path=/;             
                  domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; expires=Wed,14Oct202010:54:31GMT; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66;   
                  path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/;     
                  domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; path=/ocs/v2.php/cloud; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66;     
                  path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66;
                  path=/; path=/; domain=192.168.1.66; path=/; oc_sessionPassphrase=34Y1NQRAAIAKRnq6q2h9cfH6sA21Vsr9cMXGsx0BzSqBStY5f3%2FsJqruMRtVpw%2FfDYi5htw4cJbneKvri%2ByK8L%2FAIk5fjsulNI7ocPo1QNm3l%2F5hjous2%2FzXvF5KMfk9;                
                  domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/;
                  domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66;             
                  domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; path=/;             
                  domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; ocfyjsccrdck=29mt69g0djvsag6mmq8f51k8qo; domain=192.168.1.66; path=/; domain=192.168.1.66;                 
                  domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; oc_username=deleted;             
                  domain=192.168.1.66; path=/; max-age=0; domain=192.168.1.66; path=/; path=/index.php/apps/files/api/v1/thumbnail/448/448; domain=192.168.1.66; path=/; oc_token=deleted; domain=192.168.1.66; path=/; max-age=0;               
                  domain=192.168.1.66; path=/; path=/index.php/apps/files/api/v1/thumbnail/448/448; domain=192.168.1.66; path=/; oc_remember_login=deleted; domain=192.168.1.66; path=/; max-age=0; domain=192.168.1.66; path=/;                 
                  path=/index.php/apps/files/api/v1/thumbnail/448/448; domain=192.168.1.66; path=/
```

So, cookie handling is still weird.

Server version: 10.5
Android version: 7

**Comment by michaelstingl** [comment] 2020-10-14 11:00
@jesmrec issue only with multiaccount?

**Comment by jesmrec** [comment] 2020-10-14 11:05
No, same behaviour when killing the app several times with only one account. Cookies grow every time an account is open, no matter switching from another or reopening the app after closing. I used multiaccount in order to check the behaviour with two accounts at the time. Result is the same.

**Comment by theScrabi** [comment] 2022-02-28 11:07
Connection validator and remove okHttpSingleton will fix this as they do change the behaviour of cookie handling all together.

**Comment by jesmrec** [comment] 2022-04-27 07:43
Fixed within [okhttp singleton removal ](https://github.com/owncloud/android-library/pull/364):

- No more cookie accumulation in Android client
- Same session -> same cookie
- Server cookies not ignored. Only replaced when cookies are not sent

**Closed** 2022-04-27 11:05 UTC
