### ISSUE TITLE
Show avatar in account list

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#778] opened 2014-12-04 00:33 UTC
In the account list in the setttings, to the left of each account the avatar of that account should be shown. Same for iOS.

PR: https://github.com/owncloud/android/pull/1559

cc @rperezb @tobiasKaminsky @LukeOwncloud

**Comment by tobiasKaminsky** [comment] 2015-07-01 19:55
The problem is, that there is no public avatar route in /core as far as I know.

**Comment by tobiasKaminsky** [comment] 2015-07-01 19:58
https://github.com/owncloud/core/issues/17305

**Comment by tobiasKaminsky** [comment] 2015-07-01 20:03
Can be imlemented when https://github.com/owncloud/core/pull/14856 is merged.

**Comment by tobiasKaminsky** [comment] 2016-05-06 12:34
Done by @AndyScherzinger in ...? (do not know the PR)

**Comment by rperezb** [comment] 2016-05-06 13:23
@tobiasKaminsky i'd say that this is better to keep it open till the pr is merged
https://github.com/owncloud/android/pull/1559

**Comment by tobiasKaminsky** [comment] 2016-05-06 13:28
ok. maybe we should have a label "PR exists" or something like to show that this is in progress?

**Comment by rperezb** [comment] 2016-05-06 13:30
i added the pr on the issue description + to review label

let's see whether this helps, otherwise, a new label, label 🎉  ☺️

**Comment by tobiasKaminsky** [comment] 2016-05-06 13:38
PR in issue description is a good idea to have a cross reference.
Using the 1-5... labels for PR is doubtable as this has to be kept in sync with the PR.

**Comment by rperezb** [comment] 2016-05-09 08:26
@tobiasKaminsky yes, anyhow, both issue and pr has to be kept in sync

**Comment by davigonz** [comment] 2017-11-30 10:21
This is already implemented, see https://github.com/owncloud/android/pull/1559

**Closed** 2017-11-30 10:22 UTC
Labels: accounts, Design, enhancement
