### ISSUE TITLE
Permanent Authentification Error

### ISSUE THREAD

**Issue by rmk-ch** [owncloud/android#2906] opened 2020-06-22 08:47 UTC
### Actual behaviour
I want do synchronize my Android tablet to my owncloud installation. The data is already on the server and contains several 1000 files and is about 20GB of size. It is mainly a download-only setup (just keep Android downloading new files without changing them back to the server).

In previous versions of the owncloud Android client I received several authentification failures during synchronization. It was tedious but eventually I managed downloading almost all relevant data.
Now with the latest update the sync-process does not work anymore: authentification failure is a permanent error.
I can re-enter the password in the account settings dialog which it accepts before saying again that authentification fails.

Concluding, owncloud client is not working at all for me.
Note that the password is correct as login in through browser works from same device.
Also, the android app works for the same server on another device and another user name (same app version).

This might be related to this issue I had a while ago: https://github.com/owncloud/client/issues/6843
Server support for HTTP/2 is unfortunately still not available. But I have this issue only on one client...

### Expected behaviour
Accept password and synchronize without crashing or authentification errors.
 
### Steps to reproduce
1. Open owncloud app
2. Error appears 
3. (Re-enter password in change account dialog)
4. (Error appears)

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No, not reproducible

### Environment data
Android version: 9

Device model: Samsung Galaxy Tab S5e

Stock or customized system: stock version

ownCloud app version: 2.15 (less severe with older versions)

ownCloud server version: 10.4.1.3

#### Web server error log
N/A

#### ownCloud log (data/owncloud.log)
[ownCloud.log](https://github.com/owncloud/android/files/4829146/ownCloud.log)
Edit: Removed server, username

**Comment by jesmrec** [comment] 2020-06-23 16:43
Thanks for reporting, we'll work to fix it

**Comment by WhereisBielefeld** [comment] 2020-06-24 17:00
Same issue here

**Comment by jesmrec** [comment] 2020-06-25 06:54
Some questions:

- The errors you get, are just after logging in? or when you do any specific action? (download, av. offline...)
- Do you have more than one ownCloud account attached in the device, or only one?
- Which authentication method do you use: basic authentication (username/password), or OAuth2 (authentication via web browser)?

Any detail you can give us, matters.

@WhereisBielefeld @rmk-ch

**Comment by rmk-ch** [comment] 2020-06-25 08:48
- I get the error after freshly opening the app. Basically every time the app tries to do anything on/withthe server. Some (sub) folders have been synchronized already with previous OwnCloud versions and I have the foldermarked as available offline. So the app probably tries to synchronize with the server when opened.
- I have only one account on this device
- Basic auth is used
I am happy to help or try things when needed.

**Comment by WhereisBielefeld** [comment] 2020-06-25 19:28
@jesmrec
Sorry your are totally right, you need mir information.

Opening the app works, but if I try to reload (slide down) oder open a folder It gonna tell me autentificantion error.

If I reenter my password it shows my folders but going the next step results in the described behavior.

If I go offline, open the app no problems occurs. 

Only one user, but several accounts. My wife has the same problem but other account.

User/pw autentificantion.

Windows app, website etc is running without any problems.

We are both using Android (10 and 9)

**Comment by jesmrec** [comment] 2020-06-26 06:16
thanks!! another important detail:

did you do a fresh install, or upgrade from previous version?

**Comment by WhereisBielefeld** [comment] 2020-06-26 06:40
I got an update (beta version) and as the problem occurred, I reinstalled it with the release version but the problem remained although cleaning cache and storage.

**Comment by rmk-ch** [comment] 2020-06-26 07:14
I did an update as well.
In contrast to WhereIsBielefeld I did not try a reinstallation or cache/storage deletion.

**Comment by jesmrec** [comment] 2020-06-26 08:30
> I got an update (beta version) and as the problem occurred, I reinstalled it with the release version but the problem remained although cleaning cache and storage.

If the beta that you installed was the beta1, i encourage you to reinstall the app because such beta was buggy.

**Comment by WhereisBielefeld** [comment] 2020-06-26 09:05
> > I got an update (beta version) and as the problem occurred, I reinstalled it with the release version but the problem remained although cleaning cache and storage.
> 
> If the beta that you installed was the beta1, i encourage you to reinstall the app because such beta was buggy.

I did.

**Comment by jesmrec** [comment] 2020-06-26 11:18
did you change the password in your account in any moment? (by using the web UI settings). we have a suspiction...

**Comment by WhereisBielefeld** [comment] 2020-06-26 11:59
> did you change the password in your account in any moment? (by using the web UI settings). we have a suspiction...

No, neither me nor my wife. Sry

**Comment by rmk-ch** [comment] 2020-06-26 18:25
I believe I changed the password as administrator user as before as I wasnt totally sure if it was correct (because of this error). But I am pretty sure it is still the same as before.

**Comment by abelgardep** [comment] 2020-06-29 07:42
I was able to reproduce the problem of authentication failed loop. Basic credentials were not properly refreshed, i created a PR to fix it. Thanks for your feedback 👍

**Comment by rmk-ch** [comment] 2020-06-29 11:07
Hi @abelgardep and @jesmrec  
Thanks a lot for fixing this so quick!
Do you have an estimate when the fix will be released? Or this there a test build that I can use for the moment?

**Comment by abelgardep** [comment] 2020-06-29 13:14
First it needs to be verified, so stay tuned for new updates 👍

**Comment by abelgardep** [comment] 2020-07-01 06:48
Validated a fix to refresh credentials once you relogin. Will be included in 2.15.1

**Comment by jesmrec** [comment] 2020-07-01 08:40
@rmk-ch if you send us an email to android-app@owncloud.com, we will forward you an apk with the fix, where you can take a look. The point is, it will be a debug apk, that you only will be able to install if you removed the Google Play's apk.

**Comment by rmk-ch** [comment] 2020-07-01 08:43
@jesmrec Thanks a lot for the offer. In the meantime I have installed a temporary workaround such that I can wait for the release. 
Thanks again for fixing this so quickly.

**Comment by sj** [comment] 2020-07-14 18:37
Thanks for fixing this!

I believe I'm seeing the same issue; ownCloud has stopped working completely on my Android phone as a result of this. When do you think version 2.15.1 will be released? I'm in the beta tester group on the Google Play Store. If possible, I prefer not to install any APKs outside the play store.

Thanks again!

**Comment by jesmrec** [comment] 2020-07-16 06:12
we expect to release very soon. At the end of the current week, or early next week. Thanks a lot for your patience!

**Comment by jesmrec** [comment] 2020-07-21 07:37
Keep working on it. We are fixing the latest problem we found... ftm, work in progress. We'll keep you updated.

**Comment by jesmrec** [comment] 2020-07-31 07:35
hi! we have an interesting clue about where the problem was. If any of you are interested in helping us to check before the release, we can ship you a test apk, so we can get your feedback in advance. Just email to `android-app@owncloud.com` and post here that you sent the mail, to check asap and send you the apk.

**Comment by WhereisBielefeld** [comment] 2020-08-02 14:51
@jesmrec I'd like to try but I'm afraid to install anything outside the play store (although I know the source) Sry

**Comment by hannesa2** [comment] 2020-08-02 19:57
It we had this "_faster releases, even for testing purpose_" #2924 someone could simply invite you to alpha testers, and you could receive hotfix by Google Playstore immediate
@michaelstingl

**Comment by rmk-ch** [comment] 2020-08-03 05:54
Sorry, I cannot test it either as the affected tablet is not here at the moment. Maybe it is possible next week.

**Comment by jesmrec** [comment] 2020-08-04 08:39
> It we had this "faster releases, even for testing purpose" #2924 someone could simply invite you to alpha testers, and you could receive hotfix by Google Playstore immediate

the problem of this release is neither the testing not the release process. It is a nasty bug that we are able to reproduce, but the fix is taking more time than expected. Different things. I will put my thoughts in your PR.

**Comment by hannesa2** [comment] 2020-08-04 09:07
> > It we had this "faster releases, even for testing purpose" #2924 someone could simply invite you to alpha testers, and you could receive hotfix by Google Playstore immediate
> 
> the problem of this release is neither the testing not the release process. It is a nasty bug that we are able to reproduce, but the fix is taking more time than expected. Different things. I will put my thoughts in your PR @hannesa2

Yes it's a deliver process issue. That's my suggestion about, to speed this up, and bring it to more devices faster to test, without a release to the world. -all automatic-

**Comment by hannesa2** [comment] 2020-08-04 09:10
Btw, my [version](https://github.com/hannesa2/owncloud-android/releases/tag/2.15.1.1) with this fix has currently no authentication errors anymore

**Comment by jesmrec** [comment] 2020-08-04 09:44
the bug we detected depends on several factors, mainly kind of auth (OAuth2) and av. offline. @abelgardep is doing his best with it.

**Comment by sj** [comment] 2020-08-04 09:56
> the bug we detected depends on several factors, mainly kind of auth (OAuth2) and av. offline. @abelgardep is doing his best with it.

To add some detail: my setup is fairly straightforward: I do use 2FA on my ownCloud instance, but there are no weird other auth setups.

**Comment by WhereisBielefeld** [comment] 2020-08-12 17:12
@jesmrec so far... Good news! I needed to deleted and rejoin my account and by now it works. Sure to be clear, we need some time but im optimistic
You (and the team as well) did a great job fixing! Thank you!

**Comment by sj** [comment] 2020-08-12 18:18
Same here! I upgraded the ownCloud app, generated a new application-specific password from the web interface, entered that into the Android app, and it works brilliantly!

Thanks for the hard work team!

**Comment by jesmrec** [comment] 2020-08-13 06:12
Thanks all for your feedback!!. I will close the issue then. Feel free to reopen or open another issue in case you detect something wrong.

**Closed by jesmrec** 2020-08-13 06:12 UTC
Labels: Estimation - 3 (M)
