### ISSUE TITLE
Thumbnail on Android after core update are not working

### ISSUE THREAD

**Issue by DevTeamPostCy** [owncloud/android#1084] opened 2015-08-03 14:37 UTC
Thumbnail are not viewable on android .

Also when I locate from core website to /remote.php/webdav/Photos/Paris.jpg the thumbnail is automatically open in a download link and not in a preview mode.

Does anybody know how to fix that issue?

**Comment by tobiasKaminsky** [comment] 2015-08-03 17:00
Please use the template https://raw.github.com/owncloud/android/master/issue_template.md
Otherwise there are many important informations missing.

Regarding your second question: webdav is a protocol to transfer files, so it is intended to just offer the image and not preview it.
The right url for viewing images from within the web frontend would be: http://localhost/owncloud/index.php/apps/files#//1.jpg

**Comment by DevTeamPostCy** [comment] 2015-08-04 06:24
Thank you for your reply. I understand what you said.... But why with the previous version of the owncloud core, Android thumbnail, were ok and now are not visible to the application?

**Comment by masensio** [comment] 2015-08-04 06:49
Hi @DevTeamPostCy,

Which server version are you using? We need to check if the problem is in Android app or in the server.
As @tobiasKaminsky said, it is better that you describe the problem using the template https://github.com/owncloud/android/blob/master/issue_template.md for having all the information about the problem.

Thanks for your feedback.

**Comment by DevTeamPostCy** [comment] 2015-08-04 07:08
### Expected behaviour
Android thumbnail should be visible on the gallery view

### Actual behaviour
No thumbnail are visible.

### Steps to reproduce
1. From Android open a folder with photos
2. In the gallery I can see that has pictures but without thumbnails in order to see witch photo is what...

### Environment data
Android version: every model

Device model: every model

Stock or customized system: Stock

ownCloud app version: 1.7.0

ownCloud server version: 8.1

### Logs
#### Web server error log
None error

#### ownCloud log (data/owncloud.log)
None error

### Comments
With ownCloud server version 8.0.2 thumbnail were visible

**Comment by masensio** [comment] 2015-08-04 07:18
@DevTeamPostCy, thanks for the complete description, now we can compare the behaviour depending on the server version.

**Comment by masensio** [comment] 2015-08-04 10:40
@DevTeamPostCy, Do you have any forbidden character in your path? (like  \ / < > : " | ? *)

**Comment by DevTeamPostCy** [comment] 2015-08-04 11:15
@masensio,  Let's say if I click on the Paris.jpg in the Photos folder I get this path where I can view the image from the owncloud core.
/index.php/apps/files/?dir=%2FPhotos#/Photos/Paris.jpg

**Comment by john156** [comment] 2015-08-08 10:10
thanks helped me a lot :+1:

**Comment by pubmania** [comment] 2015-08-08 16:36
I have this problem too... Thumbnails are not visible on Android with 8.1 server. Although on an older device it does show thumbnails for photos on the device.

**Comment by DevTeamPostCy** [comment] 2015-08-10 07:30
But is there any way I can fix that problem? Is that an owncloud core bug that they will fix it?

**Comment by davivel** [comment] 2015-08-10 12:43
@DevTeamPostCy, the URL accessed to get thumbnails from the server side is:

http(s)://<your.domain>/<your.oc.path>/index.php/apps/files/api/v1/thumbnail/<width>/<height>/<pathToFile> .

Please, check in a web browser if you can see the thumbnail there; <width> and <height> are the size the client wants for the thumbnail, use the values you prefer.

**Comment by DevTeamPostCy** [comment] 2015-08-10 12:55
@davivel thank you for your reply. This path on the core is working correct. But on Android is not.... do I have to make changes on Android code? If yes, can you please give me some instructions?
Is that a problem that will be fixed or I have to proceed and fix it on my own?

**Comment by davivel** [comment] 2015-08-10 12:56
I'm not sure. Any reason why you are using version 1.7.0 of the Android app? The last one is 1.7.2

**Comment by DevTeamPostCy** [comment] 2015-08-10 14:01
Dear @davivel on 1.7.2 is corking correctly. Is there any issue on 1.7.0? Just to know if we can fix that issue instead of change android version.

**Comment by davivel** [comment] 2015-08-10 18:14
It's a lateral effect of the changes in WebDAV support done in OC 8.1. This was merged in version 1.7.1 of the Android app, in https://github.com/owncloud/android/pull/913 . Note that it includes an update of the OC library for Android, where are located the most important changes to adapt to this change of the server side.

For more details: the thumbnail is not retrieved from the server side because the property 'oc:id' returned by the server is used as a key to store the thumbnails in the local cache. Thas is one of the properties that are not received in the client without the changes in PR#913.

> Just to know if we can fix that issue instead of change android version.
I guess you talk about doing it in your own fork of the app. My recommendation is you keep it in-line with the most recent release in this repository. In the long term that will be easier than backporting individual PRs your fork. But the decision is yours.

Since this is already fixed in the official app, this issue should be closed.

**Closed by davivel** 2015-08-10 18:14 UTC
Labels: browse, bug, image
