### ISSUE TITLE
Don't use an own folder on mobile for uploaded files

### ISSUE THREAD

**Issue by Siggi0904** [owncloud/android#1306] opened 2015-11-23 10:25 UTC
The uploaded files where copied to an own owncloud folder.
Thats not good, because of to many files in the gallery and to much space consumption.

Please use to check to uploaded file the original folder and files.

**Comment by LukeOwncloud** [comment] 2015-11-23 17:23
Duplicate of https://github.com/owncloud/android/issues/819. Please check progress there.

**Closed by LukeOwncloud** 2015-11-23 17:23 UTC
