### ISSUE TITLE
Eternal syncing kills the phone's battery

### ISSUE THREAD

**Issue by llucax** [owncloud/android#953] opened 2015-04-18 19:10 UTC
I noticed a couple of days ago that my phone started to drain the battery very fast and using a program to trace which programs are using wakelocks, I found that the owncloud syncing was responsible, making my phone never entering in *deep sleep*.

I had to disable syncing, otherwise my battery lasts close to nothing.

Not too long ago I added some external folders to my owncloud server with a lot of files (~67K files). I wonder if that could trigger this problem (but I think I noticed this problem in my phone a few days **after** I added the files to the server).

A simple way to see if these 2 events are related would be to exclude the new external folders from the syncing, but I can't find any option to select which folder to sync, as you can do with the (linux) desktop app.

**Comment by llucax** [comment] 2015-04-18 19:19
BTW, I'm using version 1.7.0, and just as a comment, I remember something similar to this happened in the past. See #671.

**Comment by llucax** [comment] 2015-04-18 19:34
Mmmm, looking at the server's log while syncing, I see each and every folder is queried via `PROPFIND`, so maybe the problem is not the number of files, but the number of folders (I have ~4K folders).

And it looks like it takes in the order of 500ms to query one folder (at least that's the rate of lines printed in the log file), so querying 4K folders will take ~30 minutes.

**Comment by llucax** [comment] 2015-04-18 19:35
For me the easiest workaround will be to just be able to select which folders to sync, like in the desktop app (I don't need access to all those files in my phone, they are mostly there for web access).

**Comment by llucax** [comment] 2015-04-18 19:38
Mmm, on the other hand, the desktop client only make one query via `PROPFIND` to the top-level folders I select to sync and that's it, it doesn't query every subfolder inside those...

**Comment by llucax** [comment] 2015-04-18 19:39
Even more, the android client makes 2 `PROPFIND` query per folder, not just only one!

**Comment by masensio** [comment] 2015-04-22 08:09
Hi @llucax,

thanks for reporting  your problems.
We haven't done changes in sync process since 1.6.1 version ( This version fix #671 ).
Have you enabled automatic sync in Account Manager of the device? If you have this option enabled and you have a lot of folders ( 4K folders is a lot I think ) sync process takes a lot of time. 

Mobile sync process only takes the data about the directories tree and the content of each folder. If you need to have the content of a file or a folder you need to download specifically. We make two PROPFIND in order to obtain the files/folder and the share files/folders, but that isn't the cause of the battery problems.

So our sync process works in different way than the desktop sync process.
We know that we can do some improvements in our sync process, but I don't know when. It is not planned in the near future. :worried: 

Sorry for the inconvenience.

**Comment by leandro-lucarella-sociomantic** [comment] 2015-04-22 10:26
hi @masensio, thanks for the reply. Yes, the battery drain occurs only when Sync is enabled in the device and in particular when I enable the OwnCloud sync account.

So, this effectively leaves me without owncloud sync in my phone. What do you think about adding some option to pick which folders to sync, like in the desktop client. I have the feeling that might be easier to implement than changing how the whole sync process works...

**Comment by masensio** [comment] 2015-04-22 14:06
Yes @llucax we have in mind to have "Keep in sync" option for folders also, see  #3
I hope it will be available in a near future.

**Comment by leandro-lucarella-sociomantic** [comment] 2015-04-22 17:11
> Yes @llucax we have in mind to have "Keep in sync" option for folders also, see #3
> I hope it will be available in a near future.

No, I mean the exact opposite, to be able to tell the android client to absolutely ignore some folders. In the desktop client is the other way around, instead of having automatic access to the root directory, you set up which folders you want to sync to. So, I have like 3 top-level folders. 1 that is he only one is important to me to be accessible in the phone and with just a few files, and 2 that have a big number of subfolders. If I could tell the android client to only look at that small subfolder, that would let me use the owncloud client in android, which now for me is absolutely not an option.

**Comment by masensio** [comment] 2015-04-24 06:54
Hi @llucax,

sorry for my confusion. In that case, please open a new issue describing the new feature, to keep in mind for the future enhancements.

At the moment, we have in mind the favorite folders feature not the option that you want. So, I don't know when this new feature could be included in our app.

Thanks in advance.

**Comment by leandro-lucarella-sociomantic** [comment] 2015-04-24 15:39
Done, #960. Thanks.

**Comment by jab416171** [comment] 2015-06-20 20:06
I'm having the same problem. This app has been killing my battery over the last couple of days. I turned off sync in the account manager, so hopefully that will fix it until it's fixed in the app itself.

**Comment by davivel** [comment] 2015-06-24 07:12
@leandro-lucarella-sociomantic , what version is your server? Do you have the same problem with external storage disabled?

The sync process should not walk down all the folders every single time, but only through those branches that lead to files that had any change from the last synchronization. If the app is traversing the full tree every time through paths without changes, there are chances that the external storage is propagating wrongly the eTag until the root folder.

**Comment by llucax** [comment] 2015-06-24 10:01
Mmm, OK. That could explain why I detected this problem later. I added 2 big directories with a lot of files at 2 different times to owncloud. Maybe I only noticed it working for a long time the second time and I disabled the sync then. I'll re-enable the sync and see if after a full sync it gets back to normal.

The desktop client is a whole different thing, because I'm not syncing at all the big directories. This is why I opened #960, which basically proposes the same feature the desktop client has where you can hand pick with directories to synchronize (in the desktop client I say, please sync /safe to ~/shared/safe for example, you don't have that kind of control with the Android app, which would be also **extremely** useful to synchronize some folders to the SD card for example, something that you can't do now AFAIK).

**Comment by llucax** [comment] 2015-06-24 17:48
I can confirm they sync process keeps query folders that didn't change all the time. I had to disable it again.

**Comment by davivel** [comment] 2015-06-25 14:55
Sorry for insisting, but: does it query for those folders once or twice?

**Comment by llucax** [comment] 2015-06-25 15:05
It does check twice per folder as said in https://github.com/owncloud/android/issues/953#issuecomment-94195372, this is each time a sync is performed, 2 `PROPFIND` are made against each folder.

**Comment by llucax** [comment] 2015-06-25 15:54
But according to the web server logs, the reply is different for each (different size at least).

**Comment by davivel** [comment] 2015-06-25 16:33
Yes, that's expected. The first one is requesting only for an Etag. The second one is the full list of files in the folder, 

And we *need* to change this. A single request should be triggered per-folder, using a conditional header with the last Etag to get a response only if the Etag changed. 

Technical debt.

**Comment by llucax** [comment] 2015-06-25 17:18
> Technical debt.

"let him who is without technical debt cast the first stone" :)

**Comment by davivel** [comment] 2015-06-26 07:23
XD

**Comment by m4lvin** [comment] 2015-12-09 22:04
Was something changed recently which can bring back this issue? I never had this problem before but now owncloud is emptying my battery... (app version 1.9.0 from f-droid, Android 5.1.1 on Nexus 4, owncloud 8.2.1 on server)

**Comment by kricklen** [comment] 2016-01-17 18:08
I got the same problem, the owncloud app keeps requesting the same external folder infos from my server v8.2.2, though the content didn't change for months. This seemed to start with app v1.9.0.
The desktop v2.1.0 seems to work fine.
Is this still being investigated?

**Comment by LukeOwncloud** [comment] 2016-04-26 20:25
Should be fixed since version 1.9.1 according to https://github.com/owncloud/android/issues/1442. Please object if you are still suffering the same problem!

**Closed by LukeOwncloud** 2016-04-26 20:25 UTC
Labels: bug, performance, sync

**Comment by llucax** [comment] 2016-04-27 22:16
I can confirm this is much better, but with sync enabled, the owncloud app still hammers the server quite a bit, even for folders that didn't change in ages. Should I open another issue or reopen this one?

**Comment by LukeOwncloud** [comment] 2016-04-28 06:27
Sounds a little different. Better open a new issue. Thanks!

**Comment by llucax** [comment] 2016-04-28 09:54
#1644
