### ISSUE TITLE
Username normalization in owncloud beta (2.5.1-beta 1) prevents login with ldap user

### ISSUE THREAD

**Issue by jensd0e** [owncloud/android#2030] opened 2017-09-11 06:50 UTC
### Actual behaviour
- Username is altered (or normalized) automatically after first login. Space is changed to underscore.

### Expected behaviour
-Username should not be altered.  
 
### Steps to reproduce
1. Install owncloud latest beta. (Hint: Same behavior with latest nextcloud dev-version) 
2. Login with username containing a space. [Here authentication is done against LDAP server]. First login works, but app (almost) instantly redirects back to login screen, where you have to login again. But: 
3. Username is changed from 'Firstname Lastname' to 'Firstname_Lastname' and the username field can't be modified, so the username can't be changed and the user can't authenticate against LDAP server. User is locked out and has to reinstall app.

### Note
Username is not changed with latest ownCloud stable (2.4.0) (or latest nextcloud).

### Workaround
[Only works in nextcloud-dev:] Also configure to login with Email-Account as login attribute in LDAP. Username is changed as described above in app, but login is done with Email-Address. 
**Update**: After some time, nextcloud decided to change my username from username@mailserver.com@owcloudserver.com to user_name@owncoudserver.com. 
Conclusion: Some recent change in the owncloud and nextcloud app changes the login account to the username in owncloud. But this is not necessarily my login username. 
Now it seems, that oc and nextcloud share a recent code change. All the time, I wished that both Teams work together to fix the instant upload issue. Now I wish, that they did not work together. :-)

### Environment data
Android version: 7.0
Device model: Samsung Galaxy S7
Stock or customized system: Stock
ownCloud app version: 2.5.0 beta 2
ownCloud server version: 9.1.6

**Comment by jesmrec** [comment] 2017-09-12 11:54
This is like the regression we found in the tasks of 2.5.0 official version. We will study it. Thanks for reporting!!!!!

**Comment by jensd0e** [comment] 2017-11-22 12:46
Today I was redirected to login page over and over again, like described above. This is version 2.5.1-beta.1
Is this supposed to be fixed in 2.5.1-beta.1? 
After uninstalling and reinstalling, app crashed permanently. Fixed this by clearing app data and cache. After entering server and credentials, it did not happen again (rebooted to be sure).

**Comment by jesmrec** [comment] 2017-11-22 14:32
after clearing, is the problem fixed?

**Comment by jensd0e** [comment] 2017-11-22 15:07
No. Problem persists: I'm logged in and after one or two seconds, I'm back at the logon screen. As far as my LDAP-Server is concerned, logon is successful.

Since a restart seem not to be enough to trigger this, there seems to be some "time-dependent-token" involved. I just reinstalled and cleared data & cache to get it working again. Clearing data & cache doesn't work. I need to uninstall the app. Working again.

**Comment by jesmrec** [comment] 2017-11-22 15:49
it would be helpful a test account in your server to try to reproduce the problem. Would it be posible? in this case, you can ship test credentials to apps@owncloud.com

Regarding your mail, the link you posted comes from a different company's product.

**Comment by jensd0e** [comment] 2017-11-22 19:48
Tomorrow I can send you the credentials. But there are no login failures, so that might not be too helpful.

Regarding the link: the solution mentioned there is surely no fix for this problem? I don't know what Tobias is talking about, but it might be worth to look at problem.

Right now it works as supposed and I can't break it. 😁

**Comment by tobiasKaminsky** [comment] 2017-11-23 06:45
I did not wanted to highjack this thread, but since you mentioned me. 
Your problem with whitespaces in username is solved in nc app, as you said in your "update" in the first comment. However there was still a little bug where such users with whitespaces could not set/unset a file as favorite, so I mentioned you in this fix, to let you know that now everything will work (in nc app).

**Comment by jesmrec** [comment] 2017-11-23 07:25
i will check all the stuff again. thanks all.

**Comment by jensd0e** [comment] 2017-11-23 07:28
Ok. OC is redirecting me again. Credentials send. 

@jesmrec: Thanks a lot!
@tobiasKaminsky: Thanks for your explanation. Since login seems to be fine (checked the server logs), I don't think that a whitespace in my username is the root cause for my problem. But hey, I'm just a user here...

**Comment by jesmrec** [comment] 2017-11-23 12:30
first of all, thanks for the test account @jensd0e.

Some thoughts:

- Checking your account, i could not reproduce the problem. After logging, i was never redirected to login view when i perform some different actions in the account. In any case, Android app is ready to handle with blanks in the user field, as the server does.

- About editing the username: our policy always was that a different username means a different account. In any case, i do not understand why you said that changing the username makes you to reinstall the app. You can not change the username, but you can re-attach the account without reinstalling.

**Comment by jensd0e** [comment] 2017-11-23 14:26
@jesmrec: Since installing ownCloud today (about 7 hours ago), it didn't "break" ("break": eternally redirecting me to logon screen). Yesterday it worked from afternoon (fresh install) until today in the morning. It "broke" somewhere in between. 

I don't think my current problem has anything to do with my username having a white-space in it. It seems I have hijacked this thread (I started) for this *new* problem. :-(

About changing my username: that was just as a workaround for the problem, described in the OP. I'm using my initial username for weeks. As another test, I also installed ownCloud 2.5.0 - just to see, if my problem originates from my phone, since with version 2.5.0 I never had the redirecting error.

**Comment by jesmrec** [comment] 2017-11-23 14:31
ok... so we will have more patience to catch what is that breaks. i keep on checking your account.

**Comment by jensd0e** [comment] 2017-11-23 16:46
Ok, It's broken again: ownCloud (2.5.1-beta.1) always redirects me to login page. After entering my (valid) credentials, I see my root folder for a short time (time is varying each time) before I'm send back to login screen.

OwnCloud 2.5.0 is still working.

**Comment by jesmrec** [comment] 2017-11-23 16:50
you can find logs in settings view, in case of the beta.

**Comment by jensd0e** [comment] 2017-11-23 17:12
Are the logs removed, if I reinstall? It's easier to grab them via adb, if I only knew where to look.

**Comment by jensd0e** [comment] 2017-11-23 17:25
@jesmrec Now I have a log-file from the point, where I push the connect button, until I'm redirected. If you like, I'd be glad to send it to you.

**Comment by jesmrec** [comment] 2017-11-23 22:10
thanks! send a new mail to apps@owncloud.com attaching the file

**Comment by jensd0e** [comment] 2017-11-30 07:27
Logfile should be in your inbox.

**Comment by jesmrec** [comment] 2017-12-01 08:25
@jensd0e we did not receive the logs :(

**Comment by jensd0e** [comment] 2017-12-01 08:37
I’m sorry. I’ll send it again.

 

Regards,

Jens

**Comment by jensd0e** [comment] 2017-12-01 08:38
Seems to be stuck somewhere. I just send the logfile again. Please contact me, if no E-Mail arrives.

**Comment by jesmrec** [comment] 2017-12-01 08:56
mail received!

**Comment by pjao** [comment] 2017-12-17 23:18
@jesmrec Same problem here, from a fresh install debian9 and owncloud 10.0.4.4, when using ownCloudBeta-android/2.5.1-beta.1 always redirects me to login page. 

After entering my (valid) credentials, I see my root folder for a short time before I'm send back to login screen.

With ownCloud-android/2.5.0 no problem at all. Windows or web interface, also without problems.

**Comment by davigonz** [comment] 2018-01-16 16:12
Still trying to reproduce it, it will not be included in 2.6.0 release, moving it...

**Comment by davigonz** [comment] 2018-01-26 09:43
@jensd0e , @pjao , please follow up https://github.com/owncloud/android/issues/1964 where we are talking about the login redirection in beta app.

I will keep this issue opened to fix the problem described in the first comment, not the login redirection one.

**Comment by davigonz** [comment] 2018-07-26 12:06
We deprecated the beta app described in this issue and the solution proposed [here](https://github.com/owncloud/android/issues/2098) is no longer needed, so this shouldn't happen again with the new beta version. 

I will close this, if you want to know how to join our new betas, please have a look at the end of our [ readme file](https://github.com/owncloud/android/blob/master/README.md)

**Closed** 2018-07-26 12:06 UTC
