### ISSUE TITLE
Starred files not syncing automatically

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1093] opened 2015-08-13 14:57 UTC
To sync a starred file, I manually have to open it or refresh the folder. In any case I have to manually open the ownCloud app. This is very cumbersome.

There should be regular polling for changes in starred files, or some mechanism which syncs them in the background. That’s what is expected from files which are starred (used to be »keep up to date«!)

@rperezb @MTRichards @davivel @tobiasKaminsky @AndyScherzinger

**Comment by tobiasKaminsky** [comment] 2015-08-13 17:34
Isn't this the purpose of settings -> accounts -> files -> synchronisation
At least this is what I have in mind.
But it will still be on a random (or at least not predictable) time interval.
@davivel knows it better.

**Comment by AndyScherzinger** [comment] 2015-08-13 17:55
Why would it be random? Looking at @AndlyticsProject - synchs in time intervalls, so this either worked at some point, is broken or needs to be imlemented differently (not having looked at the code though)

**Comment by tobiasKaminsky** [comment] 2015-08-13 18:22
https://github.com/owncloud/android/issues/989#issuecomment-105419725

> This automatic synchronization is triggered by the system "whenever it wants".

This was to what I was referring.

**Comment by jancborchardt** [comment] 2015-08-13 21:38
> Isn't this the purpose of settings -> accounts -> files -> synchronisation

Not sure what you mean by that @tobiasKaminsky 

I would expect stuff to be automatically synced, very aggressively to make sure I always have the latest versions. In my case for example this is about notes which need to be always up to date.

**Comment by tobiasKaminsky** [comment] 2015-08-14 13:42
This is an option in androids setting.
As far as I know this has to be enabled in order to have sync working properly.
Can you verify if this is enabled for you?

**Comment by jancborchardt** [comment] 2015-08-15 10:23
Aaaah – I have to go to Settings -> Accounts -> ownCloud and activate File sync?

That doesn’t seem to be enabled by default, should we make the app auto-enable that once you use the Favorite / Keep up to date function?

**Comment by tobiasKaminsky** [comment] 2015-08-15 10:33
I remember that this is off by default as it could cause higher battery drain if there are many files/folders and/or many starred files.
But yes, you have to enable it.

**Comment by jancborchardt** [comment] 2015-08-15 12:41
Then we at least need some kind of hint. As soon as we have a »Favorites« entry in the sidebar for sure, we need some link to that setting.

**Comment by tobiasKaminsky** [comment] 2015-08-15 13:01
But first we need confirmation of @davivel, if everything is right what I have told.
Maybe, but I do not know, if this is possible we could enable this with the first favorite entry and notify the user about that (of course with an option to revert it).

**Comment by LukeOwncloud** [comment] 2015-08-17 14:00
Duplicate of https://github.com/owncloud/android/issues/726?

**Comment by jancborchardt** [comment] 2015-08-18 18:24
@LukeOwncloud thanks for the info! Closed that issue in favor of this here as we have more info here.

@davivel check this issue please and reply to @tobiasKaminsky’s remarks.

**Closed** 2019-03-04 21:58 UTC
Labels: bug, sync::available_offline
