### ISSUE TITLE
Authorization Header is not being sent in 2.2.0

### ISSUE THREAD

**Issue by marcos-guerrero** [owncloud/android#1867] opened 2016-12-28 09:48 UTC
### Actual behaviour
Every DAV request (PROPFIND, GET, DELETE) is being sent without Authorization header in first place. Once the server answers "HTTP/1.1 401 Unauthorized" the client sends the same request, this time with the authorization header

### Expected behaviour
As it happens before 2.2.0 version, the client should send the authorization header in the request, so no duplication happens
 
### Steps to reproduce
No special procedure. Just connect the client to the server and navigate, every PROPFIND, GET, DELETE , PUT, ... are sent without Authorization header in first term.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
yes

### Environment data
Android version:
7.1.1
Device model: 
Nexus 5x
Stock or customized system:
Stock
ownCloud app version:
2.2.0
ownCloud server version:
9.1.3

**Comment by davivel** [comment] 2017-01-11 14:55
@marcos-guerrero , in the web UI, in the view "Personal", section "Sessions", do you see a session called "Mozilla/5.0 (Android) ownCloud-android/2.2.0" ?

Did you get the app from Play Store, or did you build it yourself?

**Comment by marcos-guerrero** [comment] 2017-01-11 15:23
Hi! Thank you for answer to my issue!
There're no android session in the Personal Sessions sections, right know the only session is "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Saf..." where I'm browsing the UI
And the client is installed from F-DROID https://f-droid.org/repo/com.owncloud.android_20200000.apk
By the way, the unauthorized responses:

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured</s:message>
</d:error>

are not only for the WebDAV requests but the OCS (user, capabilities, shares) requests as well:

<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
 </meta>
 <data/>
</ocs>

Going to install the android client from Play Store and I'll report back

**Comment by marcos-guerrero** [comment] 2017-01-11 15:28
The 2.2.0 client installed from Google Play makes no difference. Still two requests , first unauthorized second authorized.

**Comment by marcos-guerrero** [comment] 2017-01-11 15:34
Wait!
About the sessions, I swear I didn't see any android session, but now:

Browser	Most recent activity	
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36	seconds ago	
Mozilla/5.0 (Android) ownCloud-android/2.2.0	a minute ago	
Mozilla/5.0 (Android) ownCloud-android/2.2.0	7 minutes ago

So it's my desktop browser, the f-droid android client (7 minutes ago) and the google play client (a minute ago)

**Comment by davivel** [comment] 2017-01-11 15:59
Can you check again if requests are being duplicated now that you can see the session in the web UI?

**Comment by marcos-guerrero** [comment] 2017-01-11 16:06
Still the same, the android client session is up to date "Mozilla/5.0 (Android) ownCloud-android/2.2.0 seconds ago) but the requests are still duplicated.

**Comment by davivel** [comment] 2017-01-11 16:10
Do you use a proxy? Is it possible that it is removing cookies in the road?

**Comment by marcos-guerrero** [comment] 2017-01-11 16:43
Today I'm using a proxy (Fiddler) and never did such bad thing!  
On my first report I used both Fiddler and the a sniffer. I have to ask my workmate to capture again the incoming traffic to the oc Server, tomorrow will report.

**Comment by marcos-guerrero** [comment] 2017-01-20 10:45
@davivel  Sorry for my late report, I couldn't get anyone helping me with the sniffer, so I changed the approach to probe my issue. No proxy, no sniffer, only I turn logging to the maximum "Log everything" in the server... and then I connect my owncloud android client 2.2.0. It works, but for every dir change (propfind) , file deletion, etc... I get one line on the log file:

{"reqId":"kmaaPyb9uNX\/E8D98lIT","remoteAddr":"172.19.3.119","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"data_user\"}","level":0,"time":"2017-01-20T10:20:58+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/ROOT\/Recs\/Dropbox\/Photos\/","user":"data_user"}


Of course, if I use the 2.1.2 client there is no error log line.

I tested the app in different android phones (my Nexus 5x 7.1.1, Samsung Galaxy 5) , all of them showing the same behaviour

**Comment by davivel** [comment] 2017-01-25 17:14
Hi, @marcos-guerrero ; in Android client 2.2.0 we disabled 'preemptive' mode in the requests to the server; that means that library is sending every request first without authentication header, and then with it if receives a 401 from the server. That results in the duplication of requests in your server.

The reason why we disabled it is that we are using a value in the "Cookies" header to keep a single session with the server. With that cookie, the server shouldn't respond with a 401, even if the credentials are not in the request. Only if the session was killed in the server a 401 should be gotten.

And for some reason (I don't remember now), enabling preemptive mode and adding the "Cookies" does not work fine. That's why we disabled it.

The thing is: you are the only one with this problem (for the moment) AFAIK. We can't reproduce here 

Could you give us more data about your server configuration? Do you use Apache or Nginx, or other? What version?

How did you install your OC server? Is it a clean installation, or an upgrade?

Thanks for your patience.

**Comment by marcos-guerrero** [comment] 2017-01-30 12:49
Hi!
I have two servers, with the same configuration, and the issue is happening on both:
*Ubuntu 16.04 LTS
*Apache 2.4.18
*PHP 7.0.8

It's a pity that https://demo.owncloud.org is not available to test on the same enviroment... but  maybe we could try to reproduce the issue in the same system, using a preloaded machine... 

* https://bitnami.com/stack/owncloud/virtual-machine 
or
* https://www.techandme.se/pre-configured-owncloud-installaton/ -> Ubuntu 16.04.1 main: https://cloud.techandme.se/index.php/s/MUl79ovm7Ifo4kG
or 
* other virtual appliance you suggest...

Which one do you prefer?

Thanks for your patience too

**Comment by davivel** [comment] 2017-01-31 17:21
I don't have a preference, whatever is easier for you.

In any case, I will make a check. I can't remember why we had to disable the preemptive mode to work with the session cookie. I'll reenable it again to find out.

**Comment by davivel** [comment] 2017-01-31 18:10
OK, I don't fully understand what happened before, but with preemptive authentication enabled the cookie session is working fine, both in server 9.1.3 and in forthcoming versions. I will restore the preemptive mode, and that should fix your problem.

The bad news are that at this moment I can't compromise to get a new release soon. We'll give it another thought, let's see what can we do.

**Comment by davivel** [comment] 2017-02-01 09:47
I didn't imagine it! :D 

With server 9.1.3 preemptive mode + session tracking work fine.

But not with 9.1.2. In that case (and probably in any 9.1.x before 9.1.3) if the request includes both the session cookie and the credentials, these are used by the server to create a new session **before** checking the session cookie; and that's why session tracking fails.

That changes from 9.1.3, and we can enable preemptive mode again and send both credentials and session. That will fix your problem, @marcos-guerrero .

AFAIK we still need session tracking in 9.1.x with x < 3, and since this bug seems to depend in some way of your setup, I opted for keeping preemptive mode disabled in the range [9.1, 9.1.3) .  

To be released with 2.3.0, no ETA yet.

**Comment by davivel** [comment] 2017-02-01 09:48
cc @jesmrec

**Comment by marcos-guerrero** [comment] 2017-02-01 17:34
@davivel So ... Do you want me to test my problem in an enviroment you can easily replicate? Because it looks like enabling preemtive mode again in the future version will fix my problem (and of course I can wait and stick to the 2.1.2 till then) but it doesn't resolve the mistery of why the heck are my servers rejecting the cookies and asking again for authentication
If you want, I'll try with bitnami and If I could reproduce the problem I would ask you to test on the same bitnami enviroment.

**Comment by davivel** [comment] 2017-02-01 17:35
@marcos-guerrero , sounds like a plan :) . :+1:

**Comment by jesmrec** [comment] 2017-02-08 17:15
@marcos-guerrero 

Taking in account that you are the only one who reproduced the problem.. could you check if the following apk developed by @davivel 

https://github.com/owncloud/android/blob/recover_preemptive_authentication/res/raw/android_2.2.0-debug.apk

fixes the problem? Thanks in advance!

**Comment by marcos-guerrero** [comment] 2017-02-09 15:00
Of course, my pleasure! I'll be back soon with the result

**Comment by marcos-guerrero** [comment] 2017-02-09 15:33
@davivel 
Just test the official 2.2.0 apk against a clean installation on my virtualbox of the https://bitnami.com/stack/owncloud/virtual-machine . The only thing I've done after installation was to change the log level to Everything and voila! There's lot of Debug traces: Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/dav\/appinfo\/v1\/webdav.php(57): Sabre\\DAV\\Server->exec()\n#5 \/opt\/bitnami\/apps\/owncloud\/htdocs\/remote.php(164): require_once('\/opt\/bitnami\/ap...')\n#6 {main}","File":"\/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":"user"}

And if I put fiddler on the middle, yes, there're two request for each action on the phone: one unauthorized and the second request is correctly answered.

So, I think it will be easy to reproduce the problem,
Best regards

**Comment by marcos-guerrero** [comment] 2017-02-09 15:35
@davivel @jesmrec 
I've just tried the test version of the app https://github.com/owncloud/android/blob/recover_preemptive_authentication/res/raw/android_2.2.0-debug.apk in the same enviroment than the previous test, and ... it works as expected. No double request, no unauthorized response. 

Best regards

**Comment by hwoodward** [comment] 2017-02-12 20:14
@jesmrec  - I was seeing the same issue on my server with the official apk, I had similar server logs and it could never upload photos. Tried the test version linked above and it solved it for me too. Just so you are aware.

**Comment by jesmrec** [comment] 2017-02-13 07:56
@hwoodward thank you too for your feedback.

This is approved and ready to be merged.

**Closed** 2017-02-13 09:42 UTC
Labels: approved by qa, bug, login
