### ISSUE TITLE
Instant Upload based on folder observance instead of broadcasted events

### ISSUE THREAD

**Issue by schiessle** [owncloud/android#6] opened 2012-10-31 13:58 UTC
We discussed and debugged the issue already on IRC some time ago. It seems that the camera App from HTC does something different which doesn't trigger the instant upload. Tested with HTC Desire S (Android 2.3.5, HTC Sense 3.0) and the ownCloud Android Client 1.3.8

EDITED by @davivel
SUMMARY on 26/02/2016

The problem: third party camera apps often fail to broadcast the ```Intent```s with action ```android.hardware.action.NEW_PICTURE``` and ```android.hardware.action.NEW_VIDEO``` that the OC app listens for to know when a new picture or video was taken.

The probable solution: keep alive a FolderObserver on the official folder where pictures / videos are stored to know when a new picture or video was taken.

Main references on this: 
https://github.com/owncloud/android/issues/6#issuecomment-22494946
https://github.com/owncloud/android/issues/6#issuecomment-60381095
#1059 

To keep in mind:
- There are third party camera apps that don't use the official DCIM folder to store their captures; let's ignore them first. 
- Android Services are not granted to be there forever; this could result in problems to keep the FolderObserver alive; risk is low, since that's the approach already used to observe kept-in-sync / favourite files, and our experience in this point has been fine.
- The app keeps too many Services. We should tend to merge them in a different architecture, with a more uniform synchronization model. Internally, the concept of 'instant upload' should evolve to 'automatic addition, later sync'.

**Comment by davivel** [comment] 2015-01-16 13:06
@LukeOwncloud , android.os.Environment.DIRECTORY_DCIM is at least good enough to take as a starting point.

FolderObserver should help. If I'm not wrong it's used in keep-in-sync files. That's the way go with this problem.

**Comment by tobiasKaminsky** [comment] 2015-08-23 17:31
This idea would solve the problem as it allows any folder to act as a source of instant upload: #744

**Comment by davivel** [comment] 2016-02-26 20:02
I renamed the issue and adde a summary of the current knowledge in the first comment.

**Comment by Fukurokudzu** [comment] 2016-04-27 13:48
Hi. I've the latest 2.0.0 on android 6 and instant upload works only from local storage and does'nt work when photo storage is set to sd card. I guess that's what this bug is about, right?

**Comment by AndyScherzinger** [comment] 2016-04-27 13:51
Which camera app are you using? Stock android camera app or any third party?

**Comment by Fukurokudzu** [comment] 2016-04-27 13:52
It's huawei honor 7 stock camera.

**Comment by davivel** [comment] 2016-05-18 12:51
This is one of the two viable alternatives to solve the "instant upload of pictures" shutdown that we'll suffer with Android N.

Advantages: this solution is valid for any Android version 'til the day.
Drawbacks: Doze could make the observer service is killed too often; or maybe not, but it's something to be tested.

For the record: the second alternative is what Google recommends to replace the subscription for NEW_PICTURE and NEW_VIDEO broadcast events; ref: https://developer.android.com/preview/features/background-optimization.html#new-jobinfo

**Comment by malkomich** [comment] 2016-06-01 09:35
We could implement a new way to schedule instant uploads for a new photo or video, with the recently JobScheduler.

https://developer.android.com/preview/features/background-optimization.html?hl=es

The problem is that this is only available for API 21 or higher, the same in which NEW_PICTURE, NEW_VIDEO and CONNECTIVITY_ACTION broadcasts are deprecated.

So we still need the solution for lower APIs, and implement this new one for 21 and higher to avoid Doze shutdowns like @davivel said.

**Comment by gw0** [comment] 2016-07-25 06:18
On Samsung Galaxy S6 using the default Camera app usual photos and videos get uploaded as expected, but Camera Collage and some custom features/effects do not, although there also get stored into `DCIM/Camera`. Same goes for apps, that store photos/videos in their own folder. A folder-observing solution (even if triggered only every now and then) would solve this.

**Comment by davivel** [comment] 2016-08-17 10:37
Going for it.

**Comment by davivel** [comment] 2016-08-29 10:59
The fix has been merged. Due to its historical importance, I'd like to keep the issue open for a while to get some feedback when the fix is released.

That will be very soon. We will reschedule the current plan and release a version 2.1.1 with the current job done in the milestone 2.2.0. The total loss of instant uploads of pictures in Android 7 is too serious to wait more time.

I will update milestones in a while. Stay tuned :)

**Comment by davivel** [comment] 2016-09-01 15:38
Release 2.1.1 is out now. Please, take a look to the option 'Camera folder' in instant upload settings to select the folder where your camera app stores the pictures, and give it a try. The new implementation will observe that folder and upload new pictures or videos in it.

We expect this solution works with most of the camera apps that were already working, and with most of the camera apps that were not working at all.

Looking forward your feedback :)

**Comment by Fukurokudzu** [comment] 2016-09-02 06:30
Just tried it on my Huawei Honor 7 (android 6.0) with stock camera and didn't succeed. 
Camera is set to store photoes on ext_sd, so i set owncloud to look into /storage/6F4B-1E08/DCIM/Camera (photoes goes there, i checked) with no luck. Right after installation OC asked permission access for sdcard, if it matters.

**Comment by davivel** [comment] 2016-09-02 07:31
Thanks, @Fukurokudzu . There are some things pending to check about permissions and ext_sd, probably your problem is about that.

The camera stores the pictures there by default, or is it configurable? In the second case, could you change it to a location in emulated external storage (public internal) and make another test? Just to know about the Huawei camera app.

**Comment by davivel** [comment] 2016-09-02 07:42
@gw0, could you try Camera Collage with ownCloud 2.1.1? Thanks.

**Comment by davivel** [comment] 2016-09-02 07:49
@mhellwig , @rlaban , @LukeOwncloud , @redfave , some feedback from you would be really awesome :) . Thanks

**Comment by cschwarz007** [comment] 2016-09-02 08:35
I tried on my Samsung A3 (2016) with Android 6.0.1 Neither storing the pictures on the SD-Card nor on the internal storage works. Tried both OpenCamera and the Samsung stock camera app...

**Comment by davivel** [comment] 2016-09-02 08:48
OpenCamera is one of our test apps. Could you double check with it, please? Remember to chose in the app settings "DCIM/OpenCamera" as camera folder.

**Comment by cschwarz007** [comment] 2016-09-02 08:56
Hi David, it works with OpenCamera but only if I set "Use Storage Access Framework" to off. Does not work with OpenCamera if Storage Framework is enabled (regardless where the pictures are saved) nor with the built-in Samsung camera app (which always uses the framework I suppose)... Hope this helps and/or let me know what other info I can provide to support...

**Comment by davivel** [comment] 2016-09-02 08:58
Sure it helps, @cschwarz007 . That's a variable we didn't take into account. I'll think a bit about it, probably we'll need to open a new issue to dealt with it.

**Comment by Fukurokudzu** [comment] 2016-09-02 09:38
@davivel ok, i set camera to store photos on internal storage. OC shows /storage/emulated as empty folder, so i just can't select internal storage there. I set OC to look into /sdcard/DCIM/Camera (new files are there) and still no luck with instant uploads. Uploads list is empty (i reinstalled the app last night just to be sure).

**Comment by davivel** [comment] 2016-09-02 10:08
Thanks, @Fukurokudzu . I expected that /sdcard/DCIM/Camera worked fine... Will have to research a bit more, maybe the Storage Access Framework is related, as in the case of @cschwarz007

**Comment by Fukurokudzu** [comment] 2016-09-02 10:12
@davivel well, maybe, but i'm just a user, i've just learned what SAF is and can't recall any settings, connected to this technology.

**Comment by davivel** [comment] 2016-09-07 07:45
@cschwarz007 , @Fukurokudzu , maybe you are interested in https://github.com/owncloud/android/issues/1795#issuecomment-245196504

**Comment by cschwarz007** [comment] 2016-09-07 19:20
@davivel Thanks a lot - this solved the issue on my (meanwhile) Sony X5 Compact (and I am sure it would work on Samsung too).

**Comment by davivel** [comment] 2016-09-14 10:38
Thanks for the feedback. Version 2.1.2 is already pushed to Play Store, will be soon in your devices with the combined solution (FileObserver + broadcast event).

For sure, this is not the last word in improvements about instant_uploads. There are plenty of things to do in https://github.com/owncloud/android/issues?q=is%3Aopen+is%3Aissue+label%3Async%3A%3Ainstant_upload , and we'll continue to address them, with your help.

**Closed by davivel** 2016-09-14 10:38 UTC
Labels: Android_7, approved by qa, enhancement, sync::instant_upload
