### ISSUE TITLE
Regenerate Private Key from mobile client

### ISSUE THREAD

**Issue by gmkrab** [owncloud/android#1660] opened 2016-05-05 16:25 UTC
So we have a couple of problems:
1. User should generate Private Key every time when his password changed.
2. Normally to generate Private Key user has to do it manually from web->username->Personal.
3. iOS/android APIs not provide this functionality
4. iOS/android APIs not provide handle of error (when user should to regenerate Private Key manually before getting any respons from server), just common handle like UNHANDLED_HTTP_CODE | UNKNOWN_ERROR

**Comment by LukeOwncloud** [comment] 2016-05-09 19:59
After 4 days of no response, I dare to ask: What private key are you referring to? Should there be such a setting here: https://demo.owncloud.org/settings/personal (user/pwd:test/test)?

**Comment by LukeOwncloud** [comment] 2016-05-19 08:44
Closing due to insufficient information. If this is still an issue, please provide more data about your server configuration and everything that is needed to reproduce this issue.

**Closed by LukeOwncloud** 2016-05-19 08:44 UTC
Labels: Needs info
