### ISSUE TITLE
[a11y] 11.4.1.2 Name-role value

### ISSUE THREAD

**Issue by tschiebel** [owncloud/android#4373] opened 2024-04-05 12:55 UTC
audit: https://infinite.owncloud.com/s/QtwuiGHikwFjozV

https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf
https://github.com/BIK-BITV/BIK-App-Test/tree/main/Pr%C3%BCfschritte/de

### Personal Space

- [ ] Several buttons have been detected on the page that do not have a role
assigned. 
![image](https://github.com/owncloud/android/assets/132444655/e317e6e5-ead7-4bb3-8770-501f8bcee1a9)

- [ ] If the elements on the page are sorted, the status of the sorting is only visually
sorting status is only visually represented by arrows. However, this visual representation
visual representation is a limitation for non-visual users, as they do not receive any
information about the current sorting. 
![image](https://github.com/owncloud/android/assets/132444655/2a4953e2-b6d7-4374-ac73-ebdd9e1828cd)

- [ ] The button with the "+" does have an accessible name, 
but this is not meaningful. It would make sense to use the word "Add" as an accessible 
the word "Add", for example, to give users a clear description of the function. 
clear description of the function. 
There is also a problem for non-visual users, as opening the menu is not 
opening the menu is not clearly signaled. It is important that the status 
of the menu is accessible to all users.
![image](https://github.com/owncloud/android/assets/132444655/a47e38e7-d80d-40f2-9fd7-d7af986db6db)

### Menu

- [ ] The link "...-Portal" was not correctly marked as a link 
correctly. The role "Link" is missing, which should be used for the semantically correct 
should be used for the semantically correct labeling of links.

- [ ] The logo (see screenshot) was erroneously labeled as a button 
although clicking on the element opens a new page in the browser. 
opens a new page in the browser. Instead, the logo should be provided with a link element 
in order to be semantically correct.
![image](https://github.com/owncloud/android/assets/132444655/b463abd0-5b33-4115-a105-3e5243c55d0b)

- [ ] All elements of the menu are missing the correct role, either 
"Button" or "Link".
![image](https://github.com/owncloud/android/assets/132444655/b6dd55ec-3db8-4a54-8efc-8f836550eb53)

- [ ] The button with the account data does not have a corresponding role. 
In addition, the labeling is too long and difficult to understand. It is 
It is also unclear which view of the menu users are currently in.
![image](https://github.com/owncloud/android/assets/132444655/eea9a521-a370-4c1d-89c2-e4da866c46ce)

### Edit shared Link

- [ ] The "Expiry date" and "Date" buttons have no role.
![image](https://github.com/owncloud/android/assets/132444655/9b3eef98-0eab-4916-906c-b47ea4ef1205)

### Spaces

- [ ] Both the "Spaces" heading (button) and the "Space" buttons 
do not have a role. 
![image](https://github.com/owncloud/android/assets/132444655/18c35722-5f88-4f39-bf14-8c458547b85a)

### Manage Account

- [ ] Neither the "Add account" button nor the "Account" button have a role. 
have a role. 
![image](https://github.com/owncloud/android/assets/132444655/dae12f0a-feb4-4839-9fb5-0cf5134575ab)

### Image Viewer

- [ ] None of the items in the "More options" menu have a role.
![image](https://github.com/owncloud/android/assets/132444655/d9e0e353-544e-4b41-b733-75ca01fd8f2b)

**Comment by jesmrec** [comment] 2024-04-17 10:58
Pending to check. Are roles really a mobile concept? or only web?

**Comment by Aitorbp** [comment] 2024-08-13 11:53
> audit: https://infinite.owncloud.com/s/QtwuiGHikwFjozV
> 
> https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf https://github.com/BIK-BITV/BIK-App-Test/tree/main/Pr%C3%BCfschritte/de
> 
> ### Personal Space
> * [ ]  Several buttons have been detected on the page that do not have a role
>   assigned.
>   ![image](https://private-user-images.githubusercontent.com/132444655/320000432-e317e6e5-ead7-4bb3-8770-501f8bcee1a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTAyMjksIm5iZiI6MTcyMzU0OTkyOSwicGF0aCI6Ii8xMzI0NDQ2NTUvMzIwMDAwNDMyLWUzMTdlNmU1LWVhZDctNGJiMy04NzcwLTUwMWY4YmNlZTFhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTUyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjVlNjQwNzM0YWRhMTEwODM2YzQzYTI1YTk1YWMxNzUzNDAxMGExMGEzZWRmZjBhZDUxNTA0NTAzZTI5NWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XnDI2Cg5rvlR0d_6mxQfePVSNURlR4oG9kwcDaiioGA)
> * [ ]  If the elements on the page are sorted, the status of the sorting is only visually
>   sorting status is only visually represented by arrows. However, this visual representation
>   visual representation is a limitation for non-visual users, as they do not receive any
>   information about the current sorting.
>   ![image](https://private-user-images.githubusercontent.com/132444655/320000494-2a4953e2-b6d7-4374-ac73-ebdd9e1828cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTAyMjksIm5iZiI6MTcyMzU0OTkyOSwicGF0aCI6Ii8xMzI0NDQ2NTUvMzIwMDAwNDk0LTJhNDk1M2UyLWI2ZDctNDM3NC1hYzczLWViZGQ5ZTE4MjhjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTUyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzNhZTI2MmQyMGJmMzUyOThhZDI5NTNmOGUwMjc2MmZjNGU2MTJiMGY5YjgwMTFkM2Y2MmNiY2RjZGEzN2E1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yU2K2R6wcxiSRZ3_HAv-j51TtinP1Y5mgSq46XdaXSI)
> * [ ]  The button with the "+" does have an accessible name,
>   but this is not meaningful. It would make sense to use the word "Add" as an accessible
>   the word "Add", for example, to give users a clear description of the function.
>   clear description of the function.
>   There is also a problem for non-visual users, as opening the menu is not
>   opening the menu is not clearly signaled. It is important that the status
>   of the menu is accessible to all users.
>   ![image](https://private-user-images.githubusercontent.com/132444655/320000718-a47e38e7-d80d-40f2-9fd7-d7af986db6db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTAyMjksIm5iZiI6MTcyMzU0OTkyOSwicGF0aCI6Ii8xMzI0NDQ2NTUvMzIwMDAwNzE4LWE0N2UzOGU3LWQ4MGQtNDBmMi05ZmQ3LWQ3YWY5ODZkYjZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTUyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjA5YTNkY2I3YWY2OWY3ZmIxMjA5NTUzODRmNGU2NTYxOTY3MzlmOGEzZTExNDM1MWRkOTFlNzBlZTgzMWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O6JeT0CPOWngW29spRUuR6srnDxpbGaI8cQoiXsJSB4)
> 
> ### Menu
> * [ ]  The link "...-Portal" was not correctly marked as a link
>   correctly. The role "Link" is missing, which should be used for the semantically correct
>   should be used for the semantically correct labeling of links.
> * [ ]  The logo (see screenshot) was erroneously labeled as a button
>   although clicking on the element opens a new page in the browser.
>   opens a new page in the browser. Instead, the logo should be provided with a link element
>   in order to be semantically correct.
>   ![image](https://private-user-images.githubusercontent.com/132444655/320001109-b463abd0-5b33-4115-a105-3e5243c55d0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTAyMjksIm5iZiI6MTcyMzU0OTkyOSwicGF0aCI6Ii8xMzI0NDQ2NTUvMzIwMDAxMTA5LWI0NjNhYmQwLTViMzMtNDExNS1hMTA1LTNlNTI0M2M1NWQwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTUyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzBhMjIxOGRlNDU4ZmIyYWNkZmRlOTZlOWU5N2JkMGNkODBkM2Y2ZDE4YjNhN2JlOTYyOTJhNWVkYzFjYjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yebmpwHwZZ3VG4oVsJKqFpx1LBO6pELqHewNKkwEa90)
> * [ ]  All elements of the menu are missing the correct role, either

Assigning an `AccessibilityDelegate` to a `MenuItem` is not as straightforward as assigning it to a normal view because `MenuItem` is not a `View` itself. Instead, `MenuItem` has an associated `View via `actionView`, which can sometimes be null if it hasn't been manually configured.

The problem is that you need to associate an actionview to the item, but this returns null. Searching on the internet it is recommended to manually assign a view to the item. But that hasn't worked either.

>   "Button" or "Link".
>   ![image](https://private-user-images.githubusercontent.com/132444655/320001278-b6dd55ec-3db8-4a54-8efc-8f836550eb53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTAyMjksIm5iZiI6MTcyMzU0OTkyOSwicGF0aCI6Ii8xMzI0NDQ2NTUvMzIwMDAxMjc4LWI2ZGQ1NWVjLTNkYjgtNGE1NC04ZWZjLThmODM2NTUwZWI1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTUyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzIzM2RlOTBmYTg5MjE2OTMxYWNmZDQzMGJhYjYyZjQzMzc4MjA0ZjQ2MDU4ZGVkM2Q1Y2IyZjUwNDkzOTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.itRPceONNNZ8Qo4ulHWOCciY4nPN5eT7pfKLOL3W9EU)
> * [ ]  The button with the account data does not have a corresponding role.
>   In addition, the labeling is too long and difficult to understand. It is
>   It is also unclear which view of the menu users are currently in.
>   ![image](https://private-user-images.githubusercontent.com/132444655/320001593-eea9a521-a370-4c1d-89c2-e4da866c46ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTAyMjksIm5iZiI6MTcyMzU0OTkyOSwicGF0aCI6Ii8xMzI0NDQ2NTUvMzIwMDAxNTkzLWVlYTlhNTIxLWEzNzAtNGMxZC04OWMyLWU0ZGE4NjZjNDZjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTUyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTFjNjRhOWNhZWYyNTgyM2JjNzVmMjRhYmI2YjQ0NmZkOTgxY2Y1ZWIzYTgzMTAyNTUxYjMwMjc1ZTE2YTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AgBeDdtWuPv5kGy7li4tflg23UxT6nUSQG5rvX9VtuA)
> 
> ### Edit shared Link
> * [ ]  The "Expiry date" and "Date" buttons have no role.
>   ![image](https://private-user-images.githubusercontent.com/132444655/320001876-9b3eef98-0eab-4916-906c-b47ea4ef1205.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTAyMjksIm5iZiI6MTcyMzU0OTkyOSwicGF0aCI6Ii8xMzI0NDQ2NTUvMzIwMDAxODc2LTliM2VlZjk4LTBlYWItNDkxNi05MDZjLWI0N2VhNGVmMTIwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTUyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjVkNmQ5Y2IwMjU3ZWMwMzc1YzQzNTE4YmZjMDg3MzkwMDJkYmY1MDY2NTdlNDg1M2FmMGRhNjc5NDQxM2QxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bbisbwnTgTX4jllqCGqYZ2qF0pIyebDqrSSGU21SMUY)
> 
> ### Spaces
> * [ ]  Both the "Spaces" heading (button) and the "Space" buttons
>   do not have a role.
>   ![image](https://private-user-images.githubusercontent.com/132444655/320002095-18c35722-5f88-4f39-bf14-8c458547b85a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTAyMjksIm5iZiI6MTcyMzU0OTkyOSwicGF0aCI6Ii8xMzI0NDQ2NTUvMzIwMDAyMDk1LTE4YzM1NzIyLTVmODgtNGYzOS1iZjE0LThjNDU4NTQ3Yjg1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTUyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTE4YmNmMDQ5MmQ1ZjYxYmIzNjZhYjYyN2YzZGY2YWM2Yzc0M2YyYjhhY2EwNGNkYjk5OTAyOGMzMWU3NTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.myBUfAmw7kUhWp7kzcU7psjayf_9gcALOG2N0zoTNfc)
> 
> ### Manage Account
> * [ ]  Neither the "Add account" button nor the "Account" button have a role.
>   have a role.
>   ![image](https://private-user-images.githubusercontent.com/132444655/320002272-dae12f0a-feb4-4839-9fb5-0cf5134575ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTAyMjksIm5iZiI6MTcyMzU0OTkyOSwicGF0aCI6Ii8xMzI0NDQ2NTUvMzIwMDAyMjcyLWRhZTEyZjBhLWZlYjQtNDgzOS05ZmI1LTBjZjUxMzQ1NzVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTUyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDMyNDQ2ZmI5YzAwMjQxNjU4M2YyMjQ3YTNmOGQ3ZjU0NmY1N2UwNGRmN2UyNGViZTQ2ZjdiOWUxMDk0OGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iRNbdssaH9TlXD-OZ3FlCTidBzattRgAtXSsOccZVoM)
> 
> ### Image Viewer
> * [ ]  None of the items in the "More options" menu have a role.
>   ![image](https://private-user-images.githubusercontent.com/132444655/320002488-d9e0e353-544e-4b41-b733-75ca01fd8f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTAyMjksIm5iZiI6MTcyMzU0OTkyOSwicGF0aCI6Ii8xMzI0NDQ2NTUvMzIwMDAyNDg4LWQ5ZTBlMzUzLTU0NGUtNGI0MS1iNzMzLTc1Y2EwMWZkOGYyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTUyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTNhYThlNmYwOTY3YTAxNDZlMTI4Mzg5YmY3YTY2NmZmMWI1NjczMGQ0NWM0YTJmZDkwNTc4Y2Y1M2FhNDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fiF1IRA5EwuGVGFVjtq4Bgqz9tjjuoZqBQtCPm0aOFQ)

**Closed** 2024-08-27 07:48 UTC
Labels: Type:bug, p3-medium, Estimation - 5 (L), Sprint, Accessibility
