### ISSUE TITLE
Autoupload don´t work on alternate Camera mode

### ISSUE THREAD

**Issue by motorsense** [owncloud/android#933] opened 2015-03-29 08:08 UTC
Mobilephone: Samsung Note 4 (SM-N910C) with stock samsung firmware (android 5.01)
Same Issue on my wifes Galaxy S5 (stock firmware android 5.0)
Owncloud Version: 8.0.2
App Version: 1.7.0

When i use automatic mode on stock camera, all works fine. When i use alternat camera mode in stock camera (e.g. sports mode) automatic upload don´t work.
Im sorry but i don´t find any log on my mobilephone.

**Comment by tobiasKaminsky** [comment] 2015-03-29 12:32
I can imagine that the problem is that the alternate camera does not send the broadcast that is required, afair: com.android.camera.NEW_PICTURE
There is a similar issue with hdr images.

**Comment by masensio** [comment] 2015-04-09 12:24
Hi @motorsense,

as @tobiasKaminsky said, maybe the problem is because the camera doesn't send the event that we are expecting for launch the upload.
We need to change the way in we treat to do instant upload to fix this kind of issues.

Sorry for the inconvenience.

**Comment by tobiasKaminsky** [comment] 2015-04-16 12:27
@motorsense Please see https://github.com/owncloud/android/issues/760 
The developer of the other apps has to implement the right broadcast.

**Comment by motorsense** [comment] 2015-04-17 06:34
@tobiasKaminsky Hello, I'm not a developer and have therefore no idea about it. I just know that it works with other cloud apps, like for example, Dropbox. Only the owncloud app do not upload on alternate camera mode.

**Comment by tobiasKaminsky** [comment] 2015-04-18 06:45
It is no problem that you are not a developer. But you can contact the developer of the alternate camera app.
But as @masensio said, there has to be a better solution in the next time.
Maybe you can find out how other cloud apps do this and give us a hint?

**Comment by motorsense** [comment] 2015-04-20 06:38
@tobiasKaminsky Hello, its not an alternate camera app problem, its a problem with stock camera app from samsung firmware in alternate camera mode. The Samsung camera app have different modes e.g. automatic mode, sports mode, food mode and so on. Only in automatic mode the owncloud automatic upload works.

**Comment by Bugsbane** [comment] 2015-06-14 15:09
Yes, the camera app should send the correct signal, but really, we can't assume that every camera app is going to do things the correct way. Really, we need to watch the DCIM folder and upload whenever a new file exists there, regardless of whether we're sent the correct signal or not.

By all means use the correct signal to pick up on these changes *faster*, it's just not helpful to users to pretend files don't exist if other app developers don't create their software how we would prefer.

**Comment by tobiasKaminsky** [comment] 2015-06-16 18:54
This is also possible with #744

**Comment by tobiasKaminsky** [comment] 2016-05-06 17:23
So closing this one as we can only fix it with #744, but this can be discussed in the PR.

**Closed by tobiasKaminsky** 2016-05-06 17:23 UTC
Labels: bug, instant_uploads
