### ISSUE TITLE
Menu items change after download/abort

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1249] opened 2015-11-04 11:14 UTC
Open a non-audio and non-video file which (e.g. xlsx), download starts. Quickly open menu. It holds about 6 entries. Wait for the download to finish, press back button when being asked to open the file. Open menu again: It holds about 12 entries. Is this intended?

Another related issue: Open file, abort download. Now menu hosts about 10 entries. This can't be right, can it?

**Comment by tobiasKaminsky** [comment] 2015-11-21 09:09
This is indeed a little mysterious.
I someone wants to help me? @AndyScherzinger @przybylski 
(Just checkout beta and give it a try. But if you can track the problem down to a specific file the change must be committed in the right PR)

**Comment by przybylski** [comment] 2015-11-21 17:11
I might have idea why this might happening, but personally I cannot reproduce it.
Can someone provide a step by step reproduction ;)

**Comment by AndyScherzinger** [comment] 2015-11-22 21:02
I also haven't found a way to reproduce this behavior :(

**Comment by LukeOwncloud** [comment] 2015-11-23 12:57
@przybylski I provided the steps in my top post. Maybe your Internet connection is too fast?

Here some screenshots:

Right after chosing file (file is being loaded):
![loading](https://cloud.githubusercontent.com/assets/2737900/11336925/73b3a7a6-91e9-11e5-9c05-e63af28c6e12.jpg)

Upload is cancelled (file is not locally available):
![loading aborted](https://cloud.githubusercontent.com/assets/2737900/11336927/75926184-91e9-11e5-9bfe-7c2866aa8d14.jpg)

Upload restarted (file is locally available now):
![loaded](https://cloud.githubusercontent.com/assets/2737900/11336928/777d4d7e-91e9-11e5-989b-d6778d4643ea.jpg)

Note that my numbers from above are not valid for the current beta version. The menus during download and after successful download seem to be correct. It is just the menu if the download was cancelled which is still wrong.

However, since the details view is being removed, this issue is obsolete, isn't it?
-> https://github.com/owncloud/android/pull/1304

**Comment by AndyScherzinger** [comment] 2015-11-23 13:47
@LukeOwncloud I asked @jancborchardt since I am unsure what happens in the download use case.

**Comment by tobiasKaminsky** [comment] 2016-03-14 09:04
@AndyScherzinger is this still valid?

**Comment by AndyScherzinger** [comment] 2016-03-14 09:17
I just checked Luke's latest description with downloading a file and aborting the download and this is still valid.

**Comment by davivel** [comment] 2016-11-21 14:10
Beta process is going to change. Current beta branch will not be maintained anymore. If this is detected in a stable version, please reopen.

And thanks for reporting! :)

**Closed by davivel** 2016-11-21 14:10 UTC
Labels: Beta, Needs info
