### ISSUE TITLE
Sync only one wifi continues after connection switch to mobile

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1166] opened 2015-09-20 11:43 UTC
As @AndyScherzinger reported (https://github.com/owncloud/android/issues/41#issuecomment-138266840):
One issue I had with the wifi upload on my vacation was that the sync started being on wifi (as it should) but went on after I lost the wifi connection and further uploaded the files and thus impacted my data plan (being in a foreign country) pretty heavily with no possibility to cancel the uploads (I know their is already an issue opened for cancellations)

**Comment by tobiasKaminsky** [comment] 2015-09-20 11:48
@AndyScherzinger:
Imho a "simple" solution would be to check before every file if "wifi only" is activated and wifi connected and then upload the next file and else to stop (or pause).

**Comment by tobiasKaminsky** [comment] 2015-09-20 11:48
Additionally the upload must receive a broadcast intent if the connection switches from wifi to mobile data and cancel the upload.

**Comment by AndyScherzinger** [comment] 2015-09-20 20:53
Jepp, agreeing on the solution! :)

**Comment by AndyScherzinger** [comment] 2015-10-07 10:38
any knowledge on where this would need to be implemented in actual code base?

**Comment by tobiasKaminsky** [comment] 2015-10-07 17:18
In InstantUploadBroadcastReceiver, function handleConnectivityAction

**Comment by AndyScherzinger** [comment] 2015-10-07 17:38
Hmm

        if (!intent.hasExtra(ConnectivityManager.EXTRA_NO_CONNECTIVITY)
                && isOnline(context)
                && (!instantPictureUploadViaWiFiOnly(context) || (instantPictureUploadViaWiFiOnly(context) == isConnectedViaWiFi(context) == true))) {

--> checks the connection (type) but then simply starts uploading, then comes the loop:

Cursor c = db.getAwaitingFiles();
            if (c.moveToFirst()) {
                do {

So the code checks the connection and if it is appropriate starts uploading without ever checking the precondition (connectivity + user settings) again. So I guess we would have to kind of duplicate of duplicate the check and also do this check an the beginning of each loop iteration.

**Comment by AndyScherzinger** [comment] 2015-10-07 17:45
One thing I am not sure of is the reference to context. Would it be possible that context somehow gets terminated by Android's life cycle system and at some point in time when using it for checking for the wifi connection the code would crash? (I am not that firm with Android and weak/strong references and the context's life cycle when being used in a receiver instance)

**Comment by tobiasKaminsky** [comment] 2015-10-07 17:49
1. point: you are right. Within the loop there must be an additional check. This is easy and I did it locally.
But the problem is to cancel the current upload. This can be do via FileUploader.cancel(account).
Unfortunenately I could not managed it to get a reference to FileUploader in the BroadcastReceiver. 
Therefore I gave up :/

Regarding context: I hope not. I think they stay intact as long as the app lives...

**Comment by AndyScherzinger** [comment] 2015-10-07 18:04
Not sure how to solve the second issue adhoc but wouldn't the first part (stop at least after the currently uploaded file) be an improvement compared to today.

So the other part "cancel an upload of a file during wifi connection lost" could be solved at another point in time on another opened issue. Standard case would be photos and/or videos I guess and at least for the photo use case (which probably is the main one) this would already help quite a lot.

**Comment by AndyScherzinger** [comment] 2015-10-07 18:06
@tobiasKaminsky  Would this be of any help?
--> http://stackoverflow.com/questions/10482171/how-to-get-reference-to-running-service
Lookup for a running service :)

**Comment by tobiasKaminsky** [comment] 2015-10-07 18:06
@AndyScherzinger Yes, but it would better to solve both, I thin. 
I am on IRC, if you want to discuss it.

**Comment by tobiasKaminsky** [comment] 2015-10-07 20:51
@AndyScherzinger PR is in #1191.
Maybe you can test it?

**Comment by AndyScherzinger** [comment] 2015-10-07 20:52
Nice! Did you find a solution? :)

**Comment by AndyScherzinger** [comment] 2015-10-07 20:56
I'll see if I can test drive it tomorrow during the day or in the evening!

**Comment by AndyScherzinger** [comment] 2015-10-07 20:59
Assuming we have a reconnect to another wifi, would the upload restart?

**Comment by tobiasKaminsky** [comment] 2015-10-07 21:01
The upload starts again.
But if it tries to resume the failed file or continues with the next one, I cannot say.
But I would bet, that it does not retry :/

**Comment by masensio** [comment] 2016-02-19 14:15
Now #1191 is merged on master. 
I think that PR fixes this issue, so I'll close it.

Thanks @tobiasKaminsky and @AndyScherzinger

**Closed by masensio** 2016-02-19 14:15 UTC
