### ISSUE TITLE
Unable to sync files containing ':' in name

### ISSUE THREAD

**Issue by rahra** [owncloud/android#962] opened 2015-04-26 07:49 UTC
The Onwcloud Android app fails to download files from the Owncloud server if there is a ':' in the file name. The GET request looks like the following example:
GET /owncloud/remote.php/webdav/Notes/2014-11-21%2014%3A38%3A10.txt HTTP/1.1
The HTTP server responds with 200 but the app then says 'Download failed'. If the file is renamed by replacing all ':'s to some other character, the download works.

**Comment by davivel** [comment] 2015-04-27 07:32
We are not able to reproduce it. What are your device model and version? I'm suspecting of a problem with the ':' in the local file system. Could you check if you can rename a local file to include a ':' with a regular file browser?

Thanks.

**Comment by rahra** [comment] 2015-04-27 08:09
Sorry for filing this report because it is definitely a matter of the local file system. On the SDcard there is FAT by default which doesn't allow ':' in the file names.

FYI what I did:
I used the ['MyOwnNotes' app](https://f-droid.org/repository/browse/?fdfilter=myownnotes&fdid=org.aykit.MyOwnNotes) which creates file names with ':' in it but on the server. The server of course allows such names because it usually uses a modern file system (which is UFS with FreeBSD in my case) and not FAT.
But when I try to download those files with the OwnCloud client then it fails to create the file locally.

I suggest to make the error message more clear because it says 'Download failed' but actually the download is ok but the file creation fails.

**Comment by davivel** [comment] 2015-05-04 06:55
Sure, the message should be better. 

Ideally, the app should become able to deal with FAT in SD Cards. Unfortunately I couldn't tell when we'll be able to handle it.

**Comment by michaelstingl** [comment] 2019-04-10 11:21
SD addressed in https://github.com/owncloud/android/issues/10

**Closed by michaelstingl** 2019-04-10 11:21 UTC
Labels: bug, local file system, sync::download
