### ISSUE TITLE
Login with password containing umlauts doesn't work

### ISSUE THREAD

**Issue by marcelklehr** [owncloud/android#1322] opened 2015-12-03 15:06 UTC
### Expected behaviour
Successful login with the provided credentials.

### Actual behaviour
Login failed.

### Steps to reproduce
1. Install owncloud and set password to `123ä`
4. Try logging in with the web interface -- login successful.
2. Try to login with android client.
3. Login fails.

### Environment data
Android version: 4..2.2

Device model: Fairphone

Stock or customized system: Customized

ownCloud app version: 1.8.0

ownCloud server version: 8.1.3

#### ownCloud log (data/owncloud.log)
```
Warning	core	Login failed: 'alphabet' (Remote IP: '178.5.136.87)
```

**Comment by marcelklehr** [comment] 2015-12-03 15:12
I just updated my server instance to v8.2.1 and the problem persists.

**Comment by LukasReschke** [comment] 2016-03-30 16:17
https://github.com/owncloud/android-library/pull/114 probably fixes this.

**Comment by sedric** [comment] 2016-04-18 12:14
Problem persist with server 9.0 and android app 1.9.1.

I test the following characters in the password : €, é.
It might be a character encoding issue on client side as the webapp authentication works.

**Comment by davivel** [comment] 2016-04-18 13:21
@rperezb , @MTRichards  I think we should set this to higher priority.

**Comment by rperezb** [comment] 2016-04-21 06:47
thx @davivel added to talk about it today as part of the next sprint planning

**Comment by sedric** [comment] 2016-04-21 09:11
Hi,

I do some other tests recently with the desktop client and it act the same. So the problem is maybe not in the android app but in a shared basecode ?

I don't know if I should open an issue in owncloud/client as well or if this issue should be moved in owncloud/core ?

**Comment by rperezb** [comment] 2016-04-21 09:48
@sedric this may be related to: https://github.com/owncloud/core/issues/7894
In the short term, we are likely to include a fix on the Android app, following @davivel suggestion

**Comment by malkomich** [comment] 2016-04-25 09:09
This issue is being fixed in PR #119

**Comment by AndyScherzinger** [comment] 2016-04-25 11:15
As in https://github.com/owncloud/android-library/pull/119

**Comment by malkomich** [comment] 2016-04-25 11:39
Thx @AndyScherzinger , comment updated ^^

**Comment by davivel** [comment] 2016-04-28 13:13
Anybody here creating users in Mac OS from Chrome or Safari? Please, see https://github.com/owncloud/core/issues/7894#issuecomment-215415935 .

**Comment by marcelklehr** [comment] 2016-04-28 13:19
@davivel Nope, I was using windows.

**Comment by davivel** [comment] 2016-04-29 07:33
Great; in that case the PR linked before should help you. We are validating it right now, the test will take a bit longer due to the issue we discovered about Webkit + Mac.

**Comment by davivel** [comment] 2016-05-03 16:42
This is now merged in master, will be available in next release of the OC app.

**Closed by davivel** 2016-05-03 16:42 UTC
Labels: bug, login, Server Involved
