### ISSUE TITLE
[BUG] Changing the account does not work properly in some cases

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/android#2626] opened 2019-08-16 10:25 UTC
### Actual behaviour
Having an issue when two accounts have been added into the application that are hosted on the same server and you switch between them.

Often when switching between accounts, the application gets confused and in the end it will only show content from one of the accounts even if you switch to the other. When it happens the "manage accounts" shows the confusion, with the bold username being the same for both accounts, with only the username@domain differing. Depending on which account you're on, you could get stuck on either one (only been using two accounts for the moment). 

When it happens closing the application (and removing it from the running list) doesn't resolve the issue, only restarting the phone.

### Expected behaviour
The account is switched properly. I see only the content from the selected account.
 
### Steps to reproduce
1. Create two accounts on the same server
2. Add different content
3. Add these two accounts to the app
3. Switch between the accounts

### Environment data
Android version:
8.0.0
Device model: 
Samsung S7
ownCloud app version:
2.11.1
ownCloud server version:
10.2.0.5

**Comment by ChrisEdS** [comment] 2019-08-16 10:26
I will try to get a video of the behavior and logs in addition.

**Comment by davigonz** [comment] 2019-08-19 12:33
> I will try to get a video of the behavior and logs in addition.

Ok, thanks for the feedback

**Comment by NiceFeather** [comment] 2019-11-11 09:31
I have three user accounts which added into the app and located at left panel, but chaos in account switching, all contents combined with the account wasn't working propely in right file list view. I think this is an emergent bug need to be fix ASAP.

**Environment data**

- Android version:
8.0.0
- Device model:
Samsung S7 edge
- ownCloud app version:
v2.13.1
- ownCloud server version:
v10.2.1

**Comment by NiceFeather** [comment] 2019-11-13 15:58
BTW, this is a significant bug, when will this fix be put on the development schedule?

**Comment by davigonz** [comment] 2019-11-18 07:47
Hu @NiceFeather , this will be addressed during the login rearchitecture that will start soon.

**Comment by NiceFeather** [comment] 2019-11-19 16:41
>  I will give you more details as soon as we know when it will be finally scheduled.

OK, Thanks in advance.

**Comment by abelgardep** [comment] 2021-02-11 15:46
I think that this issue was fixed in 2.15 when we finished the login re-architecture. I have not reproduced any weird behavior related to multi-account since then.

@NiceFeather @ChrisEdS If you can reproduce it with 2.16, please, feel free to reopen.

**Closed by abelgardep** 2021-02-11 15:46 UTC
Labels: accounts, bug
