### ISSUE TITLE
Sync complete Directorys

### ISSUE THREAD

**Issue by Alexandero89** [owncloud/android#1133] opened 2015-09-03 20:15 UTC
Hey Guys,

just had the problem that i need to sync a complete Directory in my OwnCloud-Server to my Android-Device.
Just for Example "Music". If i add a Track to the Directory it should sync to the Server.

Thx in advance!

**Comment by strugee** [comment] 2015-09-05 03:34
Duplicate of #3

**Closed** 2015-09-17 17:32 UTC
