### ISSUE TITLE
Version 1.9.0 not working as expected on Lollipop

### ISSUE THREAD

**Issue by Spielmops** [owncloud/android#1467] opened 2016-02-07 13:07 UTC
This version does not upload photos on automatic, when installed on Lollipop. So I tried to upload a photo manually. Without success and without any errormessage. Installed on Kitkat (4.2.x) it works.
I tried the newest beta with the same result and an enormous error-message stating it has something to do with permissions. (This issue has nothing to to with sd-cards, which are not writable!) 

Spielmops

**Comment by tobiasKaminsky** [comment] 2016-02-08 06:49
Can you post the error message of the beta version?
As this might be the same reason for the crash of the official version this might be very helpful.

**Comment by Spielmops** [comment] 2016-02-08 14:19
The following error-message apeared after a shot with the camera (open 
camera) on a Fairphone2 with lollipop:


************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start receiver 
com.owncloud.android.files.InstantUploadBroadcastReceiver: 
java.lang.SecurityException: Permission Denial: opening provider 
com.android.externalstorage.ExternalStorageProvider from 
ProcessRecord{2c4b1c18 9372:com.owncloud.android.beta/u0a89} (pid=9372, 
uid=10089) requires android.permission.MANAGE_DOCUMENTS or 
android.permission.MANAGE_DOCUMENTS
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2616)
at android.app.ActivityThread.access$1700(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.SecurityException: Permission Denial: opening 
provider com.android.externalstorage.ExternalStorageProvider from 
ProcessRecord{2c4b1c18 9372:com.owncloud.android.beta/u0a89} (pid=9372, 
uid=10089) requires android.permission.MANAGE_DOCUMENTS or 
android.permission.MANAGE_DOCUMENTS
at android.os.Parcel.readException(Parcel.java:1546)
at android.os.Parcel.readException(Parcel.java:1499)
at 
android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3356)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:4624)
at 
android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2472)
at 
android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1442)
at android.content.ContentResolver.query(ContentResolver.java:462)
at android.content.ContentResolver.query(ContentResolver.java:422)
at 
com.owncloud.android.files.InstantUploadBroadcastReceiver.handleNewPictureAction(InstantUploadBroadcastReceiver.java:116)
at 
com.owncloud.android.files.InstantUploadBroadcastReceiver.onReceive(InstantUploadBroadcastReceiver.java:72)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2609)
... 9 more

************ DEVICE INFORMATION ***********

Brand: Fairphone
Device: FP2
Model: FP2
Id: FP2
Product: FP2

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: r4275.1_FP2_gms36_1.1.7

***************End of ErrorLog **************************

*********** Additional information by Logsender *************

Ich use the Owncloud-client since long time so I know how to use it. On 
another phone Huawei 610 owncloud (not beta) is working as expected. On 
this phone it is not even possible to upload a picture manually. The app 
seems to work for one second and then nothing - no error message. With 
the version 1.9 non-beta everything is the same without this error-log 
from above. when the photo  is shot an error-message apears: owncloud 
was terminated.

Regards and I hope it helps,

Hartmut

PS: if you need a tester, let me know ...


Am 08.02.2016 um 07:49 schrieb Tobias Kaminsky:
>
> Can you post the error message of the beta version?
> As this might be the same reason for the crash of the official version 
> this might be very helpful.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/android/issues/1467#issuecomment-181228084>.
>

-- 
------------------------------------------------------------------------
"Ich habe keine besondere Begabung, sondern bin nur leidenschaftlich 
neugierig." (Einstein)
spielmops.org <http://spielmops.org>

**Comment by Spielmops** [comment] 2016-02-11 20:56
I take one part back: uploading a file by hand is now working. The app "privacy impact" has a bug, where it shows to be active but is not. One time checking "not active" then check again "active" was it. Uploading by hand is OK.

That leaves automatic uploads of photos: it's not working, error-message has not changed.

Spielmops

**Comment by davivel** [comment] 2016-02-24 20:24
Hi, @Spielmops, I have some doubts.

What do you mean with "privacy impact"? Is it another app in your device?

About the camera app, "Open Camera" is the name of the app?

Thanks.

**Comment by Spielmops** [comment] 2016-02-25 19:23
Privacy Impact is another app on my fairphone. For information: have a look at forum.fairphone.com. And "Open Camera" is in fact the name of the camera app  - information at f-droid.org. I tried it with another camera, the result is exact the same.

There are some android functions, which changed their behaviour in lollipop, so that several apps do not work the same way as since kitkat .

Spielmops

**Comment by davivel** [comment] 2016-02-26 10:42
Thanks, @Spielmops . Probably yours is another case of a camera app that doesn't trigger the NEW_PICTURE event the app expects. I will double check before redirecting you to another issue.

I'd guess that you are not interested in installing the Google Camera app, right?

**Comment by davivel** [comment] 2016-02-26 19:20
No, I was wrong. Open Camera triggers NEW_PICTURE, and instant upload of picture works work me.

Tested with Open Camera version 1.27, default installation (no setting modified); ownCloud for Android, version 1.9.1; Nexus 5 with Android 6.0.1.

What's your version of Open Camera? Did you modify its settings? 

Do you see any error notification from the ownCloud app when the picture is taken, or nothing at all?

**Comment by davivel** [comment] 2016-02-26 19:21
Oh, please, could you update to ownCloud for Android 1.9.1? Thanks.

**Comment by Spielmops** [comment] 2016-02-27 17:55
@davivel 
Did you read the first two posts?
Spielmops

**Comment by Spielmops** [comment] 2016-02-27 17:59
Update to version 1.9.1 did not change anything.
Spielmops

**Comment by masensio** [comment] 2016-02-29 09:00
Hi @Spielmops,

if I'm not wrong you are running a beta version and you have this problem, isn't it?

In the log I can see: 
ProcessRecord{2c4b1c18 9372:com.owncloud.android.beta/u0a89} (pid=9372,
uid=10089) requires android.permission.MANAGE_DOCUMENTS or
android.permission.MANAGE_DOCUMENTS
So beta version have to add this permission to the AndroidManifest. I think it is need to work with ExternalStorageProvider.

I think, we have different results in the tests because we are using the official app and you are using a beta version. Beta version contains some features which official app hasn't got yet. 
In that case, this issue must be fix in beta version or wait until we will merge External Storage PR on master.

@tobiasKaminsky could you check if beta version has MANAGE_DOCUMENTS in AndroidManifest? Maybe it is a first step to fix this issue.  If this permission won't fix it we need to search another research if the problem is only in beta or not.

Thanks

**Comment by Spielmops** [comment] 2016-02-29 17:45
When I got my new phone, I tried the normal version with no luck, so I installed the beta-version with no luck either but with the error-message from above. So I changed back to the normal version with the intend that fdroid gives me a message when an update is available. The update is 1.9.1 and that changes nothing.

Spielmops

**Comment by AndyScherzinger** [comment] 2016-02-29 17:58
@Spielmops have you uninstalled the beta? Since the log you posted is from the beta version as mentioned by @masensio 
@masensio the permission exception was beta only since the was the Marshmallow test drive but has been fixed in the latest couple of beta releases with the new permission api implementation.

**Comment by Spielmops** [comment] 2016-02-29 20:18
> So I changed back to the normal version
Spielmops

**Comment by AndyScherzinger** [comment] 2016-02-29 20:20
I get that @spielmops but then the log would have to be a different...  ;)

**Comment by Spielmops** [comment] 2016-02-29 20:24
Why? I installed the beta, got that error-message (and send it) and uninstalled the beta.

**Comment by AndyScherzinger** [comment] 2016-02-29 20:34
Yes, but that is an error message from the beta client (which should be there in the actual beta). And this error should occur in the 1.9.1 official client, when the beta is not installed.

**Comment by Spielmops** [comment] 2016-02-29 20:39
Sorry, but I do not get it: the error message is from a beta client and the error occurs in the version 1.9.1 official client, but that version gives no error-message. And the beta is not installed. So what is the problem?

**Comment by AndyScherzinger** [comment] 2016-02-29 20:49
Can you tell me which version of the beta client you installed? See preferences at the bottom.

**Comment by Spielmops** [comment] 2016-02-29 20:55
Version 20160120 - Added on 2016-01-21 from fdroid

**Comment by AndyScherzinger** [comment] 2016-02-29 21:32
Ah, I see. Unfortunately the beta build don't make it to fdroid at the moment. The latest apks can be found here and should fix the permission bug you are experiencing:
https://github.com/owncloud/android/tree/beta/apks

**Comment by Spielmops** [comment] 2016-03-01 15:41
How do I get apk's from there? The normal ways don't work

Spielmops

**Comment by AndyScherzinger** [comment] 2016-03-01 15:50
this should probably work: https://github.com/owncloud/android/raw/beta/apks/owncloud-beta-20160206.apk

**Comment by Spielmops** [comment] 2016-03-01 17:47
The beta from above installed, configured, one click on shutter and:

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start receiver com.owncloud.android.files.InstantUploadBroadcastReceiver: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{1295118a 10786:com.owncloud.android.beta/u0a121} (pid=10786, uid=10121) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2616)
at android.app.ActivityThread.access$1700(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{1295118a 10786:com.owncloud.android.beta/u0a121} (pid=10786, uid=10121) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
at android.os.Parcel.readException(Parcel.java:1546)
at android.os.Parcel.readException(Parcel.java:1499)
at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3356)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:4624)
at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2472)
at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1442)
at android.content.ContentResolver.query(ContentResolver.java:462)
at android.content.ContentResolver.query(ContentResolver.java:422)
at com.owncloud.android.files.InstantUploadBroadcastReceiver.handleNewPictureAction(InstantUploadBroadcastReceiver.java:116)
at com.owncloud.android.files.InstantUploadBroadcastReceiver.onReceive(InstantUploadBroadcastReceiver.java:72)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2609)
... 9 more

************ DEVICE INFORMATION ***********
Brand: Fairphone
Device: FP2
Model: FP2
Id: FP2
Product: FP2

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: r4275.1_FP2_gms36_1.1.7

**Comment by AndyScherzinger** [comment] 2016-03-01 22:41
@tobiasKaminski can you have a look? I'm not at a pc at the moment.

**Comment by Spielmops** [comment] 2016-03-29 16:28
Same with version 20160321 ...
Spielmops

**Comment by Spielmops** [comment] 2016-04-25 07:14
Tried today version 20160410: instant upload works again !
Spielmops

**Closed** 2016-04-25 07:33 UTC
Labels: Beta, bug, instant_uploads

**Comment by AndyScherzinger** [comment] 2016-04-25 07:35
I'll close the issue for now then. Please reopen in case the instant upload doesn't work again.

Just FYI in case you want to update: The latest version in beta is 20160419 at the moment (has a bug for share from other apps which will be fixed in the next beta release).
