### ISSUE TITLE
Remove »Details« action from file menu

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1275] opened 2015-11-09 12:17 UTC
The details screen serves no real purpose anymore. It only duplicates the info which is available elsewhere:
- name
- size
- date
- file type (it even wrongly states SVG files are of type JPEG)
- ability to favorite

So I would say we should get rid of that screen and remove the action in the long-press file menu. This also serves as reducing the actions in the file menu, see https://github.com/owncloud/android/issues/1144

cc @tobiasKaminsky @AndyScherzinger @davivel @masensio @MTRichards

**Comment by AndyScherzinger** [comment] 2015-11-09 13:27
How can this info be reached? Files else open with an app that support the mime type, so if it is a pdf for example I can only see the "details" via the menu item on the long click action, right?

**Comment by LukeOwncloud** [comment] 2015-11-09 14:26
@AndyScherzinger name, size, date are shown in folder view. ability to favorite is in menu.

@jancborchardt What is not available is the exact, absolute file date (including seconds). But I think it is not very important, same as the file type. So I like the idea to remove the details view.

**Comment by jancborchardt** [comment] 2015-11-09 14:45
@AndyScherzinger yeah, that screen can only be reached by the details item in the long click action. Otherwise it’s displayed for filetypes which can’t be opened by ownCloud. Which is ok – but it shouldn’t be duplicated as action in the long press menu.

In addition, the duplicate info there about »type, size, date« can be removed, and that whole screen should be beautified a bit more. Kind of like the empty folder message in the web interface of ownCloud:
![capture du 2015-11-09 15-44-51](https://cloud.githubusercontent.com/assets/925062/11036435/d7e67d1c-86f8-11e5-9878-7e333da3070a.png)

**Comment by AndyScherzinger** [comment] 2015-11-09 16:50
That isn't happening (anymore), at least not for me on the branches. It just displays a Toast saying no app found for the file type. So at least on the branches (will have to check the master), the long click really is the only way to get to the details screen...

I get @LukeOwncloud's comment and yes, atm I would also suggest to drop the screen. So not sure if the Toas is fine or the screen makes it look a bit nicer :)

**Comment by jancborchardt** [comment] 2015-11-09 17:43
Nah, the toast is fine. Even better, because it makes no sense redirecting people to a separate screen when the file can’t be opened anyway. However I can’t see the toast. For me for example, a .gpx file brings up the details screen.

**Comment by AndyScherzinger** [comment] 2015-11-09 17:53
Than it works as designed already ... on master :) 

(probably even in the release 1.8.0; not sure though)

**Comment by AndyScherzinger** [comment] 2015-11-09 17:54
Should thus the issues' requirement be to simply remove the Details action from the menu?

**Comment by LukeOwncloud** [comment] 2015-11-09 18:46
> For me for example, a .gpx file brings up the details screen.

Same for me with the beta version: The details are shown and below a download progress bar.
Do we need that progress bar? It is also shown in the notification bar.

About "file type can't be opened". I think that is very user unfriendly:
If users click a file, they want to open it. If oC can't determine the right app automatically, wouldn't it be better to ask the user how to open the file? That is what Windows does...

I suggest a menu similar to the "open with" option used by ES File Explorer:
![photo_2015-11-09_19-45-12](https://cloud.githubusercontent.com/assets/2737900/11042944/6cb52544-871a-11e5-9617-89df606eb803.jpg)

**Comment by AndyScherzinger** [comment] 2015-11-09 18:57
The screen only appears when the file hasn't been downloaded yet. 
The open with is actually what happens :)  But the action in this case is smarter and asks the system for apps to open the file. In case one or more apps are found it launches the Open with else it shows the Toast. A Windows behavior doesn't really make sense since the call scans the phone via Android for apps with a compatible mime type filter. If it doesn't find one it is basically impossible to open the file from within owncloud via the intent.

**Comment by LukeOwncloud** [comment] 2015-11-09 19:14
> A Windows behavior doesn't really make sense
I disagree. Windows determines the possible application by examining the extension. Also Android uses the extension to determine the mime type. So if a file was renamed for whatever reason, the correct app type cannot be determined. And if no 100% hit is found, a simple text editor is often better than nothing (e.g. consider MS mail format .msg or source code files like .cs or .rb (on my phone no app registered for any of these but I still want to be able to open them)).

So I think there should be two types of "open with": 1) type is known, show list of registered apps (as done right now by oC) 2) type if unknown (type should be queried from user as shown in screenshot above).

**Comment by DougJod** [comment] 2015-11-21 20:13
I'm new to this project and would like to start with a simple issue so I can familiarize myself with the contribution process. 

Is this issue simply a matter of removing the 'details' item from the file menu, or do you want to remove the FileDetailFragment altogether? The detail fragment still seems to serve a purpose when downloading a file (showing progress, option to cancel download, file details) although, as pointed out already, this functionality is duplicated elsewhere.

**Comment by AkshitKrNagpal** [comment] 2016-12-31 23:41
Hi
I am new to contributing here.
Since @DougJod has not resolved conflicts in pull request #1304. I am creating a new pull request resolving the same issue.

**Comment by davivel** [comment] 2017-03-14 17:33
Mmmm, what a difficult situation. Never had before two contributors competing for the same issue.

And to make it harder... I have to disagree with the convenience of this proposal.

To me, the key is here, said by @LukeOwncloud 

> What is not available is the exact, absolute file date (including seconds). But I think it is not very important, same as the file type.

I think it **is** important. I don't see any good reason to hide information we have available for the user. In the end, there is a reason why every single file browser in each operating system out there has a 'Details', 'Info' or 'Properties' option in its contextual menu: not all the information relevant for all the users can be summarized in the space of an item in a collection. 

So, IMHO, the approach should be in the opposite direction: let's improve the details view with more relevant information that doesn't fit in the list. There are even some proposals for that in the comments in this issue.

@DougJod , @AkshitKrNagpal , I'm really sorry for not having addressed this before. Please, don't give up your interest as contributors. I reviewed the list of Jr Jobs in this repo, and though there are not many, I checked that all of them are still relevant. Let me invite you to choose on of them, assign to your self and try again.

Closing as won't fix.

**Closed by davivel** 2017-03-14 17:33 UTC
Labels: Design, enhancement, Junior Job
