### ISSUE TITLE
2.0.0 - favorite setting is not remembered

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1664] opened 2016-05-08 15:34 UTC
### Expected behaviour
When I select a file as favorite, it should remain such until I unselect it.

### Actual behaviour
I select a file as favorite.
I change the local file.
The file gets uploaded correctly.
The favorite check disappears and the file is no longer favorite.

### Environment data
Android version: 6.0.1

Device model: Nexus 5

Stock or customized system:
Stock
ownCloud app version:
2.0.0
ownCloud server version:
9.0

**Comment by rperezb** [comment] 2016-05-09 11:10
Thanks for reporting this
I have just reproduced it with a Galaxy s3 4.1.2

**Comment by lbgaus** [comment] 2016-05-09 11:55
I am seeing this issue as well.  As part of the bug fix,  can a checkbox be added to owncloud mobile version to allow all documents edited through the phone be synchronized? To me,  requiring every document that should be kept in sync to be favorited is a lot of unnecessary effort.

**Comment by rperezb** [comment] 2016-05-10 08:45
@ibgaus the plan for that is to add the option "sync folder" https://github.com/owncloud/android/issues/1136
We expect to work on it soon

cc @MTRichards

**Comment by jabarros** [comment] 2016-05-11 11:31
It is working propertly on version 1.9.1

**Comment by jabarros** [comment] 2016-05-12 09:00
Fixed in #1673 
Pending CR and QA testing

**Comment by johnripper1** [comment] 2016-05-14 14:14
Couldnt say it better. +1 on this error.

And confirm 1.9.x always worked

**Comment by davivel** [comment] 2016-05-18 10:31
Fixed now. Will be released in version 2.0.1, probably sooner than usual.

**Closed by davivel** 2016-05-18 10:31 UTC
Labels: bug

**Comment by johnripper1** [comment] 2016-05-20 12:38
Thanks everybody for peoblem identification and fix.

Is there a ETA for the 2.0.1 version in  Google Play?

**Comment by davivel** [comment] 2016-05-20 13:09
Not yet, but should be sooner than the usual period, since this bug and #1607 are specially annoying. Probably we'll make a small release with bug fixes.

**Comment by rperezb** [comment] 2016-05-23 08:17
For reference, this was qa following https://github.com/owncloud/QA/issues/229
thx @jesmrec !
