### ISSUE TITLE
Problem with special characters in passwords

### ISSUE THREAD

**Issue by fmai** [owncloud/android#1509] opened 2016-03-14 20:52 UTC
### Expected behaviour
If I set my password to test² I'm able to login to ownCloud via web or the native clients for debian and Windows 7. This should be the case for the android app also.

### Actual behaviour
The app shows "wrong username or password" if I try to connect.
If I set the connection to unencrypted and sniff the traffic, I can see that the app changes some special characters to question marks. Screenshots can be found here (german):
https://florianmai.de/2016/03/13/owncloud-fuer-android-hat-probleme-mit-sonderzeichen/

### Steps to reproduce
1. Setup an account
2. Change password to something containing characters like ² or ł
3. Login via android app

### Environment data
Android version: 5.1.1

Device model: Oneplus One

Stock or customized system: Stock OxygenOS 2.1.4

ownCloud app version: latest on the play store

ownCloud server version: 8.2.2

#### Web server error log
```
Webserver is working fine
```

#### ownCloud log (data/owncloud.log)
```
No log found there
```

**Comment by AndyScherzinger** [comment] 2016-03-15 08:38
@davivel most likely related or a duplicate of #1322 which is still open

**Comment by malkomich** [comment] 2016-04-22 09:33
Yes, this issue is duplicated in #1322 as you said @AndyScherzinger . So we can close this issue and follow it in the #1322 one.

**Closed by malkomich** 2016-04-22 09:33 UTC
Labels: bug, contributions are welcome, login, Server Involved
