### ISSUE TITLE
Yellow arrow when the file has a duplicated name

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1554] opened 2016-03-22 17:14 UTC
### STEPS TO REPRODUCE

1.- Upload a file
2.- Upload again the same file in the same folder
### ACTUAL BEHAVIOUR

The first upload file is marked with yellow arrow
### EXPECTED BEHAVIOUR

The first file is not marked

Tested with Nexus 9
Android v6
App version 1.9.1
Server version v9

**Comment by jesmrec** [comment] 2016-03-29 09:29
postponed

**Comment by davivel** [comment] 2016-03-29 15:04
Yeah, but let's keep it open, to address in the future.

To clarify: will not be fixed in the context of #1493 because:
  - it's a quite old bug, not really related with the uploads view;
  - fixing it requires modifying IndexedForest.java, implying some risk for all the app; would require some broad-scope testing after fixing, and that would be the third time for the same feature; too much
  - the bug is not specially annoying for the user

**Comment by michaelstingl** [comment] 2019-04-10 11:49
Can no longer be reproduced. (probably fixed with the changes about the new icons)

In case this happens again, please open a new issue. (too many things changed)

**Closed by michaelstingl** 2019-04-10 11:49 UTC
Labels: bug, sync::upload
