### ISSUE TITLE
view not download - how?

### ISSUE THREAD

**Issue by doogalbear** [owncloud/android#1739] opened 2016-07-13 00:57 UTC
I installed Owncloud and am loving it except for the mobile app (android). I'm use to the Dropbox app. The Owncloud app downloads the file before I can view it where Dropbox allows me to view automatically. Can Owncloud do this and how? If not, can someone tell me how to change the default download directory for the mobile app as I don't want my phones memory filling up when I have an external memory card I could be using. 

I'm using a Samsung Galaxy S4 running 4.4.4 stock
ownCloud app version: 2.0.1
ownCloud server version: 8.0

Thank you

**Comment by davivel** [comment] 2016-07-13 16:14
Hi, @doogalbear .

There are different issues related with your problem that could help you, when implemented. Currently, in the ownCloud app files are downloaded and left in local storage until you decide to remove them (long press on the file, tap "remove", choose "local only" in the dialog").

Dropbox by default downloads the file, and later removes it silently from local storage. In the case of media files, maybe they also stream them (I'm not sure right now) so that you don't need to wait for the full file is down before start watching. None of these features are available in OC for the moment.

Some issues you probably will like to track to see the state of your request may be found in the label https://github.com/owncloud/android/labels/storage . 

Issue #592 deals with streaming of video.

Issue #756 deals with adding an automatic cache that deletes local copies of the files when overpassed.

Hope this answers your doubts. Sorry for not having the solution yet.

I will close this issue as a duplicate of several others.

Thanks.

**Closed by davivel** 2016-07-13 16:14 UTC
