### ISSUE TITLE
[BUG]Some (the most) Pictures are not uploadet to my owncloud server

### ISSUE THREAD

**Issue by Rudi56** [owncloud/android#2971] opened 2020-09-24 17:23 UTC
### Actual behaviour
-I would send all new pictures to my owncloud server
so i take some (10) pictures with my camera. 
2 of them are uploadet to my server. 8 pics not. :(
so, i will take a new test.
next day, i try the same. taken 10 pictures with my cam, 
now 4 pictures are uploaded. 6 pics not.
I would that all new Photos are send to my owncloud.

### Expected behaviour
-I would that all new Photos are send to my owncloud.
 
### Steps to reproduce
1. take  a lot of photos with your phone. (my is a oneplus 5 with android 10)
2. see what photos are uploadet

Can this problem be reproduced with the official owncloud server?
Yes
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 10 OxygenOS 10

Device model: ONEPLUS A5000

Stock or customized system:

ownCloud app version: 2.15.1 fresh from playstore

ownCloud server version:10.2.0 and 10.3.2

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
Sorry for my bad english, it is not my native language. i hope, you can read and understand what i wrote.

**Comment by jesmrec** [comment] 2020-09-28 06:41
We've had other issue like this one about OxygenOS: https://github.com/owncloud/android/issues/2919

The user fixed by himself the problem, please check the last message of that post. The problem seems to be related with OxygenOS.

**Comment by jesmrec** [comment] 2022-06-23 10:54
still reproducible? @Rudi56

**Comment by jesmrec** [comment] 2022-07-08 08:09
Feel free to reopen if still happens

**Closed by jesmrec** 2022-07-08 08:09 UTC
