### ISSUE TITLE
Android - Duplicate files.

### ISSUE THREAD

**Issue by jdezego** [owncloud/android#1324] opened 2015-12-03 20:58 UTC
When I upload a file from my phone to my server, the app creates a folder on my phone and copies the file to that folder... so now I have 2 copies of ever file I upload on my phone. This effectively cuts my phone storage in half, and is crazy if I want to upload hundreds or thousands of photos. What is the thinking behind this? Dropbox does not do this.

If this "feature" is going to remain then it should be able to be turned off in the settings. Yes, I could upload a file then go and delete the copy that was made on my phone, but I don't want to do this.

**Comment by enoch85** [comment] 2015-12-03 22:47
@tobiasKaminsky @davivel Will this be fixed in 2.0?

**Comment by enoch85** [comment] 2015-12-03 22:48
Seems like it https://github.com/owncloud/android/issues/819 --> Close.

**Comment by tobiasKaminsky** [comment] 2015-12-04 13:23
@enoch85 I think so, at least it is being tested right now.
Closing as duplicate of #819

**Closed by tobiasKaminsky** 2015-12-04 13:23 UTC
