### ISSUE TITLE
2.0.0 warns about an Error in upload when "Upload only on WiFi" is set

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1628] opened 2016-04-23 06:47 UTC
### Expected behaviour
When I set "Upload only on WiFi" I do expect instant uploads to start when I connect to WiFi. 

### Actual behaviour
When "Upload only on WiFi" is set, an message indicating a failed upload appears after taking a picture with a camera. The photos get uploaded as expected once connected to WiFi, so there is no error, and the behavior is expected. The error message is confusing and wrong.

### Steps to reproduce
1. set "Upload only on WiFi"
2. Turn off WiFi
3. Take a picture

### Environment data
Android version: 6.0.1

Device model: Nexus5

Stock or customized system:

ownCloud app version:
2.0.0
ownCloud server version:
9.0

___

NOTE: 

- Working on https://github.com/owncloud/android/pull/1688

TASKS:
- [ ] [DEV] Code review
- [ ] [DEV] Merge https://github.com/owncloud/android/pull/1688 to master

BUGS:

- [x] Notification showed https://github.com/owncloud/android/issues/1628#issuecomment-222127688 ; [FIXED]
- [x] Pending instant uploads are cleared as failed https://github.com/owncloud/android/issues/1628#issuecomment-222430985  [FIXED]

**Comment by tobiasKaminsky** [comment] 2016-04-23 07:05
So the best would be to have "waiting for wlan" instead of "error"?

**Comment by elpraga** [comment] 2016-04-23 07:11
I don't think there is a need for any message, or maybe, show briefly "waiting for WiFi" and then make it disappear. 

I find it quite helpful that the messages disappear when everything is OK.

I learnt that I have to check something manually when the message stays in the mortification area, and that is why is the current behavior confusing. It makes me think that something went wrong, when it is not the case and everything goes as expected.

**Comment by malkomich** [comment] 2016-04-25 11:26
It sound fine. We can consider that to enhance the information to be shown in the notifications section.

We can check this issue with https://github.com/owncloud/android/issues/481 in order to avoid useless notifications

**Comment by davivel** [comment] 2016-04-26 16:30
@elpraga, sure those are the steps to get the error notification?

From our tests, with 'only-wifi' for instant uploads, an error notification is shown if there is an upload in progress when the Wi-Fi is lost (upload is interrupted due to network change / fall). But if there is no Wi-Fi at all, then there is no error notification.

Is not that your case?

**Comment by elpraga** [comment] 2016-04-26 20:07
I remember pretty well that is not I know WiFi when I saw the error notification, but I'll double check it when I can  and post

**Comment by elpraga** [comment] 2016-04-26 20:09
The result here.

.. Sorry for accidentally closing the issue, my phone got grazy a little bit. ..

**Comment by elpraga** [comment] 2016-04-26 20:23
I can confirm.
1. WiFi and 4g on. Wifi connected
2. Switch off wifi
3. Take a photo
4. Error message appears. The picture is listed in failed uploads
5. Switch on WiFi
6. Take a picture
7. Picture gets uploaded correctly

**Comment by elpraga** [comment] 2016-04-28 14:45
Have you tried it again @davivel ? Have you been able to reproduce the behavior?

**Comment by davivel** [comment] 2016-04-28 16:48
Yes, you were right, I can reproduce it.

The point is that right now the section of failed uploads is the one where we show all the uploads that may be retried. But I understand this is annoying, specially due to the error notification. We will improve this

**Comment by johnripper1** [comment] 2016-05-03 11:55
1/ 
I just want to confirm this bug unter Andorid 6.0.1(Galaxy S6) too.

2/
Yes I call it a BUG. Since the new oc App was rolled out via the Google Play Store, I got several questions, where my (handful) users asked why the app tries to upload the pictures even if they are not connected to a WiFi network and the option "only upload on WiFi networks" is enabled.
I can understand this, because the users here (Germany) have a certain data plan and do not want to charge there plan with the data used by photo upload. Therefore they switch on option that only on WiFi networks the photos are uploaded.
When the app now reports the upload "as not possible due to an error" (on mobile networks) they assume that the app tried the upload (even without WiFi) and that in regular cases this would work and charge there data plan. They assume the error comes from a server or some other connection error. I even hat one user who switched out the photo upload, because he was afraid that under a normal situation the application would not take the WiFi upload option into account and the error came from a server error or whatever.
To break it down: There is no chance for a user to understand this error message. It totally confused end users.

3/
Beside this.I don't think this message is correct, too. There is no error. The application works as designed. Even so the application doesn't (in a functional way) not try to upload the photo, it correctly notices that there is no WiFi network and then doesn't upload it.
Maybe in a technical way the application sees this a error, but that nothing what should be reported to the end user.

I will go back to an older version until a fix is applied.

**Comment by s3b-** [comment] 2016-05-08 11:47
Just wanted to say that I came here for the same thing. I switched on the option to only upload images if my device is connected to a WiFi network and did not expect to see an error messages (or any message at all) after I took a picture while not connected to a WiFi network.

**Comment by michaelstingl** [comment] 2016-05-18 18:33
One of my users reported this too:

> I experience a bug with the Android application. I have configured the auto-upload for pictures and videos, but only when my smart phone has wireless connection.
> 
> When I'm on the road and I capture a picture, I get an upload error (print screen attached). The right behavior should be that it doesn't try to upload and it waits for wireless connection.
> 
> I have the Android app 2.0.0 on Android 5.0.

![screenshot_2016-05-18-13-13-27](https://cloud.githubusercontent.com/assets/214010/15370496/9e06f70e-1d37-11e6-9f64-18f4ca6869b7.png)

@davivel Can this be fixed for the next release? /cc @rperezb 

00005508

**Comment by davivel** [comment] 2016-05-18 18:50
@michaelstingl 

> Can this be fixed for the next release?

I'd say yes, we can. Even if we find the full way to automatic retries too hard (that's the place where I had this fixed in my head) we can deal specifically with the problem of being shown as an error. The changes in uploads were very important, and the last thing we need is that users get confused and scared.

**Comment by rperezb** [comment] 2016-05-23 08:21
I'd rather to fix here just the error shown, meaning here with the scope of the next version.
The full retries is a much more ambitious goal and it'd be good for us to release a new version not so far away due to some minor bugs.

**Comment by davivel** [comment] 2016-05-24 16:16
Work in progress in branch ```1628_prevent_that_upload_delayed_waiting_Wifi_notifies_an_error```

**Comment by davivel** [comment] 2016-05-25 09:13
Solved in #1688.

**Comment by michaelstingl** [comment] 2016-05-25 09:28
@davivel Very cool – thanks! There is no milestone. Will this be included in the 2.2.1 release?

**Comment by davivel** [comment] 2016-05-25 11:18
2.0.1, I hope ;) .

Probably, need confirmation from @MTRichards and @cmonteroluque , but I'd say it's an easy go-in.

**Comment by MTRichards** [comment] 2016-05-25 12:05
Makes sense, and a good improvement. @davivel confirmed!

**Comment by cmonteroluque** [comment] 2016-05-26 15:48
thanks @davivel

**Comment by jesmrec** [comment] 2016-05-27 11:53
### Bug

#### Steps to reproduce
1.- WiFi disabled
2.- Instant uploads enabled with "only wifi"
3.- Take a pic

#### Actual behaviour
A notification "Uploading" appears for a while on the top.

#### Expected behaviour
Instant uploads and their notifications should be performed when wifi is back. Any notification should be displayed, so that the user can be confused. 

Tested with HTC One v4.3

**Comment by davivel** [comment] 2016-05-27 11:56
I'll have a look; in my test device was in and out too fast to notice, but in others the notification is clearly visible.

**Comment by davivel** [comment] 2016-05-27 13:16
@jesmrec , bug fixed; test again, please.

**Comment by jesmrec** [comment] 2016-05-30 07:37
### Bug

#### Steps to reproduce
1.- WiFi disabled
2.- Instant uploads enabled with "only wifi"
3.- Take a pic
4.- Open the uploads view and tap on "clear failed" or "clear all finished"

#### Actual behaviour
Pending instant uploads are cleared and not uploaded any more 

#### Expected behaviour
Instant uploads are not cleared. They remain awaiting to the wifi connection

Tested with HTC One v4.3

cc @davivel

**Comment by jesmrec** [comment] 2016-05-30 09:23
Approved!!! all bugs fixed and correct behaviour

cc @davivel @jabarros @malkomich

**Comment by davivel** [comment] 2016-05-30 10:15
In!

Will be released soon in version 2.0.1

**Closed by davivel** 2016-05-30 10:15 UTC
Labels: approved by qa, blue-ticket, enhancement, notifications, sync::instant_upload
