### ISSUE TITLE
Crash when fast slide down in folder with lot of pics

### ISSUE THREAD

**Issue by nedimhx** [owncloud/android#947] opened 2015-04-16 21:57 UTC
When I enter in folder where is placed more folders and pictures and when I slide fast to the down, app just crash.

Can It be becouse I have update code with this pull request https://github.com/owncloud/android/pull/944

**Comment by tobiasKaminsky** [comment] 2015-04-18 06:43
Please see: https://github.com/owncloud/android/issues/921#issuecomment-91962995
The problem is that the thumbnails are not removed from the memory and therefore lead to an out of memory crash.

**Comment by masensio** [comment] 2015-05-07 07:37
Hi @nedimhx,

We are working to fix the thumbnails problems
To know if our changes solves this problem, we need a description of this bug, to reproduce it in our tests.
Could you please describe your problem specifying: device, Android version, app version, server version and the steps to reproduce it? Please indicate also the number of files (aprox) that you have in the folder.
You can use the template https://github.com/owncloud/android/blob/master/issue_template.md

Thanks

**Comment by masensio** [comment] 2015-05-22 06:45
Hi @nedimhx,

we've included some fixes in our develop branch to avoid this crash. 
That update will be available on the next release of the app (1.7.2).

So I close the issue.

**Closed by masensio** 2015-05-22 06:45 UTC
Labels: browse, bug, image
