### ISSUE TITLE
Need to view from server without downloading

### ISSUE THREAD

**Issue by jdezego** [owncloud/android#1574] opened 2016-03-29 13:41 UTC
Let's say I upload some images from my Android phone's photo gallery into a folder called "Uploads" on my ownCloud server. When I use the ownCloud app to view the Uploads folder, if I tap an image that I want to see, it gets automatically downloaded to my phone and put in a new folder named Uploads. Great... If I view 100 photos now I have 100 duplicate images on my phone wasting space. Seems to me the act of _downloading and saving_, as opposed to simply viewing the image on the server, should be an optional selection. For example long press on the image and choose Download from a popup menu.

**Comment by tobiasKaminsky** [comment] 2016-03-29 17:46
Please see #1044 
cc: @jancborchardt

**Comment by LukeOwncloud** [comment] 2016-04-23 04:35
Duplicate of https://github.com/owncloud/android/issues/588
https://github.com/owncloud/android/issues/714 is about finding a solution. As you can see there is no easy, one-fit-all solution, but this issue is being worked on. Until it finds its way into the official version it might still some time. For now, the beta version already provides a solution. 

Closing in favor of other issues. Please check progress there.

**Closed by LukeOwncloud** 2016-04-23 04:35 UTC
