### ISSUE TITLE
[BUG] 2FA can't authorize Android app

### ISSUE THREAD

**Issue by denispavliha** [owncloud/android#2692] opened 2019-11-01 13:19 UTC
**### Actual behaviour**
I set up OAuth2+TOTP apps in ownCloud settings. Then, I am able to successfully authorize the Desktop app on Windows (after I enter my 2FA code in the browser, I close the browser and the desktop clients works). 

The Android app, though, cannot get authorized. After I successfully login via the embedded webbrowser in the Android app (because after login, ownCloud clearly recognizes my name when it wants me to authorize access), the whole procedure fails as it takes me back to the username/password login form with explanation “Wrong username or password”.

**### Expected behaviour**
After writing the 2FA code in Android app's embedded webbrowser, I should be presented with a text such as "successfully authorized Android client" or similar; instead, I am shown "Wrong username or password", i.e. being taken back to the login form after successfully entering username+password and 2FA code. Clearly the login was successful, because my name and surname (account label) are shown in the webpage at the form, yet something makes ownCloud think I can't login.
 
**### Steps to reproduce**
1. enable OAuth2 app (v0.4.1) in ownCloud settings
2. enable TOTP app (2-Factor Authentication - tried on both v0.6.0 and v0.6.1) in ownCloud settings
3. (verify setup by successfully activating a Windows desktop ownCloud client, which works)
4. try to login on Android app (or even remove account and re-add it - it does not work, it's the same)
5. after entering username, password and 6-number 2FA code, it takes me back to ownCloud login screen (in the embedded webbrowser) saying “Wrong username or password”.
6. the Android app actually gets listed under /index.php/settings/personal?sectionid=security#oauth2 but the app itself does not move on from the failed login screen.

**Can this problem be reproduced with the official owncloud server?**
No, as the test:test does not have administrative permissions and TOTP+OAuth2 apps are not installed.

**### Environment data**
Android version: MIUI Global 10.3.6 (Android 9)
Device model: Xiaomi Mi MIX 2S
Stock or customized system: stock ROM (OTA)
ownCloud app version: v2.13.1
ownCloud server version: tried on both v10.2.1 (stable) and v10.3.0 (stable)
Additional apps: OAuth2 app v0.4.1, 2-Factor Authentication app either v0.6.0 or v0.6.1

**### Logs**
#### Web server error log
(not provided)

#### ownCloud log (data/owncloud.log)
(not provided ... the log file is 1.5GB, why is there no log rotation? I can't open it :full_moon_with_face:)

**Comment by jesmrec** [comment] 2019-11-05 09:33
Not able to reproduce. After typing the 6-digits number, i'm asked for authorization and then, logged in inside the account. The environment i used is pretty similar to your one (i used a MIA2 with Android 9, the most similar i found). I used Google Authenticator to get the code to verify.

The error you are getting is `Wrong username or password`. Are you using any additional app regarding authentication? (LDAP, guest, or similar). Every detail minds.

i'm only trying to figure out, where the problem can be, since i can not reproduce. Other option is getting a test account in your server, in which you have the specific set up.

**Comment by denispavliha** [comment] 2019-11-09 10:59
Thanks, @jesmrec.

I am providing some additional logs, taken at the exact time when I tried to authorize the Android app:

`{"reqId":"CENSORED_REQUEST_ID_1","level":0,"time":"2019-11-09T10:46:03+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/CENSORED_USERNAME\/","message":"updating token CENSORED_TOKEN_73, last check is now 1573296006"}
{"reqId":"CENSORED_REQUEST_ID_1","level":0,"time":"2019-11-09T10:46:03+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/CENSORED_USERNAME\/","message":"token CENSORED_TOKEN_8AAD does not exist"}
{"reqId":"CENSORED_REQUEST_ID_2","level":0,"time":"2019-11-09T10:46:04+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/CENSORED_USERNAME\/","message":"updating token CENSORED_TOKEN_73, last check is now 1573296006"}
{"reqId":"CENSORED_REQUEST_ID_2","level":0,"time":"2019-11-09T10:46:04+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/CENSORED_USERNAME\/","message":"token CENSORED_TOKEN_8AAD does not exist"}
{"reqId":"CENSORED_REQUEST_ID_3","level":0,"time":"2019-11-09T10:46:14+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"alenka","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/alenka\/","message":"updating token 57148, last check is now 1573269167"}
{"reqId":"CENSORED_REQUEST_ID_3","level":0,"time":"2019-11-09T10:46:14+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"alenka","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/alenka\/","message":"token CENSORED_TOKEN_ACEC does not exist"}
{"reqId":"CENSORED_REQUEST_ID_4","level":0,"time":"2019-11-09T10:46:23+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/apps\/oauth2\/authorize?response_type=code&redirect_uri=oc%3A%2F%2Fandroid.owncloud.com&client_id=CENSORED_CLIENT_ID_WJeD","message":"token CENSORED_TOKEN_1 with token id CENSORED_TOKEN_76 found, validating"}
{"reqId":"CENSORED_REQUEST_ID_4","level":0,"time":"2019-11-09T10:46:23+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/apps\/oauth2\/authorize?response_type=code&redirect_uri=oc%3A%2F%2Fandroid.owncloud.com&client_id=CENSORED_CLIENT_ID_WJeD","message":"token CENSORED_TOKEN_1 with token id CENSORED_TOKEN_76 found, validating"}
{"reqId":"CENSORED_REQUEST_ID_4","level":0,"time":"2019-11-09T10:46:23+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/apps\/oauth2\/authorize?response_type=code&redirect_uri=oc%3A%2F%2Fandroid.owncloud.com&client_id=CENSORED_CLIENT_ID_WJeD","message":"token CENSORED_TOKEN_1 with token id CENSORED_TOKEN_76 found, validating"}
{"reqId":"CENSORED_REQUEST_ID_5","level":0,"time":"2019-11-09T10:46:23+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=20cd490da395675c17014826bcc9a4b4","message":"token CENSORED_TOKEN_1 with token id CENSORED_TOKEN_76 found, validating"}
{"reqId":"CENSORED_REQUEST_ID_5","level":0,"time":"2019-11-09T10:46:23+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=20cd490da395675c17014826bcc9a4b4","message":"token CENSORED_TOKEN_1 with token id CENSORED_TOKEN_76 found, validating"}
{"reqId":"CENSORED_REQUEST_ID_5","level":0,"time":"2019-11-09T10:46:23+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=20cd490da395675c17014826bcc9a4b4","message":"token CENSORED_TOKEN_1 with token id CENSORED_TOKEN_76 found, validating"}
{"reqId":"CENSORED_REQUEST_ID_5","level":0,"time":"2019-11-09T10:46:23+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=20cd490da395675c17014826bcc9a4b4","message":"token CENSORED_TOKEN_1 with token id CENSORED_TOKEN_76 found, validating"}
{"reqId":"CENSORED_REQUEST_ID_6","level":0,"time":"2019-11-09T10:46:28+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/CENSORED_USERNAME\/","message":"updating token CENSORED_TOKEN_73, last check is now 1573296006"}
{"reqId":"CENSORED_REQUEST_ID_6","level":0,"time":"2019-11-09T10:46:28+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/CENSORED_USERNAME\/","message":"token CENSORED_TOKEN_8AAD does not exist"}
{"reqId":"CENSORED_REQUEST_ID_7","level":0,"time":"2019-11-09T10:46:29+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\User\\Session::validateToken","method":"POST","url":"\/index.php\/apps\/oauth2\/authorize?response_type=code&redirect_uri=oc%3A%2F%2Fandroid.owncloud.com&client_id=CENSORED_CLIENT_ID_WJeD","message":"token CENSORED_TOKEN_1 with token id CENSORED_TOKEN_76 found, validating"}
{"reqId":"CENSORED_REQUEST_ID_7","level":0,"time":"2019-11-09T10:46:29+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\User\\Session::validateToken","method":"POST","url":"\/index.php\/apps\/oauth2\/authorize?response_type=code&redirect_uri=oc%3A%2F%2Fandroid.owncloud.com&client_id=CENSORED_CLIENT_ID_WJeD","message":"token CENSORED_TOKEN_1 with token id CENSORED_TOKEN_76 found, validating"}
{"reqId":"CENSORED_REQUEST_ID_7","level":0,"time":"2019-11-09T10:46:29+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\User\\Session::validateToken","method":"POST","url":"\/index.php\/apps\/oauth2\/authorize?response_type=code&redirect_uri=oc%3A%2F%2Fandroid.owncloud.com&client_id=CENSORED_CLIENT_ID_WJeD","message":"token CENSORED_TOKEN_1 with token id CENSORED_TOKEN_76 found, validating"}
{"reqId":"CENSORED_REQUEST_ID_7","level":1,"time":"2019-11-09T10:46:29+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"oauth2","method":"POST","url":"\/index.php\/apps\/oauth2\/authorize?response_type=code&redirect_uri=oc%3A%2F%2Fandroid.owncloud.com&client_id=CENSORED_CLIENT_ID_WJeD","message":"An authorization code has been issued for the client \"Android\"."}
{"reqId":"CENSORED_REQUEST_ID_8","level":0,"time":"2019-11-09T10:46:31+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"POST","url":"\/index.php\/apps\/oauth2\/api\/v1\/token","message":"invalidating token CENSORED_TOKEN_D4EA"}
{"reqId":"CENSORED_REQUEST_ID_8","level":1,"time":"2019-11-09T10:46:31+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"--","app":"oauth2","method":"POST","url":"\/index.php\/apps\/oauth2\/api\/v1\/token","message":"An authorization code has been used by the client \"Android\" to request an access token."}
{"reqId":"CENSORED_REQUEST_ID_9","level":0,"time":"2019-11-09T10:46:33+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/CENSORED_USERNAME\/","message":"updating token CENSORED_TOKEN_73, last check is now 1573296006"}
{"reqId":"CENSORED_REQUEST_ID_9","level":0,"time":"2019-11-09T10:46:33+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/CENSORED_USERNAME\/","message":"token CENSORED_TOKEN_8AAD does not exist"}
{"reqId":"CENSORED_REQUEST_ID_10","level":0,"time":"2019-11-09T10:46:33+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/CENSORED_USERNAME\/","message":"updating token CENSORED_TOKEN_73, last check is now 1573296006"}
{"reqId":"CENSORED_REQUEST_ID_10","level":0,"time":"2019-11-09T10:46:33+00:00","remoteAddr":"CENSORED_IP_ADDRESS","user":"CENSORED_USERNAME","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/CENSORED_USERNAME\/","message":"token CENSORED_TOKEN_8AAD does not exist"}
`

It's kind of strange that, as the last few days I am newly using DuckDuckGo browser on my Android phone, I've seen that after successfully authorizing my account, DuckDuckGo entered my ownCloud account (I could have seen the files) but soon after I switched back to the Android app, I was returned to the login screen with "Wrong username or password." like always.

Is it possible that the ownCloud Android app should be opening the authorization process from my webserver within an embedded WebView, yet the OS's browser is presented instead, which, at the end of authorization, does not provide the Android app with a necessary callback for it to understand the authorization was successful?

**Comment by ReGi00** [comment] 2020-09-29 20:09
Hi
i have exact the same problem. Can't login using android app. It forward me to login thru webpage (oauth2) then back to app and show me error "Wrong username or password"
Please help
Thanks for any hints

**Comment by michaelstingl** [comment] 2020-09-30 07:24
oauth2 needs the correct Apache modules configured. Please check in doc.owncloud.com

**Comment by denispavliha** [comment] 2020-09-30 18:12
> oauth2 needs the correct Apache modules configured. Please check in doc.owncloud.com

Michael, I believe you're referring to [these instructions](https://doc.owncloud.com/server/admin_manual/configuration/server/security/oauth2.html).

Sadly, the issue occured to me despite all these functionalities having been turned on:

`root@server:/# sudo a2enmod headers
Module headers already enabled
root@server:/# sudo a2enmod rewrite
Module rewrite already enabled
root@server:/# sudo apt-get install php-redis
Reading package lists... Done
Building dependency tree
Reading state information... Done
php-redis is already the newest version (5.3.1+4.3.0-1+ubuntu16.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@server:/#`

So I can't blame Apache on this one. 

Thanks for your kind help, though. I hope we can find a solution after all.

**Comment by cdangerdouglas** [comment] 2021-04-14 19:33
I also have a similar problem. I setup owncloud MFA and everything works fine in the browser. Trying to login from andiod or IOS app fails with "incorrect password" message. Seems I have to choose between using the app or having security.

**Comment by michaelstingl** [comment] 2021-04-14 23:12
@cdangerdouglas do you have the OAuth 2.0 app installed on the ownCloud server?
(see: https://owncloud.com/de/news/how-to-use-two-factor-authentication-with-the-owncloud-desktop-client-or-mobile-apps/)

Please make sure you also have the correct Apache modules installed:
https://doc.owncloud.com/server/admin_manual/configuration/server/security/oauth2.html#requirements

**Comment by cdangerdouglas** [comment] 2021-04-15 00:26
@michaelstingl, I was missing the oauth2 app. That was all I needed. Thank you for the tip!

**Comment by jesmrec** [comment] 2022-06-16 10:52
Closing... if problem persists, please feel free to reopen

**Closed by jesmrec** 2022-06-16 10:52 UTC
Labels: Needs info

**Comment by michaelstingl** [comment] 2022-11-04 14:09
We already have a hint in the Android docs:
https://doc.owncloud.com/android/connecting.html

I opened a PR to improve the server docs:
- https://github.com/owncloud/docs-server/pull/711
