### ISSUE TITLE
Deleting photo during upload result in 'connection error' 

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1528] opened 2016-03-17 06:06 UTC
It should rather say "file deleted locally" (note: this is also what the toast message says when clicking the failed upload item)

**Comment by davivel** [comment] 2016-03-21 10:24
Will check it.

**Comment by davivel** [comment] 2016-03-21 12:27
@LukeOwncloud , how do you reproduce it, deleting a picture that is uploading due to instant uploads?

**Comment by LukeOwncloud** [comment] 2016-03-21 14:38
1. Enabled instant uploads and Internet connection. 
2. Take photo. Wait a few until photo is saved. 
3. Change to photo gallery and delete just taken photo (I use the swipe up gesture for deleting).

**Comment by davivel** [comment] 2016-03-21 16:49
Thanks. Should be fixed now in #1493.

**Comment by jesmrec** [comment] 2016-03-22 10:41
Fixed :+1:

**Closed** 2016-03-22 10:45 UTC
Labels: 5 - To release, approved by qa, bug, uploads
